name: Setup sccache
description: Install and start the sccache daemon
inputs:
  cache-size:
    description: "Maximum sccache size"
    required: false
    default: 5g
  cache-key:
    description: "Key to use to restore and save the cache"
    required: true
runs:
  using: composite
  steps:
    - name: Setup GHA cache
      uses: actions/cache/restore@v5
      with:
        path: .sccache
        key: ${{ inputs.cache-key }}

    - name: Start sccache daemon
      uses: gacts/run-and-post-run@v1
      shell: bash
      run: |
        sccache --start-server
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      post: sccache --show-stats
      env:
        SCCACHE_CACHE_SIZE: ${{ inputs.cache-size }}
        SCCACHE_CACHE_DIR: .sccache

    - if: github.ref == "refs/heads/main"
      name: Persist GHA cache
      uses: actions/cache/save@v5
      with:
        path: .sccache
        key: ${{ inputs.cache-key }}