name: Setup sccache
description: Install and start the sccache daemon
inputs:
  cache-size:
    description: "Maximum sccache size"
    required: false
    default: 5g
  cache-key:
    description: "Key to use to restore and save the cache"
    required: true
    default: "sccache-${{ runner.os }}-${{ runner.arch }}"
  cache-dir:
    description: "Location of cache files"
    required: false
    default: "${{ runner.temp }}/.sccache"
  command:
    description: "Command to run between restoring and saving the cache"
    required: true
runs:
  using: composite
  steps:
    - name: Create cache directory
      shell: bash
      run: mkdir -p "${{ inputs.cache-dir }}"

    - name: Setup GHA cache
      uses: actions/cache@v5
      with:
        path: "${{ inputs.cache-dir }}"
        key: "${{ inputs.cache-key }}"

    - name: Start sccache daemon
      uses: gacts/run-and-post-run@v1
      with:
        run: |
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

        post: sccache --show-stats
      env:
        SCCACHE_CACHE_SIZE: ${{ inputs.cache-size }}
        SCCACHE_DIR: "${{ inputs.cache-dir }}"

    - name: Run command
      shell: bash
      run: ${{ inputs.command }}
      env:
        RUSTC_WRAPPER: sccache
        
