// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for French (`fr`).
class AppLocalizationsFr extends AppLocalizations {
  AppLocalizationsFr([String locale = 'fr']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'Profil et paramètres';

  @override
  String get userSettingsScreen_profileDescription =>
      'Votre nom d\'affichage et votre photo de profil sont visibles pour vos contacts Air et les membres de vos groupes.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Partagez des noms d\'utilisateur avec d\'autres pour qu\'ils puissent se connecter avec vous. Après la connexion, les noms d\'utilisateur ne sont plus visibles aux autres. Vous pouvez avoir jusqu\'à 5 noms d\'utilisateur.';

  @override
  String get userSettingsScreen_interfaceScale => 'Échelle de l\'interface';

  @override
  String get userSettingsScreen_help => 'Aide';

  @override
  String get userSettingsScreen_deleteAccount => 'Supprimer le compte Air';

  @override
  String get userSettingsScreen_sendWithEnter => 'Envoyer avec Entrée';

  @override
  String get userSettingsScreen_sendWithEnterDescription =>
      'Si cette option est désactivée, la touche Entrée n\'enverra pas de message.';

  @override
  String get userSettingsScreen_readReceipts => 'Accusés de lecture';

  @override
  String get userSettingsScreen_readReceiptsDescription =>
      'Si vous les désactivez, les autres ne verront pas quand vous aurez lu leurs messages et vous ne verrez pas quand ils auront lu les vôtres.';

  @override
  String get userSettingsScreen_displayNameLabel => 'Nom d\'affichage';

  @override
  String get userSettingsScreen_usernamesSection => 'Noms d\'utilisateur';

  @override
  String get userSettingsScreen_settingsSection => 'Paramètres';

  @override
  String get userSettingsScreen_helpSection => 'Aide';

  @override
  String get userSettingsScreen_accountSection => 'Compte';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Nom d\'utilisateur';

  @override
  String get settingsScreen_copiedToClipboard => 'Copié dans le presse-papiers';

  @override
  String get removeUsernameDialog_title => 'Supprimer le nom d\'utilisateur';

  @override
  String get removeUsernameDialog_content =>
      'Si vous continuez, votre nom d\'utilisateur sera supprimé et pourra être réclamé par quelqu\'un d\'autre. Vous ne serez plus accessible par son intermédiaire.';

  @override
  String get removeUsernameDialog_cancel => 'Annuler';

  @override
  String get removeUsernameDialog_remove => 'Supprimer';

  @override
  String get addMembersScreen_addMembers => 'Ajouter des membres';

  @override
  String get addMembersScreen_error_noActiveChat =>
      'un chat actif est obligatoire';

  @override
  String get contactDetailsScreen_viewSafetyCode => 'Voir le code de sécurité';

  @override
  String get safetyCodeScreen_title => 'Code de sécurité';

  @override
  String get safetyCodeScreen_tapToCopy => 'Touchez pour copier';

  @override
  String get safetyCodeScreen_copiedToClipboard =>
      'Copié dans le presse-papiers';

  @override
  String safetyCodeScreen_safetyCodeExplanation(Object displayName) {
    return 'Comparez le code de sécurité affiché avec celui de $displayName. S\'ils correspondent, vous savez que vous échangez des messages chiffrés de bout en bout avec la bonne personne.';
  }

  @override
  String get chatDetailsScreen_unknownChat => 'Chat inconnu';

  @override
  String blockedChatFooter_message(Object displayName) {
    return 'Vous ne recevrez pas de messages de $displayName tant que vous ne l\'aurez pas débloqué.';
  }

  @override
  String get inactiveChatFooter_message =>
      'Vous n\'êtes plus membre de ce chat.';

  @override
  String get chatScreen_emptyChat =>
      'Sélectionnez un chat pour commencer à envoyer des messages';

  @override
  String get removeUserDialog_title => 'Retirer l\'utilisateur';

  @override
  String removeUserDialog_content(Object displayName) {
    return 'Êtes-vous sûr de vouloir retirer $displayName du groupe ?';
  }

  @override
  String get removeUserDialog_removeUser => 'Retirer l\'utilisateur';

  @override
  String get removeUserButton_text => 'Retirer l\'utilisateur';

  @override
  String get blockContactButton_text => 'Bloquer';

  @override
  String blockContactDialog_title(Object displayName) {
    return 'Bloquer $displayName ?';
  }

  @override
  String blockContactDialog_content(Object displayName) {
    return 'Vous ne recevrez plus de messages de $displayName et cette personne ne pourra pas voir les mises à jour de votre profil. Elle ne verra pas que vous l\'avez bloqué. Vous pourrez le débloquer à tout moment.';
  }

  @override
  String get blockContactDialog_cancel => 'Annuler';

  @override
  String get blockContactDialog_block => 'Bloquer';

  @override
  String get unblockContactButton_text => 'Débloquer';

  @override
  String unblockContactDialog_title(Object displayName) {
    return 'Débloquer $displayName ?';
  }

  @override
  String unblockContactDialog_content(Object displayName) {
    return 'Vous pourrez envoyer et recevoir des messages de $displayName et cette personne pourra voir votre profil actuel.';
  }

  @override
  String get unblockContactDialog_cancel => 'Annuler';

  @override
  String get unblockContactDialog_unblock => 'Débloquer';

  @override
  String get deleteContactButton_text => 'Supprimer';

  @override
  String get deleteContactDialog_title => 'Supprimer le contact Air';

  @override
  String deleteContactDialog_content(Object displayName) {
    return 'Voulez-vous vraiment supprimer votre contact Air $displayName ? Cela supprimera le chat et son historique.';
  }

  @override
  String get deleteContactDialog_cancel => 'Annuler';

  @override
  String get deleteContactDialog_delete => 'Supprimer';

  @override
  String get addContactDialog_title => 'Ajouter un contact Air';

  @override
  String addContactDialog_content(Object displayName, Object groupTitle) {
    return '$displayName du chat de groupe \"$groupTitle\" n\'est pas un contact Air. Pour discuter, envoyez-lui une demande de contact.';
  }

  @override
  String get addContactDialog_cancel => 'Annuler';

  @override
  String get addContactDialog_confirm => 'Envoyer';

  @override
  String get changeGroupTitleDialog_title => 'Modifier le titre du groupe';

  @override
  String get changeGroupTitleDialog_content =>
      'Choisissez un titre pour le groupe.';

  @override
  String get changeGroupTitleDialog_cancel => 'Annuler';

  @override
  String get changeGroupTitleDialog_confirm => 'Enregistrer';

  @override
  String get introScreen_signUp => 'Commencer';

  @override
  String get introScreen_termsLinkText => 'Conditions d\'utilisation';

  @override
  String introScreen_termsText(Object termsOfUseLink) {
    return 'En vous inscrivant, vous acceptez nos $termsOfUseLink.';
  }

  @override
  String get invitationCodeScreen_header => 'Saisissez le code d\'invitation';

  @override
  String get invitationCodeScreen_subheader =>
      'Air est actuellement accessible sur invitation. Entrez votre code pour nous rejoindre. Si vous n\'en avez pas, demandez à quelqu\'un déjà sur Air.';

  @override
  String get invitationCodeScreen_inputLabel =>
      'Code d\'invitation (obligatoire)';

  @override
  String get invitationCodeScreen_inputHint =>
      'Saisissez votre code d\'invitation...';

  @override
  String get invitationCodeScreen_error_invalidLength =>
      'Le code doit comporter 8 caractères';

  @override
  String get invitationCodeScreen_actionButton => 'Rejoindre Air';

  @override
  String invitationCodeScreen_error_internal(Object error) {
    return 'Impossible de vérifier le code d\'invitation : $error';
  }

  @override
  String get invitationCodeScreen_error_missing =>
      'Code d\'invitation manquant';

  @override
  String get invitationCodeScreen_error_invalid =>
      'Code d\'invitation invalide. Vérifiez votre code et réessayez.';

  @override
  String get signUpScreen_header => 'Créez votre profil';

  @override
  String get signUpScreen_subheader =>
      'Votre profil est visible pour les personnes avec lesquelles vous vous connectez et les membres de vos groupes. Air exige un nom d\'affichage, mais la photo est facultative.';

  @override
  String get signUpScreen_actionButton => 'Créer';

  @override
  String get signUpScreen_displayNameInputName =>
      'Nom d\'affichage (obligatoire)';

  @override
  String get signUpScreen_displayNameInputHint => 'Ajoutez un nom...';

  @override
  String get signUpScreen_serverLabel =>
      'Choisissez le serveur sur lequel vous voulez créer votre compte.';

  @override
  String get signUpScreen_serverHint => 'NOM DE DOMAINE';

  @override
  String get signUpScreen_error_invalidDomain => 'Le domaine n\'est pas valide';

  @override
  String get signUpScreen_error_emptyDisplayName =>
      'Ajoutez un nom d\'affichage d\'au moins un caractère';

  @override
  String signUpScreen_error_register(Object error) {
    return 'Erreur lors de l\'enregistrement de l\'utilisateur : $error';
  }

  @override
  String get usernameOnboarding_header => 'Ajoutez un nom d\'utilisateur';

  @override
  String get usernameOnboarding_body =>
      'Les noms d\'utilisateur sont là pour se connecter sur Air. Ils ne sont plus visibles pour les autres une fois connecté.\n\nVous pouvez ajouter, modifier ou supprimer des noms d\'utilisateur à tout moment dans votre profil.';

  @override
  String get usernameOnboarding_syntax =>
      'Utilisez des lettres, des chiffres ou des tirets. Minimum 5 caractères.';

  @override
  String get usernameOnboarding_addButton => 'Ajouter';

  @override
  String get usernameOnboarding_next => 'Suivant';

  @override
  String get usernameOnboarding_userameInputName =>
      'Nom d\'utilisateur (facultatif)';

  @override
  String get usernameOnboarding_userameInputHint =>
      'Ajoutez un nom d\'utilisateur...';

  @override
  String get userHandleScreen_title => 'Ajouter un nom d\'utilisateur';

  @override
  String get userHandleScreen_inputHint => 'Saisissez un nom d\'utilisateur...';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Le nom d\'utilisateur ne peut pas être vide';

  @override
  String get userHandleScreen_error_alreadyExists =>
      'Ce nom d\'utilisateur est déjà utilisé';

  @override
  String get userHandleScreen_description =>
      'Choisissez un nom d\'utilisateur que d\'autres peuvent utiliser pour se connecter avec vous.\n\nUtilisez des lettres, des chiffres ou des tirets. Minimum 5 caractères.';

  @override
  String get userHandleScreen_cancel => 'Annuler';

  @override
  String get userHandleScreen_confirm => 'Ajouter';

  @override
  String get editDisplayNameScreen_title => 'Modifier le nom d\'affichage';

  @override
  String get editDisplayNameScreen_description =>
      'Choisissez un nom que les autres verront lorsque vous communiquez avec eux.';

  @override
  String get editDisplayNameScreen_cancel => 'Annuler';

  @override
  String get editDisplayNameScreen_save => 'Enregistrer';

  @override
  String systemMessage_userAddedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userAddedUser_infix => ' a ajouté ';

  @override
  String systemMessage_userAddedUser_suffix(Object user2) {
    return '$user2';
  }

  @override
  String systemMessage_userRemovedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userRemovedUser_infix => ' a retiré ';

  @override
  String systemMessage_userRemovedUser_suffix(Object user2) {
    return '$user2';
  }

  @override
  String systemMessage_userChangedTitle_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedTitle_infix_1 =>
      ' a changé le nom du groupe de ';

  @override
  String systemMessage_userChangedTitle_infix_2(Object old_name) {
    return '$old_name';
  }

  @override
  String get systemMessage_userChangedTitle_infix_3 => ' en ';

  @override
  String systemMessage_userChangedTitle_suffix(Object new_name) {
    return '$new_name';
  }

  @override
  String systemMessage_acceptedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return 'Vous avez accepté la demande de contact de $displayName effectuée via votre nom d\'utilisateur $username.';
  }

  @override
  String systemMessage_acceptedDirectConnectionRequest(Object displayName) {
    return 'Vous avez accepté la demande de contact de $displayName envoyée via un chat de groupe commun.';
  }

  @override
  String systemMessage_receivedConnectionConfirmation(Object displayName) {
    return '$displayName a accepté votre demande de contact.';
  }

  @override
  String systemMessage_newHandleConnectionChat(Object username) {
    return 'Vous avez envoyé une demande de contact au nom d\'utilisateur $username. Il se peut que la personne ne soit pas avertie immédiatement.';
  }

  @override
  String systemMessage_newDirectConnectionChat(Object displayName) {
    return 'Vous avez envoyé une demande de contact à $displayName. Il se peut que la personne ne soit pas avertie immédiatement.';
  }

  @override
  String systemMessage_receivedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return '$displayName vous a envoyé une demande de contact via votre nom d\'utilisateur $username.';
  }

  @override
  String systemMessage_receivedDirectConnectionRequest(
    Object displayName,
    Object groupName,
  ) {
    return '$displayName vous a envoyé une demande de contact via le chat de groupe $groupName.';
  }

  @override
  String systemMessage_userChangedPicture_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedPicture_infix =>
      ' a modifié l\'image du groupe';

  @override
  String systemMessage_userCreatedGroup_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userCreatedGroup_suffix => ' a créé le groupe';

  @override
  String get timestamp_now => 'Maintenant';

  @override
  String get timestamp_yesterday => 'Hier';

  @override
  String get messageBubble_sending => 'Envoi en cours';

  @override
  String get messageBubble_failedToSend => 'Échec de l\'envoi';

  @override
  String get chatList_newContact => 'Nouveau contact';

  @override
  String get chatList_newGroup => 'Nouveau groupe';

  @override
  String get chatList_emptyMessage =>
      'Ajoutez votre premier contact Air pour commencer';

  @override
  String get chatList_draft => 'Brouillon';

  @override
  String get chatList_you => 'Vous';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => 'Bloqué';

  @override
  String newChatDialog_error(Object chatName) {
    return 'Impossible d\'ajouter un chat avec le nom $chatName';
  }

  @override
  String get newConnectionDialog_newConnectionTitle => 'Ajouter un contact Air';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Saisissez le nom d\'utilisateur de la personne à qui vous voulez envoyer un message.';

  @override
  String get newConnectionDialog_inputLabel =>
      'Nom d\'utilisateur (obligatoire)';

  @override
  String get newConnectionDialog_usernamePlaceholder =>
      'Saisissez un nom d\'utilisateur...';

  @override
  String newConnectionDialog_handleExists(Object username) {
    return '$username existe. Touchez \"Envoyer\" pour envoyer une demande de contact.';
  }

  @override
  String get newConnectionDialog_cancel => 'Annuler';

  @override
  String get newConnectionDialog_confirm1 => 'Vérifier';

  @override
  String get newConnectionDialog_confirm2 => 'Envoyer';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Impossible d\'envoyer une demande de contact à $username. Veuillez réessayer.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Le nom d\'utilisateur ne peut pas être vide';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Le nom d\'utilisateur $username n\'existe pas';
  }

  @override
  String get newConnectionDialog_error_duplicateRequest =>
      'Vous avez déjà une demande de contact en attente pour ce nom d\'utilisateur.';

  @override
  String get newConnectionDialog_error_ownHandle =>
      'Vous ne pouvez pas vous envoyer une demande de contact.';

  @override
  String composer_inputHint(Object chatTitle) {
    return 'Message à $chatTitle';
  }

  @override
  String get composer_editMessage => 'Modifier le message';

  @override
  String get composer_error_attachment =>
      'Échec du téléchargement de la pièce jointe. Veuillez réessayer.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat =
        intl.NumberFormat.decimalPatternDigits(
          locale: localeName,
          decimalDigits: 2,
        );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get attachment_tryAgain => 'Réessayer';

  @override
  String get attachment_gallery => 'Galerie';

  @override
  String get attachment_camera => 'Appareil photo';

  @override
  String get attachment_file => 'Fichier';

  @override
  String get textMessage_edited => 'modifié';

  @override
  String get textMessage_hiddenPlaceholder =>
      'Utilisateur bloqué, appuyez pour afficher le message';

  @override
  String get textMessage_deleted => 'Message supprimé';

  @override
  String get linkConfirmation_title => 'Ouvrir le lien ?';

  @override
  String get linkConfirmation_description =>
      'Vérifiez l’URL pour vous assurer de vouloir l’ouvrir :';

  @override
  String get linkConfirmation_openLink => 'Ouvrir';

  @override
  String get linkConfirmation_cancel => 'Annuler';

  @override
  String get messageContextMenu_copy => 'Copier';

  @override
  String get messageContextMenu_edit => 'Modifier';

  @override
  String get messageContextMenu_save => 'Enregistrer';

  @override
  String get messageContextMenu_share => 'Partager';

  @override
  String get messageContextMenu_saveError =>
      'Échec de l\'enregistrement de la pièce jointe';

  @override
  String get messageContextMenu_saveConfirmation => 'Pièce jointe enregistrée';

  @override
  String get reportSpamButton_text => 'Signaler comme spam';

  @override
  String get reportSpamDialog_title => 'Signaler comme spam ?';

  @override
  String get reportSpamDialog_content =>
      'Air sera averti que cette personne peut envoyer des spams. Air ne peut jamais voir le contenu des chats.';

  @override
  String get reportSpamDialog_cancel => 'Annuler';

  @override
  String get reportSpamDialog_reportSpam => 'Signaler comme spam';

  @override
  String get reportSpamDialog_success => 'Spam signalé';

  @override
  String get reportSpamDialog_error =>
      'Impossible de signaler le spam. Veuillez réessayer.';

  @override
  String get helpScreen_contactUs => 'Nous contacter';

  @override
  String get helpScreen_versionInfo => 'Informations sur la version';

  @override
  String get helpScreen_licenses => 'Licences';

  @override
  String get licensesScreen_title => 'Licences';

  @override
  String get contactUsScreen_title => 'Contact';

  @override
  String get contactUsScreen_subject => 'Objet du message';

  @override
  String get contactUsScreen_body => 'Corps du message';

  @override
  String get contactUsScreen_composeEmail => 'Composer un e-mail';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Quelque chose ne fonctionne pas';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'J\'ai une question';

  @override
  String get contactUsScreen_subject_requestFeature =>
      'Demander une fonctionnalité';

  @override
  String get contactUsScreen_subject_other => 'Autre';

  @override
  String get contactUsScreen_subject_empty => 'Veuillez sélectionner un objet';

  @override
  String get contactUsScreen_body_empty => 'Entrez votre message';

  @override
  String get contactUsScreen_body_tooShort =>
      'Veuillez fournir plus d\'informations';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'Impossible de lancer le client de messagerie';

  @override
  String get groupDetails_leaveChat => 'Quitter';

  @override
  String get groupDetails_deleteChat => 'Supprimer';

  @override
  String get groupDetails_addPeople => 'Ajouter des personnes';

  @override
  String get groupDetails_seeAll => 'Voir tout';

  @override
  String groupDetails_memberCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count membres',
      one: '$count membre',
    );
    return '$_temp0';
  }

  @override
  String get groupDetails_groupDescription => 'Groupe';

  @override
  String get groupMembersScreen_title => 'Membres du groupe';

  @override
  String get groupMembersScreen_searchHint => 'Chercher';

  @override
  String get groupCreationScreen_title => 'Ajouter des membres';

  @override
  String get groupCreationScreen_next => 'Suivant';

  @override
  String get groupCreationDetails_title => 'Détails du groupe';

  @override
  String get groupCreationDetails_groupNameHint =>
      'Nom du groupe (obligatoire)';

  @override
  String get groupCreationDetails_groupNameHintFocused => 'Nom du groupe';

  @override
  String get groupCreationDetails_groupNameHelper =>
      'Utilisez au moins un caractère';

  @override
  String get groupCreationDetails_create => 'Créer';

  @override
  String get groupCreationDetails_emptySelection => 'Aucun membre';

  @override
  String get addMembersScreen_done => 'Terminé';

  @override
  String get leaveChatDialog_title => 'Quitter le chat';

  @override
  String leaveChatDialog_content(Object chatName) {
    return 'Êtes-vous sûr de vouloir quitter $chatName ?';
  }

  @override
  String get leaveChatDialog_cancel => 'Annuler';

  @override
  String get leaveChatDialog_leave => 'Quitter';

  @override
  String get deleteChatDialog_title => 'Supprimer le chat ?';

  @override
  String get deleteChatDialog_content =>
      'Ce chat sera supprimé. Cette action est irréversible.';

  @override
  String get deleteChatDialog_delete => 'Supprimer';

  @override
  String get byteUnit_B => 'o';

  @override
  String get byteUnit_KB => 'Ko';

  @override
  String get byteUnit_MB => 'Mo';

  @override
  String get byteUnit_GB => 'Go';

  @override
  String get byteUnit_TB => 'To';

  @override
  String get byteUnit_PB => 'Po';

  @override
  String get byteUnit_EB => 'Eo';

  @override
  String get byteUnit_ZB => 'Zo';

  @override
  String get byteUnit_YB => 'Yo';

  @override
  String get deleteAccountScreen_title => 'Supprimer mon compte';

  @override
  String get deleteAccountScreen_explanatoryText =>
      'Cela supprimera votre compte Air et réinitialisera l\'application. Vous ne pourrez pas récupérer votre compte.';

  @override
  String get deleteAccountScreen_confirmationInputHint => 'Confirmation';

  @override
  String get deleteAccountScreen_confirmationInputLabel =>
      'Tapez \'delete\' pour confirmer';

  @override
  String get deleteAccountScreen_confirmButtonText => 'Supprimer le compte Air';

  @override
  String get deleteAccountScreen_deleteAccountError =>
      'Un problème est survenu de notre côté. Veuillez patienter un instant puis réessayer.';

  @override
  String get appOutdatedScreen_title => 'Mise à jour logicielle requise';

  @override
  String get appOutdatedScreen_message =>
      'Mettez à jour pour continuer à utiliser Air';

  @override
  String get appOutdatedScreen_description =>
      'Ouvrez TestFlight sur iOS ou Google Play sur Android, puis mettez Air à jour.';

  @override
  String get appOutdatedScreen_action => 'Mettre à jour';

  @override
  String get contactRequestDialog_title => 'Demande de contact';

  @override
  String get contactRequestDialog_avatarHint =>
      'Touchez pour afficher sa photo';

  @override
  String get contactRequestDialog_cancel => 'Plus tard';

  @override
  String get contactRequestDialog_confirm => 'Accepter';

  @override
  String get contactRequestDialog_error_fatal =>
      'Impossible d\'accepter la demande de contact';
}
