// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AppLocalizationsDe extends AppLocalizations {
  AppLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get languageName => 'Deutsch';

  @override
  String get userSettingsScreen_title => 'Profil und Einstellungen';

  @override
  String get userSettingsScreen_profileDescription =>
      'Dein Anzeigename und dein Profilbild sind für deine Air-Kontakte und Mitglieder deiner Gruppen sichtbar.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Teile Benutzernamen mit anderen, damit sie sich mit dir verbinden können. Nach der Verbindung sind Benutzernamen für andere nicht mehr sichtbar. Du kannst bis zu 5 Benutzernamen haben.';

  @override
  String get userSettingsScreen_interfaceScale => 'Oberflächenskalierung';

  @override
  String get userSettingsScreen_help => 'Hilfe';

  @override
  String get userSettingsScreen_deleteAccount => 'Air-Konto löschen';

  @override
  String get userSettingsScreen_sendWithEnter => 'Mit Eingabetaste senden';

  @override
  String get userSettingsScreen_sendWithEnterDescription =>
      'Wenn deaktiviert, wir die Nachricht beim Drücken der Entertaste nicht versendet.';

  @override
  String get userSettingsScreen_readReceipts => 'Lesebestätigungen';

  @override
  String get userSettingsScreen_readReceiptsDescription =>
      'Wenn deaktiviert, sehen andere nicht, wann du ihre Nachrichten gelesen hast, und du siehst nicht, wann sie deine gelesen haben.';

  @override
  String get userSettingsScreen_displayNameLabel => 'Anzeigename';

  @override
  String get userSettingsScreen_usernamesSection => 'Benutzernamen';

  @override
  String get userSettingsScreen_settingsSection => 'Einstellungen';

  @override
  String get userSettingsScreen_helpSection => 'Hilfe';

  @override
  String get userSettingsScreen_accountSection => 'Konto';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Benutzername';

  @override
  String get userSettingsScreen_inviteCodes => 'Invite codes';

  @override
  String get settingsScreen_copiedToClipboard => 'In Zwischenablage kopiert';

  @override
  String get removeUsernameDialog_title => 'Benutzername entfernen';

  @override
  String get removeUsernameDialog_content =>
      'Wenn du fortfährst, wird dein Benutzername entfernt und kann von jemand anderem beansprucht werden. Du wirst über ihn nicht mehr erreichbar sein.';

  @override
  String get removeUsernameDialog_cancel => 'Abbrechen';

  @override
  String get removeUsernameDialog_remove => 'Entfernen';

  @override
  String get addMembersScreen_addMembers => 'Mitglieder hinzufügen';

  @override
  String get addMembersScreen_error_noActiveChat =>
      'ein aktiver Chat ist erforderlich';

  @override
  String get contactDetailsScreen_chat => 'Chat';

  @override
  String get contactDetailsScreen_viewSafetyCode => 'Sicherheitscode anzeigen';

  @override
  String get safetyCodeScreen_title => 'Sicherheitscode';

  @override
  String get safetyCodeScreen_tapToCopy => 'Zum Kopieren tippen';

  @override
  String get safetyCodeScreen_copiedToClipboard => 'In Zwischenablage kopiert';

  @override
  String safetyCodeScreen_safetyCodeExplanation(Object displayName) {
    return 'Vergleiche den Sicherheitscode mit dem, den $displayName sieht. Wenn die Codes übereinstimmen, weißt du, dass ihr Ende-zu-Ende-verschlüsselte Nachrichten miteinander austauscht.';
  }

  @override
  String get chatDetailsScreen_unknownChat => 'Unbekannter Chat';

  @override
  String blockedChatFooter_message(Object displayName) {
    return 'Du erhältst keine Nachrichten von $displayName, solange du $displayName nicht entsperrst.';
  }

  @override
  String get inactiveChatFooter_message =>
      'Du bist kein Mitglied dieses Chats mehr.';

  @override
  String get chatScreen_emptyChat =>
      'Wähle einen Chat aus, um mit dem Nachrichten schreiben zu beginnen';

  @override
  String get removeUserDialog_title => 'Benutzer entfernen';

  @override
  String removeUserDialog_content(Object displayName) {
    return 'Bist du sicher, dass du $displayName aus der Gruppe entfernen möchtest?';
  }

  @override
  String get removeUserDialog_removeUser => 'Benutzer entfernen';

  @override
  String get removeUserButton_text => 'Entfernen';

  @override
  String get blockContactButton_text => 'Blockieren';

  @override
  String blockContactDialog_title(Object displayName) {
    return '$displayName blockieren?';
  }

  @override
  String blockContactDialog_content(Object displayName) {
    return 'Du erhältst keine Nachrichten von $displayName, und die Person sieht keine Aktualisierungen deines Profils. Sie sieht nicht, dass du sie blockiert hast. Du kannst sie jederzeit wieder freigeben.';
  }

  @override
  String get blockContactDialog_cancel => 'Abbrechen';

  @override
  String get blockContactDialog_block => 'Blockieren';

  @override
  String get unblockContactButton_text => 'Entsperren';

  @override
  String unblockContactDialog_title(Object displayName) {
    return '$displayName entsperren?';
  }

  @override
  String unblockContactDialog_content(Object displayName) {
    return 'Du kannst Nachrichten mit $displayName austauschen, und die Person sieht dein aktuelles Profil.';
  }

  @override
  String get unblockContactDialog_cancel => 'Abbrechen';

  @override
  String get unblockContactDialog_unblock => 'Entsperren';

  @override
  String get deleteContactButton_text => 'Löschen';

  @override
  String get deleteContactDialog_title => 'Air-Kontakt löschen';

  @override
  String deleteContactDialog_content(Object displayName) {
    return 'Möchtest du deinen Air-Kontakt $displayName wirklich löschen? Dadurch werden der Chat und sein Nachrichtenverlauf gelöscht.';
  }

  @override
  String get deleteContactDialog_cancel => 'Abbrechen';

  @override
  String get deleteContactDialog_delete => 'Löschen';

  @override
  String get addContactDialog_title => 'Air-Kontakt hinzufügen';

  @override
  String addContactDialog_content(Object displayName, Object groupTitle) {
    return '$displayName aus dem Gruppenchat \"$groupTitle\" ist kein Air-Kontakt. Sende eine Kontaktanfrage, um zu chatten.';
  }

  @override
  String get addContactDialog_cancel => 'Abbrechen';

  @override
  String get addContactDialog_confirm => 'Senden';

  @override
  String get changeGroupTitleDialog_title => 'Gruppentitel ändern';

  @override
  String get changeGroupTitleDialog_content =>
      'Wähle einen Titel für die Gruppe.';

  @override
  String get changeGroupTitleDialog_cancel => 'Abbrechen';

  @override
  String get changeGroupTitleDialog_confirm => 'Speichern';

  @override
  String get introScreen_signUp => 'Starten';

  @override
  String get introScreen_termsLinkText => 'Nutzungsbedingungen';

  @override
  String introScreen_termsText(Object termsOfUseLink) {
    return 'Mit deiner Registrierung stimmst du unseren $termsOfUseLink zu.';
  }

  @override
  String get invitationCodeScreen_header => 'Einladungscode eingeben';

  @override
  String get invitationCodeScreen_subheader =>
      'Air ist derzeit nur mit Einladung verfügbar. Gib deinen Code ein, um teilzunehmen. Wenn du keinen hast, bitte jemanden, der schon auf Air ist.';

  @override
  String get invitationCodeScreen_inputLabel => 'Einladungscode (erforderlich)';

  @override
  String get invitationCodeScreen_inputHint =>
      'Gib deinen Einladungscode ein...';

  @override
  String get invitationCodeScreen_error_invalidLength =>
      'Code muss 8 Zeichen lang sein';

  @override
  String get invitationCodeScreen_actionButton => 'Air beitreten';

  @override
  String invitationCodeScreen_error_internal(Object error) {
    return 'Einladungscode konnte nicht überprüft werden: $error';
  }

  @override
  String get invitationCodeScreen_error_missing => 'Einladungscode fehlt';

  @override
  String get invitationCodeScreen_error_invalid =>
      'Ungültiger Einladungscode. Prüfe den Code und versuche es erneut.';

  @override
  String get invitationCodesScreen_title => 'Invite codes';

  @override
  String get invitationCodesScreen_copyAll => 'Copy all';

  @override
  String get invitationCodesScreen_tapToGetCode => 'Tap to get code';

  @override
  String get invitationCodesScreen_removeUnusedCodes => 'Remove used codes';

  @override
  String get invitationCodesScreen_empty => 'No invitation codes available';

  @override
  String get invitationCodesScreen_infoText1 =>
      'Air is in a limited access phase. Everyone who wants to join needs an invite code.';

  @override
  String get invitationCodesScreen_infoText2 =>
      'Share these codes with your friends or anyone else who wants to join Air! New codes will be added periodically.';

  @override
  String get invitationCodesScreen_global_quota_exceeded =>
      'Wir haben im Moment keine Einladungenscode mehr, versuch es bitte später nochmal.';

  @override
  String get invitationCodesScreen_errorRequestingCode =>
      'Something went wrong. Try again.';

  @override
  String get invitationCodesScreen_copiedToClipboard => 'Copied to clipboard';

  @override
  String get signUpScreen_header => 'Erstelle dein Profil';

  @override
  String get signUpScreen_subheader =>
      'Dein Profil ist für Personen sichtbar, mit denen du dich verbindest, und für Mitglieder deiner Gruppen. Air benötigt einen Anzeigenamen, ein Bild ist optional.';

  @override
  String get signUpScreen_actionButton => 'Erstellen';

  @override
  String get signUpScreen_displayNameInputName => 'Anzeigename (erforderlich)';

  @override
  String get signUpScreen_displayNameInputHint => 'Name hinzufügen...';

  @override
  String get signUpScreen_serverLabel =>
      'Wähle den Server aus, auf dem du dein Konto erstellen möchtest.';

  @override
  String get signUpScreen_serverHint => 'DOMAIN-NAME';

  @override
  String get signUpScreen_error_invalidDomain => 'Domain ist ungültig';

  @override
  String get signUpScreen_error_emptyDisplayName =>
      'Füge einen Anzeigenamen mit mindestens einem Zeichen hinzu';

  @override
  String signUpScreen_error_register(Object error) {
    return 'Fehler beim Registrieren des Benutzers: $error';
  }

  @override
  String get usernameOnboarding_header => 'Füge einen Benutzernamen hinzu';

  @override
  String get usernameOnboarding_body =>
      'Über Benutzernamen kann man sich in Air mit anderen verbinden. Sie sind für andere nicht mehr sichtbar, sobald man verbunden ist.\n\nDu kannst Benutzernamen jederzeit in deinem Profil hinzufügen, ändern oder löschen.';

  @override
  String get usernameOnboarding_syntax =>
      'Verwende Buchstaben, Zahlen oder Bindestriche. Mindestens 5 Zeichen.';

  @override
  String get usernameOnboarding_addButton => 'Hinzufügen';

  @override
  String get usernameOnboarding_error =>
      'Bei uns ist ein Fehler aufgetreten. Warte einen Moment und versuche es dann erneut.';

  @override
  String get usernameOnboarding_next => 'Weiter';

  @override
  String get usernameOnboarding_usernameInputName => 'Benutzername (optional)';

  @override
  String get usernameOnboarding_usernameInputHint =>
      'Benutzernamen hinzufügen...';

  @override
  String get userHandleScreen_title => 'Benutzername hinzufügen';

  @override
  String get userHandleScreen_inputHint => 'Gib einen Benutzernamen ein...';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String get userHandleScreen_error_alreadyExists =>
      'Benutzername wird bereits verwendet';

  @override
  String get userHandleScreen_description =>
      'Wähle einen Benutzernamen, den andere verwenden können, um sich mit dir zu verbinden.\n\nVerwende Buchstaben, Zahlen oder Bindestriche. Mindestens 5 Zeichen.';

  @override
  String get userHandleScreen_cancel => 'Abbrechen';

  @override
  String get userHandleScreen_confirm => 'Hinzufügen';

  @override
  String get userHandleScreen_error_tooShort =>
      'Benutzername muss mindestens 5 Zeichen lang sein';

  @override
  String get userHandleScreen_error_tooLong =>
      'Benutzername darf höchstens 63 Zeichen lang sein';

  @override
  String get userHandleScreen_error_invalidCharacter =>
      'Benutzername darf nur Buchstaben, Zahlen oder Bindestriche enthalten';

  @override
  String get userHandleScreen_error_consecutiveDashes =>
      'Benutzername darf keine aufeinanderfolgenden Bindestriche enthalten';

  @override
  String get userHandleScreen_error_leadingDigit =>
      'Benutzername darf nicht mit einer Ziffer beginnen';

  @override
  String get editDisplayNameScreen_title => 'Anzeigenamen ändern';

  @override
  String get editDisplayNameScreen_description =>
      'Wähle einen Namen, den andere sehen werden, wenn du mit ihnen kommunizierst.';

  @override
  String get editDisplayNameScreen_cancel => 'Abbrechen';

  @override
  String get editDisplayNameScreen_save => 'Speichern';

  @override
  String systemMessage_userAddedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userAddedUser_infix => ' hat ';

  @override
  String systemMessage_userAddedUser_suffix(Object user2) {
    return '$user2 hinzugefügt';
  }

  @override
  String systemMessage_userRemovedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userRemovedUser_infix => ' hat ';

  @override
  String systemMessage_userRemovedUser_suffix(Object user2) {
    return '$user2 entfernt';
  }

  @override
  String systemMessage_userChangedTitle_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedTitle_infix_1 =>
      ' hat den Gruppennamen geändert von ';

  @override
  String systemMessage_userChangedTitle_infix_2(Object old_name) {
    return '$old_name';
  }

  @override
  String get systemMessage_userChangedTitle_infix_3 => ' zu ';

  @override
  String systemMessage_userChangedTitle_suffix(Object new_name) {
    return '$new_name';
  }

  @override
  String systemMessage_acceptedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return 'Du hast die Kontaktanfrage von $displayName akzeptiert, die über deinen Benutzernamen $username gestellt wurde.';
  }

  @override
  String systemMessage_acceptedDirectConnectionRequest(Object displayName) {
    return 'Du hast die Kontaktanfrage von $displayName akzeptiert, die über einen gemeinsamen Gruppenchat gestellt wurde.';
  }

  @override
  String systemMessage_receivedConnectionConfirmation(Object displayName) {
    return '$displayName hat deine Kontaktanfrage akzeptiert.';
  }

  @override
  String systemMessage_newHandleConnectionChat(Object username) {
    return 'Du hast eine Kontaktanfrage an den Benutzernamen $username gesendet. Die Person wird vielleicht nicht sofort über deine Anfrage benachrichtigt.';
  }

  @override
  String systemMessage_newDirectConnectionChat(Object displayName) {
    return 'Du hast eine Kontaktanfrage an $displayName gesendet. Die Person wird vielleicht nicht sofort über deine Anfrage benachrichtigt.';
  }

  @override
  String systemMessage_receivedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return '$displayName hat dir eine Kontaktanfrage über deinen Benutzernamen $username gesendet.';
  }

  @override
  String systemMessage_receivedDirectConnectionRequest(
    Object displayName,
    Object groupName,
  ) {
    return '$displayName hat dir eine Kontaktanfrage über den Gruppenchat $groupName gesendet.';
  }

  @override
  String systemMessage_userChangedPicture_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedPicture_infix =>
      ' hat das Gruppenbild geändert';

  @override
  String systemMessage_userCreatedGroup_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userCreatedGroup_suffix =>
      ' hat die Gruppe erstellt';

  @override
  String get timestamp_now => 'Jetzt';

  @override
  String timestamp_minutesAgo(int count) {
    return '${count}m';
  }

  @override
  String get timestamp_yesterday => 'Gestern';

  @override
  String get messageBubble_sending => 'Wird gesendet';

  @override
  String get messageBubble_failedToSend => 'Senden fehlgeschlagen';

  @override
  String get chatList_newContact => 'Neuer Kontakt';

  @override
  String get chatList_newGroup => 'Neue Gruppe';

  @override
  String get chatList_emptyMessage =>
      'Füge deinen ersten Air-Kontakt hinzu, um loszulegen.';

  @override
  String get chatList_draft => 'Entwurf';

  @override
  String get chatList_you => 'Du';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => 'Blockiert';

  @override
  String newChatDialog_error(Object chatName) {
    return 'Chat mit dem Namen $chatName konnte nicht hinzugefügt werden';
  }

  @override
  String newChatDialog_error_incompatibleClient(Object chatName) {
    return 'Gruppenchat mit dem Namen $chatName konnte nicht erstellt werden, da einer der Kontakte einen inkompatiblen Client hat.';
  }

  @override
  String get newConnectionDialog_newConnectionTitle => 'Air-Kontakt hinzufügen';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Gib den Benutzernamen der Person ein, der du eine Nachricht senden möchtest.';

  @override
  String get newConnectionDialog_inputLabel => 'Benutzername (erforderlich)';

  @override
  String get newConnectionDialog_usernamePlaceholder =>
      'Benutzernamen eingeben...';

  @override
  String newConnectionDialog_handleExists(Object username) {
    return '$username existiert. Tippe auf \"Senden\", um eine Kontaktanfrage zu schicken.';
  }

  @override
  String get newConnectionDialog_cancel => 'Abbrechen';

  @override
  String get newConnectionDialog_confirm1 => 'Prüfen';

  @override
  String get newConnectionDialog_confirm2 => 'Senden';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Kontaktanfrage an $username konnte nicht gesendet werden. Bitte versuche es erneut.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Benutzername $username existiert nicht';
  }

  @override
  String get newConnectionDialog_error_duplicateRequest =>
      'Du hast bereits eine ausstehende Kontaktanfrage an diesen Benutzernamen.';

  @override
  String get newConnectionDialog_error_ownHandle =>
      'Du kannst dir selbst keine Kontaktanfrage senden.';

  @override
  String composer_inputHint(Object chatTitle) {
    return 'Nachricht an $chatTitle';
  }

  @override
  String get composer_editMessage => 'Nachricht bearbeiten';

  @override
  String get composer_error_attachment =>
      'Anhang konnte nicht hochgeladen werden. Bitte versuche es erneut.';

  @override
  String composer_error_attachment_too_large(
    Object actualSize,
    Object maxSize,
  ) {
    return 'Der Anhang ist zu groß. Die maximale Größe beträgt $maxSize, die tatsächliche Größe beträgt $actualSize.';
  }

  @override
  String get composer_reply_deleted_message_placeholder =>
      'Ursprüngliche Nachricht gelöscht';

  @override
  String get composer_reply_noaccess_message_user => 'Unbekannter Nutzer';

  @override
  String get composer_reply_noaccess_message_placeholder =>
      'Du hast keinen Zugriff auf diese Nachricht.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat =
        intl.NumberFormat.decimalPatternDigits(
          locale: localeName,
          decimalDigits: 2,
        );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get attachment_tryAgain => 'Erneut versuchen';

  @override
  String get attachment_gallery => 'Galerie';

  @override
  String get attachment_camera => 'Kamera';

  @override
  String get attachment_file => 'Datei';

  @override
  String get textMessage_edited => 'bearbeitet';

  @override
  String get textMessage_hiddenPlaceholder =>
      'Blockierter Benutzer, tippe, um die Nachricht anzuzeigen';

  @override
  String get textMessage_deleted => 'Nachricht gelöscht';

  @override
  String get textMessage_deletedBySelf => 'Du hast diese Nachricht gelöscht.';

  @override
  String textMessage_deletedByOther(String senderName) {
    return '$senderName hat diese Nachricht gelöscht.';
  }

  @override
  String get linkConfirmation_title => 'Link öffnen?';

  @override
  String get linkConfirmation_description =>
      'Prüfe die URL, um sicherzugehen, dass du sie öffnen möchtest:';

  @override
  String get linkConfirmation_openLink => 'Öffnen';

  @override
  String get linkConfirmation_cancel => 'Abbrechen';

  @override
  String get messageContextMenu_reply => 'Antworten';

  @override
  String get messageContextMenu_copy => 'Kopieren';

  @override
  String get messageContextMenu_edit => 'Bearbeiten';

  @override
  String get messageContextMenu_delete => 'Löschen';

  @override
  String get messageContextMenu_save => 'Speichern';

  @override
  String get messageContextMenu_share => 'Teilen';

  @override
  String get messageContextMenu_saveError =>
      'Anhang konnte nicht gespeichert werden';

  @override
  String get messageContextMenu_saveConfirmation => 'Anhang gespeichert';

  @override
  String get deleteMessageDialog_title => 'Nachricht löschen?';

  @override
  String get deleteMessageDialog_description =>
      'Wähle, für wen diese Nachricht gelöscht werden soll. Sie wird von all deinen Geräten gelöscht.';

  @override
  String get deleteMessageDialog_forEveryone => 'Für alle löschen';

  @override
  String get deleteMessageDialog_forMe => 'Für mich löschen';

  @override
  String get deleteMessageForMeDialog_title => 'Nachricht löschen?';

  @override
  String get deleteMessageForMeDialog_description =>
      'Diese Nachricht wird von all deinen Geräten gelöscht.';

  @override
  String get deleteMessageForMeDialog_delete => 'Löschen';

  @override
  String get reportSpamButton_text => 'Spam melden';

  @override
  String get reportSpamDialog_title => 'Spam melden?';

  @override
  String get reportSpamDialog_content =>
      'Air wird benachrichtigt, dass diese Person möglicherweise Spam sendet. Air kann niemals den Inhalt von Chats einsehen.';

  @override
  String get reportSpamDialog_cancel => 'Abbrechen';

  @override
  String get reportSpamDialog_reportSpam => 'Spam melden';

  @override
  String get reportSpamDialog_success => 'Spam gemeldet';

  @override
  String get reportSpamDialog_error =>
      'Spam konnte nicht gemeldet werden. Bitte versuche es erneut.';

  @override
  String get helpScreen_contactUs => 'Kontakt';

  @override
  String get helpScreen_versionInfo => 'Versionsinformationen';

  @override
  String get helpScreen_licenses => 'Lizenzen';

  @override
  String get licensesScreen_title => 'Lizenzen';

  @override
  String get contactUsScreen_title => 'Kontakt';

  @override
  String get contactUsScreen_subject => 'Nachrichtenbetreff';

  @override
  String get contactUsScreen_body => 'Inhalt';

  @override
  String get contactUsScreen_composeEmail => 'E-Mail verfassen';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Etwas funktioniert nicht';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'Ich habe eine Frage';

  @override
  String get contactUsScreen_subject_requestFeature => 'Feature anfragen';

  @override
  String get contactUsScreen_subject_other => 'Andere';

  @override
  String get contactUsScreen_subject_empty => 'Bitte wähle einen Betreff aus';

  @override
  String get contactUsScreen_body_empty => 'Gib deine Nachricht ein';

  @override
  String get contactUsScreen_body_tooShort => 'Bitte gib mehr Informationen an';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'E-Mail-Client konnte nicht geöffnet werden';

  @override
  String get groupDetails_leaveChat => 'Verlassen';

  @override
  String get groupDetails_deleteChat => 'Löschen';

  @override
  String get groupDetails_addPeople => 'Hinzufügen';

  @override
  String get groupDetails_seeAll => 'Alle anzeigen';

  @override
  String groupDetails_memberCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count Mitglieder',
      one: '$count Mitglied',
    );
    return '$_temp0';
  }

  @override
  String get groupDetails_groupDescription => 'Gruppe';

  @override
  String get groupMembersScreen_title => 'Gruppenmitglieder';

  @override
  String get groupMembersScreen_searchHint => 'Suchen';

  @override
  String get groupCreationScreen_title => 'Mitglieder hinzufügen';

  @override
  String get groupCreationScreen_next => 'Weiter';

  @override
  String get groupCreationDetails_title => 'Gruppendetails';

  @override
  String get groupCreationDetails_groupNameHint => 'Gruppenname (erforderlich)';

  @override
  String get groupCreationDetails_groupNameHintFocused => 'Gruppenname';

  @override
  String get groupCreationDetails_groupNameHelper =>
      'Verwende mindestens ein Zeichen';

  @override
  String get groupCreationDetails_create => 'Erstellen';

  @override
  String get groupCreationDetails_emptySelection => 'Keine Mitglieder';

  @override
  String get addMembersScreen_done => 'Fertig';

  @override
  String get addMembersScreen_error_incompatibleClient =>
      'Mitglied(er) konnten nicht hinzugefügt werden, da einer der Kontakte einen inkompatiblen Client hat';

  @override
  String get leaveChatDialog_title => 'Chat verlassen';

  @override
  String leaveChatDialog_content(Object chatName) {
    return 'Möchtest du $chatName wirklich verlassen?';
  }

  @override
  String get leaveChatDialog_cancel => 'Abbrechen';

  @override
  String get leaveChatDialog_leave => 'Verlassen';

  @override
  String get deleteChatDialog_title => 'Chat löschen?';

  @override
  String get deleteChatDialog_content =>
      'Dieser Chat wird gelöscht. Dies kann nicht rückgängig gemacht werden.';

  @override
  String get deleteChatDialog_delete => 'Löschen';

  @override
  String get byteUnit_B => 'B';

  @override
  String get byteUnit_KB => 'KB';

  @override
  String get byteUnit_MB => 'MB';

  @override
  String get byteUnit_GB => 'GB';

  @override
  String get byteUnit_TB => 'TB';

  @override
  String get byteUnit_PB => 'PB';

  @override
  String get byteUnit_EB => 'EB';

  @override
  String get byteUnit_ZB => 'ZB';

  @override
  String get byteUnit_YB => 'YB';

  @override
  String get deleteAccountScreen_title => 'Mein Konto löschen';

  @override
  String get deleteAccountScreen_explanatoryText =>
      'Dadurch wird dein Air-Konto gelöscht und die App zurückgesetzt. Du kannst dein Konto nicht wiederherstellen.';

  @override
  String get deleteAccountScreen_confirmationInputHint => 'Bestätigung';

  @override
  String get deleteAccountScreen_confirmationInputLabel =>
      'Gib \'delete\' ein, um zu bestätigen';

  @override
  String get deleteAccountScreen_confirmButtonText => 'Air-Konto löschen';

  @override
  String get deleteAccountScreen_deleteAccountError =>
      'Bei uns ist ein Fehler aufgetreten. Warte einen Moment und versuche es dann erneut.';

  @override
  String get appOutdatedScreen_title => 'Software-Update erforderlich';

  @override
  String get appOutdatedScreen_message =>
      'Aktualisiere, um Air weiter zu nutzen';

  @override
  String get appOutdatedScreen_description =>
      'Öffne TestFlight auf iOS oder Google Play auf Android und aktualisiere Air.';

  @override
  String get appOutdatedScreen_action => 'Aktualisieren';

  @override
  String get contactRequestDialog_title => 'Kontaktanfrage';

  @override
  String get contactRequestDialog_avatarHint => 'Tippe, um das Bild anzuzeigen';

  @override
  String get contactRequestDialog_cancel => 'Später';

  @override
  String get contactRequestDialog_confirm => 'Annehmen';

  @override
  String get contactRequestDialog_error_fatal =>
      'Kontaktanfrage konnte nicht angenommen werden';

  @override
  String get contactRequestDialog_error_incompatibleClient =>
      'Kontaktanfrage konnte nicht angenommen werden. Aktualisiere Air auf die neueste Version und versuche es dann erneut.';

  @override
  String get errorBanner_ok => 'OK';

  @override
  String messageList_unreadMessages(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count ungelesene Nachrichten',
      one: '$count ungelesene Nachricht',
    );
    return '$_temp0';
  }
}
