// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for German (`de`).
class AppLocalizationsDe extends AppLocalizations {
  AppLocalizationsDe([String locale = 'de']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'Benutzereinstellungen';

  @override
  String get userSettingsScreen_profileDescription =>
      'Andere sehen dein Bild und deinen Namen, wenn du mit ihnen kommunizierst.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Teile Benutzernamen mit anderen, damit sie sich mit dir verbinden können. Nach der Verbindung sind Benutzernamen für andere nicht mehr sichtbar. Du kannst bis zu 5 Benutzernamen haben.';

  @override
  String get userSettingsScreen_interfaceScale => 'Oberflächenskalierung';

  @override
  String get userSettingsScreen_help => 'Hilfe';

  @override
  String get userSettingsScreen_deleteAccount => 'Air-Konto löschen';

  @override
  String get userSettingsScreen_sendWithEnter => 'Mit Eingabetaste senden';

  @override
  String get userSettingsScreen_sendWithEnterDescription =>
      'If disabled, pressing the Enter key won’t send a message.';

  @override
  String get userSettingsScreen_readReceipts => 'Lesebestätigungen';

  @override
  String get userSettingsScreen_readReceiptsDescription =>
      'Wenn deaktiviert, sehen andere nicht, wann du ihre Nachrichten gelesen hast, und du siehst nicht, wann sie deine gelesen haben.';

  @override
  String get userSettingsScreen_displayNameLabel => 'Display name';

  @override
  String get userSettingsScreen_usernamesSection => 'Usernames';

  @override
  String get userSettingsScreen_settingsSection => 'Settings';

  @override
  String get userSettingsScreen_helpSection => 'Help';

  @override
  String get userSettingsScreen_accountSection => 'Account';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Benutzername';

  @override
  String get removeUsernameDialog_title => 'Benutzername entfernen';

  @override
  String get removeUsernameDialog_content =>
      'Wenn du fortfährst, wird dein Benutzername entfernt und kann von jemand anderem beansprucht werden. Du wirst über ihn nicht mehr erreichbar sein.';

  @override
  String get removeUsernameDialog_cancel => 'Abbrechen';

  @override
  String get removeUsernameDialog_remove => 'Entfernen';

  @override
  String get addMembersScreen_addMembers => 'Mitglieder hinzufügen';

  @override
  String get addMembersScreen_error_noActiveChat =>
      'ein aktiver Chat ist erforderlich';

  @override
  String get chatDetailsScreen_unknownChat => 'Unbekannter Chat';

  @override
  String blockedChatFooter_message(Object displayName) {
    return 'Du erhältst keine Nachrichten von $displayName, solange du $displayName nicht entsperrst.';
  }

  @override
  String get chatScreen_emptyChat =>
      'Wähle einen Chat aus, um mit dem Nachrichten schreiben zu beginnen';

  @override
  String get removeUserDialog_title => 'Benutzer entfernen';

  @override
  String removeUserDialog_content(Object displayName) {
    return 'Bist du sicher, dass du diesen Benutzer aus der Gruppe entfernen möchtest?';
  }

  @override
  String get removeUserDialog_removeUser => 'Benutzer entfernen';

  @override
  String get removeUserButton_text => 'Benutzer entfernen';

  @override
  String get blockContactButton_text => 'Blockieren';

  @override
  String blockContactDialog_title(Object displayName) {
    return '$displayName blockieren?';
  }

  @override
  String blockContactDialog_content(Object displayName) {
    return 'Du erhältst keine Nachrichten von $displayName, und die Person sieht keine Aktualisierungen deines Profils. Sie sieht nicht, dass du sie blockiert hast. Du kannst sie jederzeit wieder freigeben.';
  }

  @override
  String get blockContactDialog_cancel => 'Abbrechen';

  @override
  String get blockContactDialog_block => 'Blockieren';

  @override
  String get unblockContactButton_text => 'Entsperren';

  @override
  String unblockContactDialog_title(Object displayName) {
    return '$displayName entsperren?';
  }

  @override
  String unblockContactDialog_content(Object displayName) {
    return 'Du kannst Nachrichten mit $displayName austauschen, und die Person sieht dein aktuelles Profil.';
  }

  @override
  String get unblockContactDialog_cancel => 'Abbrechen';

  @override
  String get unblockContactDialog_unblock => 'Entsperren';

  @override
  String get deleteContactButton_text => 'Air-Kontakt löschen';

  @override
  String get deleteContactDialog_title => 'Air-Kontakt löschen';

  @override
  String deleteContactDialog_content(Object displayName) {
    return 'Möchtest du deinen Air-Kontakt $displayName wirklich löschen? Dadurch werden der Chat und sein Nachrichtenverlauf gelöscht.';
  }

  @override
  String get deleteContactDialog_cancel => 'Abbrechen';

  @override
  String get deleteContactDialog_delete => 'Löschen';

  @override
  String get introScreen_signUp => 'Registrieren';

  @override
  String get introScreen_termsLinkText => 'Nutzungsbedingungen';

  @override
  String introScreen_termsText(Object termsOfUseLink) {
    return 'Mit deiner Registrierung stimmst du unseren $termsOfUseLink zu.';
  }

  @override
  String get signUpScreen_header => 'Erstelle dein Profil';

  @override
  String get signUpScreen_subheader =>
      'Dein Profil ist für Personen sichtbar, mit denen du dich verbindest, und für Mitglieder deiner Gruppen. Air benötigt einen Anzeigenamen, ein Bild ist optional.';

  @override
  String get usernameOnboarding_header => 'Füge einen Benutzernamen hinzu';

  @override
  String get usernameOnboarding_body =>
      'Über Benutzernamen kann man sich in Air mit anderen verbinden. Sie sind für andere nicht mehr sichtbar, sobald man verbunden ist.\n\nDu kannst Benutzernamen jederzeit in deinem Profil hinzufügen, ändern oder löschen.';

  @override
  String get usernameOnboarding_syntax =>
      'Verwende Buchstaben, Zahlen oder Bindestriche. Mindestens 5 Zeichen.';

  @override
  String get usernameOnboarding_addButton => 'Hinzufügen';

  @override
  String get usernameOnboarding_skip => 'Überspringen';

  @override
  String get signUpScreen_actionButton => 'Registrieren';

  @override
  String get signUpScreen_displayNameInputName => 'Anzeigename (erforderlich)';

  @override
  String get signUpScreen_displayNameInputHint => 'Name hinzufügen...';

  @override
  String get signUpScreen_serverLabel =>
      'Wähle den Server aus, auf dem du dein Konto erstellen möchtest.';

  @override
  String get signUpScreen_serverHint => 'DOMAIN-NAME';

  @override
  String get signUpScreen_error_invalidDomain => 'Domain ist ungültig';

  @override
  String get signUpScreen_error_emptyDisplayName =>
      'Füge einen Anzeigenamen mit mindestens einem Zeichen hinzu';

  @override
  String signUpScreen_error_register(Object error) {
    return 'Fehler beim Registrieren des Benutzers: $error';
  }

  @override
  String get userHandleScreen_title => 'Benutzername';

  @override
  String get userHandleScreen_inputHint => 'Benutzername';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String get userHandleScreen_error_alreadyExists =>
      'Benutzername wird bereits verwendet';

  @override
  String get userHandleScreen_description =>
      'Wähle einen Benutzernamen, den andere verwenden können, um sich mit dir zu verbinden.\n\nVerwende Buchstaben, Zahlen oder Bindestriche. Mindestens 5 Zeichen.';

  @override
  String get userHandleScreen_cancel => 'Cancel';

  @override
  String get userHandleScreen_confirm => 'Add';

  @override
  String get userHandleScreen_save => 'Speichern';

  @override
  String get editDisplayNameScreen_title => 'Anzeigename';

  @override
  String get editDisplayNameScreen_description =>
      'Wähle einen Namen, den andere sehen werden, wenn du mit ihnen kommunizierst.';

  @override
  String get editDisplayNameScreen_cancel => 'Cancel';

  @override
  String get editDisplayNameScreen_save => 'Speichern';

  @override
  String get systemMessage_userAddedUser_prefix => '';

  @override
  String get systemMessage_userAddedUser_infix => ' hat ';

  @override
  String get systemMessage_userAddedUser_suffix => ' hinzugefügt';

  @override
  String get systemMessage_userRemovedUser_prefix => '';

  @override
  String get systemMessage_userRemovedUser_infix => ' hat ';

  @override
  String get systemMessage_userRemovedUser_suffix => ' entfernt';

  @override
  String get timestamp_now => 'Jetzt';

  @override
  String get timestamp_yesterday => 'Gestern';

  @override
  String get chatList_newContact => 'Neuer Kontakt';

  @override
  String get chatList_newGroup => 'Neue Gruppe';

  @override
  String get chatList_emptyMessage =>
      'Erstelle eine neue Verbindung, um zu beginnen';

  @override
  String get chatList_draft => 'Entwurf';

  @override
  String get chatList_you => 'Du';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => 'Blockiert';

  @override
  String newChatDialog_error(Object chatName) {
    return 'Chat mit dem Namen $chatName konnte nicht hinzugefügt werden';
  }

  @override
  String get newConnectionDialog_newConnectionTitle => 'Neue Verbindung';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Gib den Benutzernamen des Benutzers ein, mit dem du dich verbinden möchtest';

  @override
  String get newConnectionDialog_usernamePlaceholder => 'Benutzername';

  @override
  String get newConnectionDialog_actionButton => 'Verbinden';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Benutzer mit Benutzername $username konnte nicht hinzugefügt werden. Bitte versuche es erneut.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Benutzername darf nicht leer sein';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Benutzername $username existiert nicht';
  }

  @override
  String composer_inputHint(Object chatTitle) {
    return 'Nachricht an $chatTitle';
  }

  @override
  String get composer_editMessage => 'Nachricht bearbeiten';

  @override
  String get composer_error_attachment =>
      'Anhang konnte nicht hochgeladen werden. Bitte versuche es erneut.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat = intl
        .NumberFormat.decimalPatternDigits(
      locale: localeName,
      decimalDigits: 2,
    );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get textMessage_edited => 'bearbeitet';

  @override
  String get textMessage_hiddenPlaceholder =>
      'Blockierter Benutzer, tippe, um die Nachricht anzuzeigen';

  @override
  String get textMessage_deleted => 'Nachricht gelöscht';

  @override
  String get messageContextMenu_copy => 'Kopieren';

  @override
  String get messageContextMenu_edit => 'Bearbeiten';

  @override
  String get reportSpamButton_text => 'Spam melden';

  @override
  String get reportSpamDialog_title => 'Spam melden?';

  @override
  String get reportSpamDialog_content =>
      'Air wird benachrichtigt, dass diese Person möglicherweise Spam sendet. Air kann niemals den Inhalt von Chats einsehen.';

  @override
  String get reportSpamDialog_cancel => 'Abbrechen';

  @override
  String get reportSpamDialog_reportSpam => 'Spam melden';

  @override
  String get reportSpamDialog_success => 'Spam gemeldet';

  @override
  String get reportSpamDialog_error =>
      'Spam konnte nicht gemeldet werden. Bitte versuche es erneut.';

  @override
  String get helpScreen_title => 'Hilfe';

  @override
  String get helpScreen_contactUs => 'Kontakt';

  @override
  String get helpScreen_versionInfo => 'Versionsinformationen';

  @override
  String get helpScreen_licenses => 'Lizenzen';

  @override
  String get licensesScreen_title => 'Lizenzen';

  @override
  String get contactUsScreen_title => 'Kontakt';

  @override
  String get contactUsScreen_subject => 'Nachrichtenbetreff';

  @override
  String get contactUsScreen_body => 'Inhalt';

  @override
  String get contactUsScreen_composeEmail => 'E-Mail verfassen';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Etwas funktioniert nicht';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'Ich habe eine Frage';

  @override
  String get contactUsScreen_subject_requestFeature => 'Feature anfragen';

  @override
  String get contactUsScreen_subject_other => 'Andere';

  @override
  String get contactUsScreen_subject_empty => 'Bitte wähle einen Betreff aus';

  @override
  String get contactUsScreen_body_empty => 'Gib deine Nachricht ein';

  @override
  String get contactUsScreen_body_tooShort => 'Bitte gib mehr Informationen an';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'E-Mail-Client konnte nicht geöffnet werden';

  @override
  String get groupDetails_leaveChat => 'Verlassen';

  @override
  String get groupDetails_deleteChat => 'Löschen';

  @override
  String get groupDetails_seeAll => 'Alle anzeigen';

  @override
  String groupDetails_memberCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count Mitglieder',
      one: '$count Mitgleid',
    );
    return '$_temp0';
  }

  @override
  String get groupMembersScreen_title => 'Gruppenmitglieder';

  @override
  String get groupMembersScreen_searchHint => 'Suchen';

  @override
  String get groupCreationScreen_title => 'Mitglieder hinzufügen';

  @override
  String get groupCreationScreen_next => 'Weiter';

  @override
  String get groupCreationScreen_skip => 'Überspringen';

  @override
  String get groupCreationDetails_title => 'Gruppendetails';

  @override
  String get groupCreationDetails_groupNameHint => 'Gruppenname (erforderlich)';

  @override
  String get groupCreationDetails_groupNameHintFocused => 'Gruppenname';

  @override
  String get groupCreationDetails_groupNameHelper =>
      'Mindestens ein Zeichen, bitte';

  @override
  String get groupCreationDetails_descriptionHint =>
      'Gruppenbeschreibung (optional)';

  @override
  String get groupCreationDetails_descriptionHintFocused =>
      'Gruppenbeschreibung';

  @override
  String get groupCreationDetails_create => 'Erstellen';

  @override
  String get groupCreationDetails_emptySelection => 'Keine Mitglieder';

  @override
  String get addMembersScreen_done => 'Fertig';

  @override
  String get leaveChatDialog_title => 'Chat verlassen';

  @override
  String leaveChatDialog_content(Object chatName) {
    return 'Möchtest du $chatName wirklich verlassen?';
  }

  @override
  String get leaveChatDialog_cancel => 'Abbrechen';

  @override
  String get leaveChatDialog_leave => 'Verlassen';

  @override
  String get deleteChatDialog_title => 'Chat löschen?';

  @override
  String get deleteChatDialog_content =>
      'Dieser Chat wird gelöscht. Dies kann nicht rückgängig gemacht werden.';

  @override
  String get deleteChatDialog_delete => 'Löschen';

  @override
  String get byteUnit_B => 'B';

  @override
  String get byteUnit_KB => 'KB';

  @override
  String get byteUnit_MB => 'MB';

  @override
  String get byteUnit_GB => 'GB';

  @override
  String get byteUnit_TB => 'TB';

  @override
  String get byteUnit_PB => 'PB';

  @override
  String get byteUnit_EB => 'EB';

  @override
  String get byteUnit_ZB => 'ZB';

  @override
  String get byteUnit_YB => 'YB';

  @override
  String get deleteAccountScreen_title => 'Mein Konto löschen';

  @override
  String get deleteAccountScreen_explanatoryText =>
      'Dadurch wird dein Air-Konto gelöscht und die App zurückgesetzt. Du kannst dein Konto nicht wiederherstellen.';

  @override
  String get deleteAccountScreen_confirmationInputHint => 'Bestätigung';

  @override
  String get deleteAccountScreen_confirmationInputLabel =>
      'Gib \'delete\' ein, um zu bestätigen';

  @override
  String get deleteAccountScreen_confirmButtonText => 'Air-Konto löschen';

  @override
  String get deleteAccountScreen_cancelButtonText => 'Abbrechen';

  @override
  String get deleteAccountScreen_deleteAccountError =>
      'Bei uns ist ein Fehler aufgetreten. Warte einen Moment und versuche es dann erneut.';
}
