// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for French (`fr`).
class AppLocalizationsFr extends AppLocalizations {
  AppLocalizationsFr([String locale = 'fr']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get userSettingsScreen_title => 'Paramètres utilisateur';

  @override
  String get userSettingsScreen_profileDescription =>
      'Les autres verront votre photo et votre nom lorsque vous communiquez avec eux.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Partagez des noms d\'utilisateur avec d\'autres pour qu\'ils puissent se connecter avec vous. Après la connexion, les noms d\'utilisateur ne sont plus visibles aux autres. Vous pouvez avoir jusqu\'à 5 noms d\'utilisateur.';

  @override
  String get userSettingsScreen_interfaceScale => 'Échelle de l\'interface';

  @override
  String get userSettingsScreen_help => 'Aide';

  @override
  String get userSettingsScreen_deleteAccount => 'Supprimer le compte Air';

  @override
  String get userSettingsScreen_sendWithEnter => 'Envoyer avec Entrée';

  @override
  String get userSettingsScreen_sendWithEnterDescription =>
      'If disabled, pressing the Enter key won’t send a message.';

  @override
  String get userSettingsScreen_readReceipts => 'Accusés de lecture';

  @override
  String get userSettingsScreen_readReceiptsDescription =>
      'Si vous les désactivez, les autres ne verront pas quand vous aurez lu leurs messages et vous ne verrez pas quand ils auront lu les vôtres.';

  @override
  String get userSettingsScreen_displayNameLabel => 'Display name';

  @override
  String get userSettingsScreen_usernamesSection => 'Usernames';

  @override
  String get userSettingsScreen_settingsSection => 'Settings';

  @override
  String get userSettingsScreen_helpSection => 'Help';

  @override
  String get userSettingsScreen_accountSection => 'Account';

  @override
  String get userSettingsScreen_userHandlePlaceholder => 'Nom d\'utilisateur';

  @override
  String get settingsScreen_copiedToClipboard => 'Copied to clipboard';

  @override
  String get removeUsernameDialog_title => 'Supprimer le nom d\'utilisateur';

  @override
  String get removeUsernameDialog_content =>
      'Si vous continuez, votre nom d\'utilisateur sera supprimé et pourra être réclamé par quelqu\'un d\'autre. Vous ne serez plus accessible par son intermédiaire.';

  @override
  String get removeUsernameDialog_cancel => 'Annuler';

  @override
  String get removeUsernameDialog_remove => 'Supprimer';

  @override
  String get addMembersScreen_addMembers => 'Ajouter des membres';

  @override
  String get addMembersScreen_error_noActiveChat =>
      'un chat actif est obligatoire';

  @override
  String get chatDetailsScreen_unknownChat => 'Chat inconnu';

  @override
  String blockedChatFooter_message(Object displayName) {
    return 'Vous ne recevrez pas de messages de $displayName tant que vous ne l\'aurez pas débloqué.';
  }

  @override
  String get inactiveChatFooter_message =>
      'Vous n\'êtes plus membre de ce chat.';

  @override
  String get chatScreen_emptyChat =>
      'Sélectionnez un chat pour commencer à envoyer des messages';

  @override
  String get removeUserDialog_title => 'Retirer l\'utilisateur';

  @override
  String removeUserDialog_content(Object displayName) {
    return 'Êtes-vous sûr de vouloir retirer cet utilisateur du groupe ?';
  }

  @override
  String get removeUserDialog_removeUser => 'Retirer l\'utilisateur';

  @override
  String get removeUserButton_text => 'Retirer l\'utilisateur';

  @override
  String get blockContactButton_text => 'Bloquer';

  @override
  String blockContactDialog_title(Object displayName) {
    return 'Bloquer $displayName ?';
  }

  @override
  String blockContactDialog_content(Object displayName) {
    return 'Vous ne recevrez plus de messages de $displayName et cette personne ne pourra pas voir les mises à jour de votre profil. Elle ne verra pas que vous l\'avez bloqué. Vous pourrez le débloquer à tout moment.';
  }

  @override
  String get blockContactDialog_cancel => 'Annuler';

  @override
  String get blockContactDialog_block => 'Bloquer';

  @override
  String get unblockContactButton_text => 'Débloquer';

  @override
  String unblockContactDialog_title(Object displayName) {
    return 'Débloquer $displayName ?';
  }

  @override
  String unblockContactDialog_content(Object displayName) {
    return 'Vous pourrez envoyer et recevoir des messages de $displayName et cette personne pourra voir votre profil actuel.';
  }

  @override
  String get unblockContactDialog_cancel => 'Annuler';

  @override
  String get unblockContactDialog_unblock => 'Débloquer';

  @override
  String get deleteContactButton_text => 'Supprimer';

  @override
  String get deleteContactDialog_title => 'Supprimer le contact Air';

  @override
  String deleteContactDialog_content(Object displayName) {
    return 'Voulez-vous vraiment supprimer votre contact Air $displayName ? Cela supprimera le chat et son historique.';
  }

  @override
  String get deleteContactDialog_cancel => 'Annuler';

  @override
  String get deleteContactDialog_delete => 'Supprimer';

  @override
  String get addContactDialog_title => 'Add Air contact';

  @override
  String addContactDialog_content(Object displayName, Object groupTitle) {
    return '$displayName from the group chat \"$groupTitle\" isn\'t an Air contact. To chat with them, send a contact request.';
  }

  @override
  String get addContactDialog_cancel => 'Cancel';

  @override
  String get addContactDialog_confirm => 'Send';

  @override
  String addContactDialog_error(Object username) {
    return 'Failed to send $username a contact request. Try again.';
  }

  @override
  String get changeGroupTitleDialog_title => 'Change group title';

  @override
  String get changeGroupTitleDialog_content => 'Choose a title for the group.';

  @override
  String get changeGroupTitleDialog_cancel => 'Cancel';

  @override
  String get changeGroupTitleDialog_confirm => 'Save';

  @override
  String get introScreen_signUp => 'S\'inscrire';

  @override
  String get introScreen_termsLinkText => 'Conditions d\'utilisation';

  @override
  String introScreen_termsText(Object termsOfUseLink) {
    return 'En vous inscrivant, vous acceptez nos $termsOfUseLink.';
  }

  @override
  String get signUpScreen_header => 'Créez votre profil';

  @override
  String get signUpScreen_subheader =>
      'Votre profil est visible pour les personnes avec lesquelles vous vous connectez et les membres de vos groupes. Air exige un nom d\'affichage, mais la photo est facultative.';

  @override
  String get usernameOnboarding_header => 'Ajoutez un nom d\'utilisateur';

  @override
  String get usernameOnboarding_body =>
      'On peut se connecter à d\'autres grace aux noms d\'utilisateur sur Air. Ils ne seront plus visibles pour les autres une fois la connexion établie.\n\nAjoutez, modifiez ou supprimez des noms d\'utilisateur à tout moment dans votre profil.';

  @override
  String get usernameOnboarding_syntax =>
      'Utilisez des lettres, des chiffres ou des tirets. Minimum 5 caractères.';

  @override
  String get usernameOnboarding_addButton => 'Ajouter';

  @override
  String get usernameOnboarding_skip => 'Ignorer';

  @override
  String get usernameOnboarding_userameInputName =>
      'Nom d\'utilisateur (facultatif)';

  @override
  String get usernameOnboarding_userameInputHint => 'Ajoutez un nom...';

  @override
  String get signUpScreen_actionButton => 'S\'inscrire';

  @override
  String get signUpScreen_displayNameInputName =>
      'Nom d\'affichage (obligatoire)';

  @override
  String get signUpScreen_displayNameInputHint => 'Ajoutez un nom...';

  @override
  String get signUpScreen_serverLabel =>
      'Choisissez le serveur sur lequel vous voulez créer votre compte.';

  @override
  String get signUpScreen_serverHint => 'NOM DE DOMAINE';

  @override
  String get signUpScreen_error_invalidDomain => 'Le domaine n\'est pas valide';

  @override
  String get signUpScreen_error_emptyDisplayName =>
      'Ajoutez un nom d\'affichage d\'au moins un caractère';

  @override
  String signUpScreen_error_register(Object error) {
    return 'Erreur lors de l\'enregistrement de l\'utilisateur : $error';
  }

  @override
  String get userHandleScreen_title => 'Nom d\'utilisateur';

  @override
  String get userHandleScreen_inputHint => 'Nom d\'utilisateur';

  @override
  String get userHandleScreen_error_emptyHandle =>
      'Le nom d\'utilisateur ne peut pas être vide';

  @override
  String get userHandleScreen_error_alreadyExists =>
      'Ce nom d\'utilisateur est déjà utilisé';

  @override
  String get userHandleScreen_description =>
      'Choisissez un nom d\'utilisateur que d\'autres peuvent utiliser pour se connecter avec vous.\n\nUtilisez des lettres, des chiffres ou des tirets. Minimum 5 caractères.';

  @override
  String get userHandleScreen_cancel => 'Cancel';

  @override
  String get userHandleScreen_confirm => 'Add';

  @override
  String get userHandleScreen_save => 'Enregistrer';

  @override
  String get editDisplayNameScreen_title => 'Nom d\'affichage';

  @override
  String get editDisplayNameScreen_description =>
      'Choisissez un nom que les autres verront lorsque vous communiquez avec eux.';

  @override
  String get editDisplayNameScreen_cancel => 'Cancel';

  @override
  String get editDisplayNameScreen_save => 'Enregistrer';

  @override
  String systemMessage_userAddedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userAddedUser_infix => ' a ajouté ';

  @override
  String systemMessage_userAddedUser_suffix(Object user2) {
    return '$user2';
  }

  @override
  String systemMessage_userRemovedUser_prefix(Object user1) {
    return '$user1';
  }

  @override
  String get systemMessage_userRemovedUser_infix => ' a retiré ';

  @override
  String systemMessage_userRemovedUser_suffix(Object user2) {
    return '$user2';
  }

  @override
  String systemMessage_userChangedTitle_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedTitle_infix_1 =>
      ' changed the group name from ';

  @override
  String systemMessage_userChangedTitle_infix_2(Object old_name) {
    return '$old_name';
  }

  @override
  String get systemMessage_userChangedTitle_infix_3 => ' to ';

  @override
  String systemMessage_userChangedTitle_suffix(Object new_name) {
    return '$new_name';
  }

  @override
  String systemMessage_acceptedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return 'You accepted $displayName\'s contact request made through your username $username.';
  }

  @override
  String systemMessage_acceptedDirectConnectionRequest(Object displayName) {
    return 'You accepted $displayName\'s contact request made through a mutual group chat.';
  }

  @override
  String systemMessage_receivedConnectionConfirmation(Object displayName) {
    return '$displayName accepted your contact request.';
  }

  @override
  String systemMessage_newHandleConnectionChat(Object username) {
    return 'You sent a contact request to username $username. They might not be immediately notified about your request.';
  }

  @override
  String systemMessage_newDirectConnectionChat(Object displayName) {
    return 'You sent a contact request to $displayName. They might not be immediately notified about your request.';
  }

  @override
  String systemMessage_receivedHandleConnectionRequest(
    Object displayName,
    Object username,
  ) {
    return '$displayName sent you a contact request through your username $username.';
  }

  @override
  String systemMessage_receivedDirectConnectionRequest(
    Object displayName,
    Object groupName,
  ) {
    return '$displayName sent you a contact request through the group chat $groupName.';
  }

  @override
  String systemMessage_userChangedPicture_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userChangedPicture_infix =>
      ' changed the group picture';

  @override
  String systemMessage_userCreatedGroup_prefix(Object user) {
    return '$user';
  }

  @override
  String get systemMessage_userCreatedGroup_suffix => ' created the group';

  @override
  String get timestamp_now => 'Maintenant';

  @override
  String get timestamp_yesterday => 'Hier';

  @override
  String get chatList_newContact => 'Nouveau contact';

  @override
  String get chatList_newGroup => 'Nouveau groupe';

  @override
  String get chatList_emptyMessage =>
      'Créez une nouvelle connexion pour commencer';

  @override
  String get chatList_draft => 'Brouillon';

  @override
  String get chatList_you => 'Vous';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => 'Bloqué';

  @override
  String newChatDialog_error(Object chatName) {
    return 'Impossible d\'ajouter un chat avec le nom $chatName';
  }

  @override
  String get newConnectionDialog_newConnectionTitle => 'Nouvelle connexion';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Saisissez le nom d\'utilisateur de la personne avec laquelle vous souhaitez vous connecter';

  @override
  String get newConnectionDialog_usernamePlaceholder => 'Nom d\'utilisateur';

  @override
  String get newConnectionDialog_actionButton => 'Se connecter';

  @override
  String newConnectionDialog_error(Object username) {
    return 'Impossible d\'ajouter l\'utilisateur avec le nom d\'utilisateur $username. Veuillez réessayer.';
  }

  @override
  String get newConnectionDialog_error_emptyHandle =>
      'Le nom d\'utilisateur ne peut pas être vide';

  @override
  String newConnectionDialog_error_handleNotFound(Object username) {
    return 'Le nom d\'utilisateur $username n\'existe pas';
  }

  @override
  String composer_inputHint(Object chatTitle) {
    return 'Message à $chatTitle';
  }

  @override
  String get composer_editMessage => 'Modifier le message';

  @override
  String get composer_error_attachment =>
      'Échec du téléchargement de la pièce jointe. Veuillez réessayer.';

  @override
  String attachmentSize(double size, Object byteUnit) {
    final intl.NumberFormat sizeNumberFormat =
        intl.NumberFormat.decimalPatternDigits(
          locale: localeName,
          decimalDigits: 2,
        );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get attachment_tryAgain => 'Try again';

  @override
  String get attachment_gallery => 'Gallery';

  @override
  String get attachment_camera => 'Camera';

  @override
  String get attachment_file => 'File';

  @override
  String get textMessage_edited => 'modifié';

  @override
  String get textMessage_hiddenPlaceholder =>
      'Utilisateur bloqué, appuyez pour afficher le message';

  @override
  String get textMessage_deleted => 'Message supprimé';

  @override
  String get messageContextMenu_copy => 'Copier';

  @override
  String get messageContextMenu_edit => 'Modifier';

  @override
  String get messageContextMenu_save => 'Save';

  @override
  String get messageContextMenu_share => 'Share';

  @override
  String get messageContextMenu_saveError => 'Failed to save attachment';

  @override
  String get messageContextMenu_saveConfirmation => 'Attachment saved';

  @override
  String get reportSpamButton_text => 'Signaler comme spam';

  @override
  String get reportSpamDialog_title => 'Signaler comme spam ?';

  @override
  String get reportSpamDialog_content =>
      'Air sera averti que cette personne peut envoyer des spams. Air ne peut jamais voir le contenu des chats.';

  @override
  String get reportSpamDialog_cancel => 'Annuler';

  @override
  String get reportSpamDialog_reportSpam => 'Signaler comme spam';

  @override
  String get reportSpamDialog_success => 'Spam signalé';

  @override
  String get reportSpamDialog_error =>
      'Impossible de signaler le spam. Veuillez réessayer.';

  @override
  String get helpScreen_title => 'Aide';

  @override
  String get helpScreen_contactUs => 'Nous contacter';

  @override
  String get helpScreen_versionInfo => 'Informations sur la version';

  @override
  String get helpScreen_licenses => 'Licences';

  @override
  String get licensesScreen_title => 'Licences';

  @override
  String get contactUsScreen_title => 'Contact';

  @override
  String get contactUsScreen_subject => 'Objet du message';

  @override
  String get contactUsScreen_body => 'Corps du message';

  @override
  String get contactUsScreen_composeEmail => 'Composer un e-mail';

  @override
  String get contactUsScreen_subject_somethingNotWorking =>
      'Quelque chose ne fonctionne pas';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'J\'ai une question';

  @override
  String get contactUsScreen_subject_requestFeature =>
      'Demander une fonctionnalité';

  @override
  String get contactUsScreen_subject_other => 'Autre';

  @override
  String get contactUsScreen_subject_empty => 'Veuillez sélectionner un objet';

  @override
  String get contactUsScreen_body_empty => 'Entrez votre message';

  @override
  String get contactUsScreen_body_tooShort =>
      'Veuillez fournir plus d\'informations';

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'Impossible de lancer le client de messagerie';

  @override
  String get groupDetails_leaveChat => 'Quitter';

  @override
  String get groupDetails_deleteChat => 'Supprimer';

  @override
  String get groupDetails_seeAll => 'Voir tout';

  @override
  String groupDetails_memberCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count membres',
      one: '$count membre',
    );
    return '$_temp0';
  }

  @override
  String get groupMembersScreen_title => 'Membres du groupe';

  @override
  String get groupMembersScreen_searchHint => 'Chercher';

  @override
  String get groupCreationScreen_title => 'Ajouter des membres';

  @override
  String get groupCreationScreen_next => 'Suivant';

  @override
  String get groupCreationScreen_skip => 'Ignorer';

  @override
  String get groupCreationDetails_title => 'Détails du groupe';

  @override
  String get groupCreationDetails_groupNameHint =>
      'Nom du groupe (obligatoire)';

  @override
  String get groupCreationDetails_groupNameHintFocused => 'Nom du groupe';

  @override
  String get groupCreationDetails_groupNameHelper =>
      'Au moins un caractère, s\'il vous plaît';

  @override
  String get groupCreationDetails_descriptionHint =>
      'Description du groupe (facultatif)';

  @override
  String get groupCreationDetails_descriptionHintFocused =>
      'Description du groupe';

  @override
  String get groupCreationDetails_create => 'Créer';

  @override
  String get groupCreationDetails_emptySelection => 'Aucun membre';

  @override
  String get addMembersScreen_done => 'Terminé';

  @override
  String get leaveChatDialog_title => 'Quitter le chat';

  @override
  String leaveChatDialog_content(Object chatName) {
    return 'Êtes-vous sûr de vouloir quitter $chatName ?';
  }

  @override
  String get leaveChatDialog_cancel => 'Annuler';

  @override
  String get leaveChatDialog_leave => 'Quitter';

  @override
  String get deleteChatDialog_title => 'Supprimer le chat ?';

  @override
  String get deleteChatDialog_content =>
      'Ce chat sera supprimé. Cette action est irréversible.';

  @override
  String get deleteChatDialog_delete => 'Supprimer';

  @override
  String get byteUnit_B => 'o';

  @override
  String get byteUnit_KB => 'Ko';

  @override
  String get byteUnit_MB => 'Mo';

  @override
  String get byteUnit_GB => 'Go';

  @override
  String get byteUnit_TB => 'To';

  @override
  String get byteUnit_PB => 'Po';

  @override
  String get byteUnit_EB => 'Eo';

  @override
  String get byteUnit_ZB => 'Zo';

  @override
  String get byteUnit_YB => 'Yo';

  @override
  String get deleteAccountScreen_title => 'Supprimer mon compte';

  @override
  String get deleteAccountScreen_explanatoryText =>
      'Cela supprimera votre compte Air et réinitialisera l\'application. Vous ne pourrez pas récupérer votre compte.';

  @override
  String get deleteAccountScreen_confirmationInputHint => 'Confirmation';

  @override
  String get deleteAccountScreen_confirmationInputLabel =>
      'Tapez \'delete\' pour confirmer';

  @override
  String get deleteAccountScreen_confirmButtonText => 'Supprimer le compte Air';

  @override
  String get deleteAccountScreen_cancelButtonText => 'Annuler';

  @override
  String get deleteAccountScreen_deleteAccountError =>
      'Un problème est survenu de notre côté. Veuillez patienter un instant puis réessayer.';
}
