// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:intl/intl.dart' as intl;

import 'app_localizations_de.dart';
import 'app_localizations_en.dart';
import 'app_localizations_fr.dart';

// ignore_for_file: type=lint

/// Callers can lookup localized strings with an instance of AppLocalizations
/// returned by `AppLocalizations.of(context)`.
///
/// Applications need to include `AppLocalizations.delegate()` in their app's
/// `localizationDelegates` list, and the locales they support in the app's
/// `supportedLocales` list. For example:
///
/// ```dart
/// import 'l10n/app_localizations.dart';
///
/// return MaterialApp(
///   localizationsDelegates: AppLocalizations.localizationsDelegates,
///   supportedLocales: AppLocalizations.supportedLocales,
///   home: MyApplicationHome(),
/// );
/// ```
///
/// ## Update pubspec.yaml
///
/// Please make sure to update your pubspec.yaml to include the following
/// packages:
///
/// ```yaml
/// dependencies:
///   # Internationalization support.
///   flutter_localizations:
///     sdk: flutter
///   intl: any # Use the pinned version from flutter_localizations
///
///   # Rest of dependencies
/// ```
///
/// ## iOS Applications
///
/// iOS applications define key application metadata, including supported
/// locales, in an Info.plist file that is built into the application bundle.
/// To configure the locales supported by your app, you’ll need to edit this
/// file.
///
/// First, open your project’s ios/Runner.xcworkspace Xcode workspace file.
/// Then, in the Project Navigator, open the Info.plist file under the Runner
/// project’s Runner folder.
///
/// Next, select the Information Property List item, select Add Item from the
/// Editor menu, then select Localizations from the pop-up menu.
///
/// Select and expand the newly-created Localizations item then, for each
/// locale your application supports, add a new item and select the locale
/// you wish to add from the pop-up menu in the Value field. This list should
/// be consistent with the languages listed in the AppLocalizations.supportedLocales
/// property.
abstract class AppLocalizations {
  AppLocalizations(String locale)
    : localeName = intl.Intl.canonicalizedLocale(locale.toString());

  final String localeName;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  /// A list of this localizations delegate along with the default localizations
  /// delegates.
  ///
  /// Returns a list of localizations delegates containing this delegate along with
  /// GlobalMaterialLocalizations.delegate, GlobalCupertinoLocalizations.delegate,
  /// and GlobalWidgetsLocalizations.delegate.
  ///
  /// Additional delegates can be added by appending to this list in
  /// MaterialApp. This list does not have to be used at all if a custom list
  /// of delegates is preferred or required.
  static const List<LocalizationsDelegate<dynamic>> localizationsDelegates =
      <LocalizationsDelegate<dynamic>>[
        delegate,
        GlobalMaterialLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ];

  /// A list of this localizations delegate's supported locales.
  static const List<Locale> supportedLocales = <Locale>[
    Locale('de'),
    Locale('en'),
    Locale('fr'),
  ];

  /// No description provided for @appTitle.
  ///
  /// In en, this message translates to:
  /// **'Air'**
  String get appTitle;

  /// No description provided for @userSettingsScreen_title.
  ///
  /// In en, this message translates to:
  /// **'User Settings'**
  String get userSettingsScreen_title;

  /// No description provided for @userSettingsScreen_idCopied.
  ///
  /// In en, this message translates to:
  /// **'User ID copied to clipboard'**
  String get userSettingsScreen_idCopied;

  /// No description provided for @userSettingsScreen_profileDescription.
  ///
  /// In en, this message translates to:
  /// **'Your Display Name and Profile Picture are visible to your Air Contacts and members of groups you\'re in.'**
  String get userSettingsScreen_profileDescription;

  /// No description provided for @userSettingsScreen_userNamesDescription.
  ///
  /// In en, this message translates to:
  /// **'Share Usernames with anyone you want to connect with. Usernames aren\'t visible to other users, even your Air Contacts. You can have up to 5 Usernames.'**
  String get userSettingsScreen_userNamesDescription;

  /// No description provided for @userSettingsScreen_interfaceScale.
  ///
  /// In en, this message translates to:
  /// **'Interface scale'**
  String get userSettingsScreen_interfaceScale;

  /// No description provided for @userSettingsScreen_help.
  ///
  /// In en, this message translates to:
  /// **'Help'**
  String get userSettingsScreen_help;

  /// No description provided for @userSettingsScreen_deleteAccount.
  ///
  /// In en, this message translates to:
  /// **'Delete Air Account'**
  String get userSettingsScreen_deleteAccount;

  /// No description provided for @userSettingsScreen_sendWithEnter.
  ///
  /// In en, this message translates to:
  /// **'Send with Enter'**
  String get userSettingsScreen_sendWithEnter;

  /// No description provided for @userSettingsScreen_readReceipts.
  ///
  /// In en, this message translates to:
  /// **'Read Receipts'**
  String get userSettingsScreen_readReceipts;

  /// No description provided for @userSettingsScreen_readReceiptsDescription.
  ///
  /// In en, this message translates to:
  /// **'If disabled, others won\'t be able to see when you\'ve read their messages and you won\'t be able to see when they\'ve read yours.'**
  String get userSettingsScreen_readReceiptsDescription;

  /// No description provided for @removeUsernameDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Remove Username'**
  String get removeUsernameDialog_title;

  /// No description provided for @removeUsernameDialog_content.
  ///
  /// In en, this message translates to:
  /// **'People won\'t be able to send you a Contact Request using this Username, and it may be claimed by someone else.'**
  String get removeUsernameDialog_content;

  /// No description provided for @removeUsernameDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get removeUsernameDialog_cancel;

  /// No description provided for @removeUsernameDialog_remove.
  ///
  /// In en, this message translates to:
  /// **'Remove'**
  String get removeUsernameDialog_remove;

  /// No description provided for @userSettingsScreen_noUserHandles.
  ///
  /// In en, this message translates to:
  /// **'no usernames yet'**
  String get userSettingsScreen_noUserHandles;

  /// No description provided for @userSettingsScreen_userHandlePlaceholder.
  ///
  /// In en, this message translates to:
  /// **'Username'**
  String get userSettingsScreen_userHandlePlaceholder;

  /// No description provided for @addMembersScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Add members'**
  String get addMembersScreen_title;

  /// No description provided for @addMembersScreen_addMembers.
  ///
  /// In en, this message translates to:
  /// **'Add members'**
  String get addMembersScreen_addMembers;

  /// No description provided for @addMembersScreen_error_noActiveChat.
  ///
  /// In en, this message translates to:
  /// **'an active chat is obligatory'**
  String get addMembersScreen_error_noActiveChat;

  /// No description provided for @chatDetailsScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Details'**
  String get chatDetailsScreen_title;

  /// No description provided for @chatDetailsScreen_unknownChat.
  ///
  /// In en, this message translates to:
  /// **'Unknown chat'**
  String get chatDetailsScreen_unknownChat;

  /// No description provided for @blockedChatFooter_message.
  ///
  /// In en, this message translates to:
  /// **'You won’t receive messages from {displayName} unless you unblock them.'**
  String blockedChatFooter_message(Object displayName);

  /// No description provided for @chatScreen_emptyChat.
  ///
  /// In en, this message translates to:
  /// **'Select a chat to start messaging'**
  String get chatScreen_emptyChat;

  /// No description provided for @removeUserDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Remove user'**
  String get removeUserDialog_title;

  /// No description provided for @removeUserDialog_content.
  ///
  /// In en, this message translates to:
  /// **'Are you sure you want to remove {displayName} from the group?'**
  String removeUserDialog_content(Object displayName);

  /// No description provided for @removeUserDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get removeUserDialog_cancel;

  /// No description provided for @removeUserDialog_removeUser.
  ///
  /// In en, this message translates to:
  /// **'Remove user'**
  String get removeUserDialog_removeUser;

  /// No description provided for @removeUserButton_text.
  ///
  /// In en, this message translates to:
  /// **'Remove'**
  String get removeUserButton_text;

  /// No description provided for @blockContactButton_text.
  ///
  /// In en, this message translates to:
  /// **'Block'**
  String get blockContactButton_text;

  /// No description provided for @blockContactDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Block {displayName}?'**
  String blockContactDialog_title(Object displayName);

  /// No description provided for @blockContactDialog_content.
  ///
  /// In en, this message translates to:
  /// **'You won’t receive messages from {displayName} and they won’t be able to view any updates to your profile. They won’t be able to see that you blocked them. You can unblock them anytime.'**
  String blockContactDialog_content(Object displayName);

  /// No description provided for @blockContactDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get blockContactDialog_cancel;

  /// No description provided for @blockContactDialog_block.
  ///
  /// In en, this message translates to:
  /// **'Block'**
  String get blockContactDialog_block;

  /// No description provided for @unblockContactButton_text.
  ///
  /// In en, this message translates to:
  /// **'Unblock'**
  String get unblockContactButton_text;

  /// No description provided for @unblockContactDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Unblock {displayName}?'**
  String unblockContactDialog_title(Object displayName);

  /// No description provided for @unblockContactDialog_content.
  ///
  /// In en, this message translates to:
  /// **'You’ll be able to send and receive messages from {displayName} and they’ll be able to view your current profile.'**
  String unblockContactDialog_content(Object displayName);

  /// No description provided for @unblockContactDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get unblockContactDialog_cancel;

  /// No description provided for @unblockContactDialog_unblock.
  ///
  /// In en, this message translates to:
  /// **'Unblock'**
  String get unblockContactDialog_unblock;

  /// No description provided for @deleteContactButton_text.
  ///
  /// In en, this message translates to:
  /// **'Delete Air Contact'**
  String get deleteContactButton_text;

  /// No description provided for @deleteContactDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Delete Air Contact'**
  String get deleteContactDialog_title;

  /// No description provided for @deleteContactDialog_content.
  ///
  /// In en, this message translates to:
  /// **'Are you sure you want to delete your Air Contact {displayName}? If you do, the chat and its message history will be deleted.'**
  String deleteContactDialog_content(Object displayName);

  /// No description provided for @deleteContactDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get deleteContactDialog_cancel;

  /// No description provided for @deleteContactDialog_delete.
  ///
  /// In en, this message translates to:
  /// **'Delete'**
  String get deleteContactDialog_delete;

  /// No description provided for @introScreen_signUp.
  ///
  /// In en, this message translates to:
  /// **'Start'**
  String get introScreen_signUp;

  /// No description provided for @signUpScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Create an Air Account'**
  String get signUpScreen_title;

  /// No description provided for @signUpScreen_actionButton.
  ///
  /// In en, this message translates to:
  /// **'Sign Up'**
  String get signUpScreen_actionButton;

  /// No description provided for @signUpScreen_displayNameLabel.
  ///
  /// In en, this message translates to:
  /// **'Add a Profile Picture and Display Name.'**
  String get signUpScreen_displayNameLabel;

  /// No description provided for @signUpScreen_displayNameHint.
  ///
  /// In en, this message translates to:
  /// **'Display Name'**
  String get signUpScreen_displayNameHint;

  /// No description provided for @signUpScreen_serverLabel.
  ///
  /// In en, this message translates to:
  /// **'Choose a server where you want to create your account.'**
  String get signUpScreen_serverLabel;

  /// No description provided for @signUpScreen_serverHint.
  ///
  /// In en, this message translates to:
  /// **'DOMAIN NAME'**
  String get signUpScreen_serverHint;

  /// No description provided for @signUpScreen_error_invalidDomain.
  ///
  /// In en, this message translates to:
  /// **'Domain is invalid'**
  String get signUpScreen_error_invalidDomain;

  /// No description provided for @signUpScreen_error_emptyDisplayName.
  ///
  /// In en, this message translates to:
  /// **'Add a Display Name of at least one character'**
  String get signUpScreen_error_emptyDisplayName;

  /// No description provided for @signUpScreen_error_register.
  ///
  /// In en, this message translates to:
  /// **'Error when registering user: {error}'**
  String signUpScreen_error_register(Object error);

  /// No description provided for @userHandleScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Username'**
  String get userHandleScreen_title;

  /// No description provided for @userHandleScreen_inputHint.
  ///
  /// In en, this message translates to:
  /// **'Username'**
  String get userHandleScreen_inputHint;

  /// No description provided for @userHandleScreen_error_emptyHandle.
  ///
  /// In en, this message translates to:
  /// **'Username cannot be empty'**
  String get userHandleScreen_error_emptyHandle;

  /// No description provided for @userHandleScreen_error_alreadyExists.
  ///
  /// In en, this message translates to:
  /// **'Username is already in use'**
  String get userHandleScreen_error_alreadyExists;

  /// No description provided for @userHandleScreen_description.
  ///
  /// In en, this message translates to:
  /// **'Choose a username that others can use to connect with you.\n\nUse letters, numbers, or underscores. Minimum 5 characters.'**
  String get userHandleScreen_description;

  /// No description provided for @userHandleScreen_save.
  ///
  /// In en, this message translates to:
  /// **'Save'**
  String get userHandleScreen_save;

  /// No description provided for @editDisplayNameScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Display Name'**
  String get editDisplayNameScreen_title;

  /// No description provided for @editDisplayNameScreen_hintText.
  ///
  /// In en, this message translates to:
  /// **'Display Name'**
  String get editDisplayNameScreen_hintText;

  /// No description provided for @editDisplayNameScreen_description.
  ///
  /// In en, this message translates to:
  /// **'Choose a name that others will see when you communicate with them.'**
  String get editDisplayNameScreen_description;

  /// No description provided for @editDisplayNameScreen_save.
  ///
  /// In en, this message translates to:
  /// **'Save'**
  String get editDisplayNameScreen_save;

  /// No description provided for @systemMessage_userAddedUser_prefix.
  ///
  /// In en, this message translates to:
  /// **''**
  String get systemMessage_userAddedUser_prefix;

  /// No description provided for @systemMessage_userAddedUser_infix.
  ///
  /// In en, this message translates to:
  /// **' added '**
  String get systemMessage_userAddedUser_infix;

  /// No description provided for @systemMessage_userAddedUser_suffix.
  ///
  /// In en, this message translates to:
  /// **''**
  String get systemMessage_userAddedUser_suffix;

  /// No description provided for @systemMessage_userRemovedUser_prefix.
  ///
  /// In en, this message translates to:
  /// **''**
  String get systemMessage_userRemovedUser_prefix;

  /// No description provided for @systemMessage_userRemovedUser_infix.
  ///
  /// In en, this message translates to:
  /// **' removed '**
  String get systemMessage_userRemovedUser_infix;

  /// No description provided for @systemMessage_userRemovedUser_suffix.
  ///
  /// In en, this message translates to:
  /// **''**
  String get systemMessage_userRemovedUser_suffix;

  /// No description provided for @timestamp_now.
  ///
  /// In en, this message translates to:
  /// **'Now'**
  String get timestamp_now;

  /// No description provided for @timestamp_yesterday.
  ///
  /// In en, this message translates to:
  /// **'Yesterday'**
  String get timestamp_yesterday;

  /// No description provided for @chatList_newContact.
  ///
  /// In en, this message translates to:
  /// **'New Air Contact'**
  String get chatList_newContact;

  /// No description provided for @chatList_newGroup.
  ///
  /// In en, this message translates to:
  /// **'New Group Chat'**
  String get chatList_newGroup;

  /// No description provided for @chatList_emptyMessage.
  ///
  /// In en, this message translates to:
  /// **'Add your first Air Contact to get started'**
  String get chatList_emptyMessage;

  /// No description provided for @chatList_draft.
  ///
  /// In en, this message translates to:
  /// **'Draft'**
  String get chatList_draft;

  /// No description provided for @chatList_you.
  ///
  /// In en, this message translates to:
  /// **'You'**
  String get chatList_you;

  /// No description provided for @chatList_imageEmoji.
  ///
  /// In en, this message translates to:
  /// **'🖼️'**
  String get chatList_imageEmoji;

  /// No description provided for @chatList_fileEmoji.
  ///
  /// In en, this message translates to:
  /// **'📎'**
  String get chatList_fileEmoji;

  /// No description provided for @chatList_blocked.
  ///
  /// In en, this message translates to:
  /// **'Blocked'**
  String get chatList_blocked;

  /// No description provided for @newChatDialog_newChatTitle.
  ///
  /// In en, this message translates to:
  /// **'New Group Chat'**
  String get newChatDialog_newChatTitle;

  /// No description provided for @newChatDialog_newChatDescription.
  ///
  /// In en, this message translates to:
  /// **'Choose a name for the Group Chat'**
  String get newChatDialog_newChatDescription;

  /// No description provided for @newChatDialog_chatNamePlaceholder.
  ///
  /// In en, this message translates to:
  /// **'Chat name'**
  String get newChatDialog_chatNamePlaceholder;

  /// No description provided for @newChatDialog_actionButton.
  ///
  /// In en, this message translates to:
  /// **'Create Group'**
  String get newChatDialog_actionButton;

  /// No description provided for @newChatDialog_error.
  ///
  /// In en, this message translates to:
  /// **'Failed to create new Group Chat with name {chatName}'**
  String newChatDialog_error(Object chatName);

  /// No description provided for @newChatDialog_error_emptyGroupName.
  ///
  /// In en, this message translates to:
  /// **'Add a name for the Group Chat'**
  String get newChatDialog_error_emptyGroupName;

  /// No description provided for @newConnectionDialog_newConnectionTitle.
  ///
  /// In en, this message translates to:
  /// **'New Air Contact'**
  String get newConnectionDialog_newConnectionTitle;

  /// No description provided for @newConnectionDialog_newConnectionDescription.
  ///
  /// In en, this message translates to:
  /// **'Type the Username of the person you want to connect to'**
  String get newConnectionDialog_newConnectionDescription;

  /// No description provided for @newConnectionDialog_usernamePlaceholder.
  ///
  /// In en, this message translates to:
  /// **'Username'**
  String get newConnectionDialog_usernamePlaceholder;

  /// No description provided for @newConnectionDialog_actionButton.
  ///
  /// In en, this message translates to:
  /// **'Connect'**
  String get newConnectionDialog_actionButton;

  /// No description provided for @newConnectionDialog_error.
  ///
  /// In en, this message translates to:
  /// **'Failed to send {username} a Contact Request. Try again.'**
  String newConnectionDialog_error(Object username);

  /// No description provided for @newConnectionDialog_error_emptyHandle.
  ///
  /// In en, this message translates to:
  /// **'Type the Username'**
  String get newConnectionDialog_error_emptyHandle;

  /// No description provided for @newConnectionDialog_error_handleNotFound.
  ///
  /// In en, this message translates to:
  /// **'Username {username} doesn\'t exist'**
  String newConnectionDialog_error_handleNotFound(Object username);

  /// No description provided for @composer_inputHint.
  ///
  /// In en, this message translates to:
  /// **'Message {chatTitle}'**
  String composer_inputHint(Object chatTitle);

  /// No description provided for @composer_editMessage.
  ///
  /// In en, this message translates to:
  /// **'Edit message'**
  String get composer_editMessage;

  /// No description provided for @composer_error_attachment.
  ///
  /// In en, this message translates to:
  /// **'Failed to upload attachment. Try again.'**
  String get composer_error_attachment;

  /// No description provided for @attachmentSize.
  ///
  /// In en, this message translates to:
  /// **'{size} {byteUnit}'**
  String attachmentSize(double size, Object byteUnit);

  /// No description provided for @textMessage_edited.
  ///
  /// In en, this message translates to:
  /// **'edited'**
  String get textMessage_edited;

  /// No description provided for @textMessage_hiddenPlaceholder.
  ///
  /// In en, this message translates to:
  /// **'Blocked user, tap to reveal message'**
  String get textMessage_hiddenPlaceholder;

  /// No description provided for @textMessage_deleted.
  ///
  /// In en, this message translates to:
  /// **'Deleted message'**
  String get textMessage_deleted;

  /// No description provided for @messageContextMenu_copy.
  ///
  /// In en, this message translates to:
  /// **'Copy message'**
  String get messageContextMenu_copy;

  /// No description provided for @messageContextMenu_edit.
  ///
  /// In en, this message translates to:
  /// **'Edit message'**
  String get messageContextMenu_edit;

  /// No description provided for @reportSpamButton_text.
  ///
  /// In en, this message translates to:
  /// **'Report spam'**
  String get reportSpamButton_text;

  /// No description provided for @reportSpamDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Report spam?'**
  String get reportSpamDialog_title;

  /// No description provided for @reportSpamDialog_content.
  ///
  /// In en, this message translates to:
  /// **'Air will be notified that this person may be sending spam. Air is never able to see the contents of any chats.'**
  String get reportSpamDialog_content;

  /// No description provided for @reportSpamDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get reportSpamDialog_cancel;

  /// No description provided for @reportSpamDialog_reportSpam.
  ///
  /// In en, this message translates to:
  /// **'Report spam'**
  String get reportSpamDialog_reportSpam;

  /// No description provided for @reportSpamDialog_success.
  ///
  /// In en, this message translates to:
  /// **'Spam reported'**
  String get reportSpamDialog_success;

  /// No description provided for @reportSpamDialog_error.
  ///
  /// In en, this message translates to:
  /// **'Failed to report spam. Try again.'**
  String get reportSpamDialog_error;

  /// No description provided for @helpScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Help'**
  String get helpScreen_title;

  /// No description provided for @helpScreen_contactUs.
  ///
  /// In en, this message translates to:
  /// **'Contact us'**
  String get helpScreen_contactUs;

  /// No description provided for @helpScreen_versionInfo.
  ///
  /// In en, this message translates to:
  /// **'Version info'**
  String get helpScreen_versionInfo;

  /// No description provided for @helpScreen_licenses.
  ///
  /// In en, this message translates to:
  /// **'Licenses'**
  String get helpScreen_licenses;

  /// No description provided for @licensesScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Licenses'**
  String get licensesScreen_title;

  /// No description provided for @contactUsScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Contact'**
  String get contactUsScreen_title;

  /// No description provided for @contactUsScreen_subject.
  ///
  /// In en, this message translates to:
  /// **'Message subject'**
  String get contactUsScreen_subject;

  /// No description provided for @contactUsScreen_body.
  ///
  /// In en, this message translates to:
  /// **'Body'**
  String get contactUsScreen_body;

  /// No description provided for @contactUsScreen_composeEmail.
  ///
  /// In en, this message translates to:
  /// **'Compose email'**
  String get contactUsScreen_composeEmail;

  /// No description provided for @contactUsScreen_subject_somethingNotWorking.
  ///
  /// In en, this message translates to:
  /// **'Something\'s not working'**
  String get contactUsScreen_subject_somethingNotWorking;

  /// No description provided for @contactUsScreen_subject_iHaveAQuestion.
  ///
  /// In en, this message translates to:
  /// **'I have a question'**
  String get contactUsScreen_subject_iHaveAQuestion;

  /// No description provided for @contactUsScreen_subject_requestFeature.
  ///
  /// In en, this message translates to:
  /// **'Request a feature'**
  String get contactUsScreen_subject_requestFeature;

  /// No description provided for @contactUsScreen_subject_other.
  ///
  /// In en, this message translates to:
  /// **'Other'**
  String get contactUsScreen_subject_other;

  /// No description provided for @contactUsScreen_subject_empty.
  ///
  /// In en, this message translates to:
  /// **'Select a subject'**
  String get contactUsScreen_subject_empty;

  /// No description provided for @contactUsScreen_body_empty.
  ///
  /// In en, this message translates to:
  /// **'Enter your message'**
  String get contactUsScreen_body_empty;

  /// No description provided for @contactUsScreen_body_tooShort.
  ///
  /// In en, this message translates to:
  /// **'Provide more information'**
  String get contactUsScreen_body_tooShort;

  /// No description provided for @contactUsScreen_errorLaunchingEmail.
  ///
  /// In en, this message translates to:
  /// **'Couldn\'t launch email client'**
  String get contactUsScreen_errorLaunchingEmail;

  /// No description provided for @groupDetails_members.
  ///
  /// In en, this message translates to:
  /// **'Members'**
  String get groupDetails_members;

  /// No description provided for @groupDetails_addMembers.
  ///
  /// In en, this message translates to:
  /// **'Add members'**
  String get groupDetails_addMembers;

  /// No description provided for @groupDetails_leaveChat.
  ///
  /// In en, this message translates to:
  /// **'Leave'**
  String get groupDetails_leaveChat;

  /// No description provided for @groupDetails_deleteChat.
  ///
  /// In en, this message translates to:
  /// **'Delete'**
  String get groupDetails_deleteChat;

  /// No description provided for @groupDetails_seeAll.
  ///
  /// In en, this message translates to:
  /// **'See all'**
  String get groupDetails_seeAll;

  /// No description provided for @groupDetails_memberCount.
  ///
  /// In en, this message translates to:
  /// **'{count, plural, one {{count} member} other {{count} members}}'**
  String groupDetails_memberCount(int count);

  /// No description provided for @groupMembersScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Group members'**
  String get groupMembersScreen_title;

  /// No description provided for @groupMembersScreen_searchHint.
  ///
  /// In en, this message translates to:
  /// **'Search'**
  String get groupMembersScreen_searchHint;

  /// No description provided for @groupCreationScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Add members'**
  String get groupCreationScreen_title;

  /// No description provided for @groupCreationScreen_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get groupCreationScreen_cancel;

  /// No description provided for @groupCreationScreen_next.
  ///
  /// In en, this message translates to:
  /// **'Next'**
  String get groupCreationScreen_next;

  /// No description provided for @groupCreationScreen_skip.
  ///
  /// In en, this message translates to:
  /// **'Skip'**
  String get groupCreationScreen_skip;

  /// No description provided for @groupCreationDetails_title.
  ///
  /// In en, this message translates to:
  /// **'Group details'**
  String get groupCreationDetails_title;

  /// No description provided for @groupCreationDetails_groupNameHint.
  ///
  /// In en, this message translates to:
  /// **'Group name (required)'**
  String get groupCreationDetails_groupNameHint;

  /// No description provided for @groupCreationDetails_groupNameHintFocused.
  ///
  /// In en, this message translates to:
  /// **'Group name'**
  String get groupCreationDetails_groupNameHintFocused;

  /// No description provided for @groupCreationDetails_groupNameHelper.
  ///
  /// In en, this message translates to:
  /// **'At least one character, please'**
  String get groupCreationDetails_groupNameHelper;

  /// No description provided for @groupCreationDetails_descriptionHint.
  ///
  /// In en, this message translates to:
  /// **'Group description (optional)'**
  String get groupCreationDetails_descriptionHint;

  /// No description provided for @groupCreationDetails_descriptionHintFocused.
  ///
  /// In en, this message translates to:
  /// **'Group description'**
  String get groupCreationDetails_descriptionHintFocused;

  /// No description provided for @groupCreationDetails_create.
  ///
  /// In en, this message translates to:
  /// **'Create'**
  String get groupCreationDetails_create;

  /// No description provided for @groupCreationDetails_emptySelection.
  ///
  /// In en, this message translates to:
  /// **'No members'**
  String get groupCreationDetails_emptySelection;

  /// No description provided for @addMembersScreen_done.
  ///
  /// In en, this message translates to:
  /// **'Done'**
  String get addMembersScreen_done;

  /// No description provided for @leaveChatDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Leave Group'**
  String get leaveChatDialog_title;

  /// No description provided for @leaveChatDialog_content.
  ///
  /// In en, this message translates to:
  /// **'Are you sure you want to leave {chatName}?'**
  String leaveChatDialog_content(Object chatName);

  /// No description provided for @leaveChatDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get leaveChatDialog_cancel;

  /// No description provided for @leaveChatDialog_leave.
  ///
  /// In en, this message translates to:
  /// **'Leave'**
  String get leaveChatDialog_leave;

  /// No description provided for @deleteChatDialog_title.
  ///
  /// In en, this message translates to:
  /// **'Delete Chat?'**
  String get deleteChatDialog_title;

  /// No description provided for @deleteChatDialog_content.
  ///
  /// In en, this message translates to:
  /// **'This Chat will be deleted. There is no way to undo this.'**
  String get deleteChatDialog_content;

  /// No description provided for @deleteChatDialog_cancel.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get deleteChatDialog_cancel;

  /// No description provided for @deleteChatDialog_delete.
  ///
  /// In en, this message translates to:
  /// **'Delete'**
  String get deleteChatDialog_delete;

  /// No description provided for @byteUnit_B.
  ///
  /// In en, this message translates to:
  /// **'B'**
  String get byteUnit_B;

  /// No description provided for @byteUnit_KB.
  ///
  /// In en, this message translates to:
  /// **'KB'**
  String get byteUnit_KB;

  /// No description provided for @byteUnit_MB.
  ///
  /// In en, this message translates to:
  /// **'MB'**
  String get byteUnit_MB;

  /// No description provided for @byteUnit_GB.
  ///
  /// In en, this message translates to:
  /// **'GB'**
  String get byteUnit_GB;

  /// No description provided for @byteUnit_TB.
  ///
  /// In en, this message translates to:
  /// **'TB'**
  String get byteUnit_TB;

  /// No description provided for @byteUnit_PB.
  ///
  /// In en, this message translates to:
  /// **'PB'**
  String get byteUnit_PB;

  /// No description provided for @byteUnit_EB.
  ///
  /// In en, this message translates to:
  /// **'EB'**
  String get byteUnit_EB;

  /// No description provided for @byteUnit_ZB.
  ///
  /// In en, this message translates to:
  /// **'ZB'**
  String get byteUnit_ZB;

  /// No description provided for @byteUnit_YB.
  ///
  /// In en, this message translates to:
  /// **'YB'**
  String get byteUnit_YB;

  /// No description provided for @deleteAccountScreen_title.
  ///
  /// In en, this message translates to:
  /// **'Delete My Account'**
  String get deleteAccountScreen_title;

  /// No description provided for @deleteAccountScreen_explanatoryText.
  ///
  /// In en, this message translates to:
  /// **'This will delete your Air Account and reset the application. You will not be able to recover your account.'**
  String get deleteAccountScreen_explanatoryText;

  /// No description provided for @deleteAccountScreen_confirmationInputHint.
  ///
  /// In en, this message translates to:
  /// **'Confirmation'**
  String get deleteAccountScreen_confirmationInputHint;

  /// No description provided for @deleteAccountScreen_confirmationInputLabel.
  ///
  /// In en, this message translates to:
  /// **'Type \'delete\' to confirm'**
  String get deleteAccountScreen_confirmationInputLabel;

  /// No description provided for @deleteAccountScreen_confirmButtonText.
  ///
  /// In en, this message translates to:
  /// **'Delete Air Account'**
  String get deleteAccountScreen_confirmButtonText;

  /// No description provided for @deleteAccountScreen_cancelButtonText.
  ///
  /// In en, this message translates to:
  /// **'Cancel'**
  String get deleteAccountScreen_cancelButtonText;

  /// No description provided for @deleteAccountScreen_deleteAccountError.
  ///
  /// In en, this message translates to:
  /// **'Something went wrong on our end. Wait a moment, then try again.'**
  String get deleteAccountScreen_deleteAccountError;
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(lookupAppLocalizations(locale));
  }

  @override
  bool isSupported(Locale locale) =>
      <String>['de', 'en', 'fr'].contains(locale.languageCode);

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

AppLocalizations lookupAppLocalizations(Locale locale) {
  // Lookup logic when only language code is specified.
  switch (locale.languageCode) {
    case 'de':
      return AppLocalizationsDe();
    case 'en':
      return AppLocalizationsEn();
    case 'fr':
      return AppLocalizationsFr();
  }

  throw FlutterError(
    'AppLocalizations.delegate failed to load unsupported locale "$locale". This is likely '
    'an issue with the localizations generation tool. Please file an issue '
    'on GitHub with a reproducible sample app and the gen-l10n configuration '
    'that was used.',
  );
}
