// SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

// This file is automatically generated, so please do not edit it.

// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Spanish Castilian (`es`).
class AppLocalizationsEs extends AppLocalizations {
  AppLocalizationsEs([String locale = 'es']) : super(locale);

  @override
  String get appTitle => 'Air';

  @override
  String get languageName => 'Español';

  @override
  String get userSettingsScreen_title => 'Perfil y ajustes';

  @override
  String get userSettingsScreen_profileDescription =>
      'Tu nombre visible y tu foto de perfil son visibles para tus contactos de Air y para los miembros de los grupos en los que estás.';

  @override
  String get userSettingsScreen_userNamesDescription =>
      'Comparte tus nombres de usuario con quien quieras conectar. Los nombres de usuario no son visibles para los demás, ni siquiera para tus contactos de Air. Puedes tener hasta 5 nombres de usuario.';

  @override
  String get userSettingsScreen_help => 'Ayuda';

  @override
  String get userSettingsScreen_deleteAccount => 'Eliminar cuenta de Air';

  @override
  String get userSettingsScreen_sendWithEnter => 'Enviar con Enter';

  @override
  String get userSettingsScreen_sendWithEnterDescription =>
      'Si se activa, la tecla \"Enter\" del teclado envía el mensaje.';

  @override
  String get userSettingsScreen_readReceipts => 'Confirmaciones de lectura';

  @override
  String get userSettingsScreen_readReceiptsDescription =>
      'Si se activa, los demás verán si has leído sus mensajes y tú verás si han leído los tuyos.';

  @override
  String get userSettingsScreen_displayNameLabel => 'Nombre visible';

  @override
  String get userSettingsScreen_usernamesSection => 'Nombres de usuario';

  @override
  String get userSettingsScreen_helpSection => 'Ayuda';

  @override
  String get userSettingsScreen_accountSection => 'Cuenta';

  @override
  String get userSettingsScreen_inviteCodes => 'Códigos de invitación';

  @override
  String get userSettingsScreen_devices => 'Dispositivos';

  @override
  String get youSection_profile => 'Perfil';

  @override
  String get youSection_preferences => 'Preferencias';

  @override
  String get youSection_developer => 'Desarrollador';

  @override
  String get settingsScreen_copiedToClipboard => 'Copiado al portapapeles';

  @override
  String get removeUsernameDialog_title => '¿Quitar el nombre de usuario?';

  @override
  String get removeUsernameDialog_content =>
      'Nadie podrá enviarte una solicitud de contacto con este nombre de usuario, y puede que otra persona lo ocupe.';

  @override
  String get removeUsernameDialog_cancel => 'Cancelar';

  @override
  String get removeUsernameDialog_remove => 'Quitar';

  @override
  String get userSettingsScreen_usernamePlaceholder => 'Nombre de usuario';

  @override
  String get addMembersScreen_addMembers => 'Añadir miembros';

  @override
  String get contactDetailsScreen_title => 'Perfil';

  @override
  String get contactDetailsScreen_chat => 'Chat';

  @override
  String get contactDetailsScreen_viewSafetyCode => 'Código de seguridad';

  @override
  String get contactDetailsScreen_mute => 'Silenciar';

  @override
  String get contactDetailsScreen_unmute => 'Dejar de silenciar';

  @override
  String get safetyCodeScreen_title => 'Código de seguridad';

  @override
  String get safetyCodeScreen_tapToCopy => 'Toca para copiar';

  @override
  String get safetyCodeScreen_copiedToClipboard => 'Copiado al portapapeles';

  @override
  String safetyCodeScreen_safetyCodeExplanation(String displayName) {
    return 'Compara el código de seguridad que ves tú con el que ve $displayName. Si los códigos coinciden, sabes que envías y recibes mensajes cifrados de extremo a extremo con la persona correcta.';
  }

  @override
  String get chatDetailsScreen_unknownChat => 'Chat desconocido';

  @override
  String get muteDurationSheet_title => '¿Silenciar el chat?';

  @override
  String get muteDurationSheet_body =>
      'Elige cuánto tiempo quieres silenciar el chat.';

  @override
  String get muteDurationSheet_1hour => '1 hora';

  @override
  String get muteDurationSheet_8hours => '8 horas';

  @override
  String get muteDurationSheet_untilTomorrow => 'Hasta medianoche';

  @override
  String get muteDurationSheet_untilNextMonday => 'Hasta el próximo lunes';

  @override
  String get muteDurationSheet_always => 'Siempre';

  @override
  String blockedChatFooter_message(String displayName) {
    return 'No recibirás mensajes de $displayName a menos que desbloquees a esta persona.';
  }

  @override
  String get inactiveChatFooter_message => 'Ya no eres miembro de este chat.';

  @override
  String get chatScreen_emptyChat =>
      'Selecciona un chat para empezar a escribir';

  @override
  String get removeUserDialog_title => 'Quitar miembro';

  @override
  String removeUserDialog_content(String displayName) {
    return '¿Seguro que quieres quitar a $displayName del grupo?';
  }

  @override
  String get removeUserDialog_removeUser => 'Quitar miembro';

  @override
  String get removeUserButton_text => 'Quitar';

  @override
  String get blockContactButton_text => 'Bloquear';

  @override
  String blockContactDialog_title(String displayName) {
    return '¿Bloquear a $displayName?';
  }

  @override
  String blockContactDialog_content(String displayName) {
    return 'No recibirás mensajes de $displayName y esa persona no podrá ver los cambios que hagas en tu perfil. Tampoco sabrá que la has bloqueado. Puedes desbloquearla cuando quieras.';
  }

  @override
  String get blockContactDialog_cancel => 'Cancelar';

  @override
  String get blockContactDialog_block => 'Bloquear';

  @override
  String get unblockContactButton_text => 'Desbloquear';

  @override
  String unblockContactDialog_title(String displayName) {
    return '¿Desbloquear a $displayName?';
  }

  @override
  String unblockContactDialog_content(String displayName) {
    return 'Podrás enviar y recibir mensajes de $displayName, y esa persona podrá ver tu perfil actual.';
  }

  @override
  String get unblockContactDialog_cancel => 'Cancelar';

  @override
  String get unblockContactDialog_unblock => 'Desbloquear';

  @override
  String get deleteContactButton_text => 'Eliminar';

  @override
  String get deleteContactDialog_title => 'Eliminar contacto de Air';

  @override
  String deleteContactDialog_content(String displayName) {
    return '¿Seguro que quieres eliminar a tu contacto de Air $displayName? Si lo haces, se eliminarán el chat y su historial de mensajes.';
  }

  @override
  String get deleteContactDialog_cancel => 'Cancelar';

  @override
  String get deleteContactDialog_delete => 'Eliminar';

  @override
  String get addContactDialog_title => 'Añadir contacto de Air';

  @override
  String addContactDialog_content(String displayName, String groupTitle) {
    return '$displayName, del chat de grupo \"$groupTitle\", no es un contacto de Air. Para chatear con esta persona, envíale una solicitud de contacto.';
  }

  @override
  String get addContactDialog_cancel => 'Cancelar';

  @override
  String get addContactDialog_confirm => 'Enviar';

  @override
  String get changeGroupTitleDialog_title => 'Cambiar el nombre del grupo';

  @override
  String get changeGroupTitleDialog_content => 'Elige un nombre para el grupo.';

  @override
  String get changeGroupTitleDialog_cancel => 'Cancelar';

  @override
  String get changeGroupTitleDialog_confirm => 'Guardar';

  @override
  String get unsavedInputDialog_title => '¿Seguro que quieres cerrar?';

  @override
  String get unsavedInputDialog_cancel => 'Cancelar';

  @override
  String get unsavedInputDialog_close => 'Cerrar';

  @override
  String get introScreen_serverLabel =>
      'Elige el servidor al que conectarte para vincular el dispositivo.';

  @override
  String get introScreen_serverHint => 'NOMBRE DE DOMINIO';

  @override
  String get introScreen_linkExisting => 'Vincular a una cuenta existente';

  @override
  String get introScreen_signUp => 'Crear cuenta';

  @override
  String get introScreen_termsLinkText => 'Condiciones de uso';

  @override
  String introScreen_termsText(String termsOfUseLink) {
    return 'Al crear una cuenta, aceptas nuestras $termsOfUseLink.';
  }

  @override
  String get invitationCodeScreen_header => 'Introduce el código de invitación';

  @override
  String get invitationCodeScreen_subheader =>
      'Air funciona por ahora solo con invitación. Introduce tu código para entrar. Si no tienes uno, pídeselo a alguien que ya esté en Air.';

  @override
  String get invitationCodeScreen_inputLabel =>
      'Código de invitación (obligatorio)';

  @override
  String get invitationCodeScreen_inputHint =>
      'Introduce tu código de invitación...';

  @override
  String get invitationCodeScreen_error_invalidLength =>
      'El código debe tener 8 caracteres';

  @override
  String get invitationCodeScreen_actionButton => 'Entrar en Air';

  @override
  String invitationCodeScreen_error_internal(String error) {
    return 'No se pudo comprobar el código de invitación: $error';
  }

  @override
  String get invitationCodeScreen_error_missing =>
      'Falta el código de invitación';

  @override
  String get invitationCodeScreen_error_invalid =>
      'Código de invitación no válido. Compruébalo y vuelve a intentarlo.';

  @override
  String get invitationCodesScreen_title => 'Códigos de invitación';

  @override
  String get invitationCodesScreen_copyAll => 'Copiar todos';

  @override
  String get invitationCodesScreen_tapToGetCode =>
      'Toca para obtener un código';

  @override
  String get invitationCodesScreen_removeUsedCodes =>
      'Quitar los códigos usados';

  @override
  String get invitationCodesScreen_empty =>
      'No hay códigos de invitación disponibles';

  @override
  String get invitationCodesScreen_infoText1 =>
      'Air está en una fase de acceso limitado. Quien quiera entrar necesita un código de invitación.';

  @override
  String get invitationCodesScreen_infoText2 =>
      '¡Comparte estos códigos con tus amistades o con cualquiera que quiera entrar en Air! Se añadirán códigos nuevos cada cierto tiempo.';

  @override
  String get invitationCodesScreen_global_quota_exceeded =>
      'Nos hemos quedado sin invitaciones por ahora, inténtalo más tarde.';

  @override
  String get invitationCodesScreen_errorRequestingCode =>
      'Algo ha salido mal. Inténtalo de nuevo.';

  @override
  String get invitationCodesScreen_copiedToClipboard =>
      'Copiado al portapapeles';

  @override
  String invitationCodesScreen_codeClipboardMessage(String code) {
    return 'Chateemos en Air: https://air.ms/install. Usa el código de invitación $code.';
  }

  @override
  String invitationCodesScreen_codesClipboardMessage(String codes) {
    return 'Chateemos en Air: https://air.ms/install. Usa uno de estos códigos de invitación para entrar:\n\n$codes';
  }

  @override
  String get signUpScreen_header => 'Crea tu perfil';

  @override
  String get signUpScreen_subheader =>
      'Tu perfil es visible para las personas con las que conectas y para los miembros de los grupos en los que estás. Air necesita un nombre visible, pero la foto es opcional.';

  @override
  String get signUpScreen_actionButton => 'Crear';

  @override
  String get signUpScreen_displayNameInputName =>
      'Nombre visible (obligatorio)';

  @override
  String get signUpScreen_displayNameInputHint => 'Añade un nombre...';

  @override
  String get signUpScreen_serverLabel =>
      'Elige el servidor en el que quieres crear tu cuenta.';

  @override
  String get signUpScreen_serverHint => 'NOMBRE DE DOMINIO';

  @override
  String get signUpScreen_error_invalidDomain => 'El dominio no es válido';

  @override
  String get signUpScreen_error_emptyDisplayName =>
      'Añade un nombre visible de al menos un carácter';

  @override
  String signUpScreen_error_register(String error) {
    return 'Error al registrar al usuario: $error';
  }

  @override
  String get usernameOnboarding_header => 'Añade un nombre de usuario';

  @override
  String get usernameOnboarding_body =>
      'Los nombres de usuario son la forma de conectar en Air. Una vez hecha la conexión, dejan de ser visibles para los demás.\n\nPuedes añadir, cambiar o quitar nombres de usuario en cualquier momento desde tu perfil.';

  @override
  String get usernameOnboarding_syntax =>
      'Usa letras, números o guiones. Mínimo 5 caracteres.';

  @override
  String get usernameOnboarding_addButton => 'Añadir';

  @override
  String get usernameOnboarding_error =>
      'Algo ha fallado por nuestra parte. Espera un momento y vuelve a intentarlo.';

  @override
  String get usernameOnboarding_next => 'Siguiente';

  @override
  String get usernameOnboarding_usernameInputName =>
      'Nombre de usuario (opcional)';

  @override
  String get usernameOnboarding_usernameInputHint =>
      'Añade un nombre de usuario...';

  @override
  String get linkingDeviceScreen_header => 'Vincular a una cuenta existente';

  @override
  String get linkingDeviceScreen_connecting => 'Conectando...';

  @override
  String get linkingDeviceScreen_separator => 'o';

  @override
  String get linkingDeviceScreen_numericCode => 'Código numérico';

  @override
  String get linkingDeviceScreen_linking => 'Vinculando...';

  @override
  String get linkingDeviceScreen_linking_confirm_title =>
      'Confirmar la vinculación';

  @override
  String get linkingDeviceScreen_linking_confirm_edit_subtitle =>
      'Toca para editar el nombre del dispositivo';

  @override
  String get linkingDeviceScreen_linking_confirm_body =>
      'Vas a vincular un dispositivo nuevo, que tendrá acceso completo a tu cuenta de Air. Hazlo solo si el dispositivo es tuyo.';

  @override
  String get linkingDeviceScreen_linking_confirm_checkbox =>
      'Quiero vincular este dispositivo.';

  @override
  String get linkingDeviceScreen_linking_confirm_button => 'Confirmar';

  @override
  String get linkingDeviceScreen_instructions_1 =>
      'Abre Air en tu dispositivo actual y ve a Tú → Dispositivos.';

  @override
  String get linkingDeviceScreen_instructions_2 =>
      'Toca \"Vincular un dispositivo\" y luego escanea el código QR o introduce el código numérico de arriba.';

  @override
  String get linkingDeviceScreen_instructions_3 =>
      'Mantén las dos apps abiertas durante la vinculación.';

  @override
  String get linkingDeviceScreen_error_codesExpired_title =>
      'Códigos caducados';

  @override
  String get linkingDeviceScreen_error_codesExpired_message =>
      'Para vincular este dispositivo, recarga los códigos y vuelve a intentarlo.';

  @override
  String get linkingDeviceScreen_error_codesExpired_cancel => 'Cancelar';

  @override
  String get linkingDeviceScreen_error_codesExpired_reload => 'Recargar';

  @override
  String get linkingDevicesScreen_error_title => 'La vinculación ha fallado';

  @override
  String get linkingDevicesScreen_error_generic =>
      'Se ha producido un error desconocido.';

  @override
  String get linkingDevicesScreen_error_sessionNotFound =>
      'El código que has introducido no es correcto.';

  @override
  String get linkingDevicesScreen_error_dismiss => 'Reintentar';

  @override
  String get linkedDevicesScreen_thisDevice => 'Este dispositivo';

  @override
  String get linkedDevicesScreen_linkedDevices => 'Dispositivos vinculados';

  @override
  String linkedDevicesScreen_linkedOn(String date) {
    return 'Vinculado el $date';
  }

  @override
  String get linkedDevicesScreen_editNameHint =>
      'Toca un dispositivo para editar su nombre.';

  @override
  String get linkedDevicesScreen_linkDevice => 'Vincular un dispositivo';

  @override
  String get linkedDevicesScreen_unknownDevice => 'Dispositivo desconocido';

  @override
  String get linkedDevicesScreen_renameError_title =>
      'No se pudo cambiar el nombre.';

  @override
  String linkedDevicesScreen_renameError(String deviceName) {
    return 'No se pudo cambiar el nombre del dispositivo $deviceName. Comprueba tu conexión de red y vuelve a intentarlo.';
  }

  @override
  String get linkedDevicesScreen_unlinkError_title =>
      'No se pudo desvincular el dispositivo.';

  @override
  String linkedDevicesScreen_unlinkError(String deviceName) {
    return 'No se pudo desvincular el dispositivo $deviceName. Comprueba tu conexión de red y vuelve a intentarlo.';
  }

  @override
  String get linkedDevicesScreen_errorDialog_confirm => 'De acuerdo';

  @override
  String linkedDevicesScreen_deviceCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count dispositivos vinculados.',
      one: '$count dispositivo vinculado.',
      zero: 'No hay dispositivos vinculados.',
    );
    return '$_temp0';
  }

  @override
  String get linkedDevicesScreen_encryptionNotice =>
      'Los mensajes están cifrados de extremo a extremo en todos los dispositivos.';

  @override
  String get linkedDevicesScreen_encryptionNotice_learnMore =>
      'Más información.';

  @override
  String get linkedDevicesScreen_encryptionDialog_title =>
      'Cifrado y vinculación de dispositivos';

  @override
  String get linkedDevicesScreen_encryptionDialog_content =>
      'En Air, tus mensajes (incluidos los archivos adjuntos) están siempre cifrados de extremo a extremo. Esto significa que nadie más puede leerlos, ni siquiera Air.\n\nAl vincular un dispositivo, tus mensajes siguen cifrados y eres la única persona que puede leerlos.';

  @override
  String get linkedDevicesScreen_encryptionDialog_confirm => 'De acuerdo';

  @override
  String get linkedDevicesScreen_linkDialog_chooseMethod =>
      'Si usas un teléfono o una tablet con una cámara que funcione, elige \"Escanear código QR\". Si usas un equipo o un dispositivo con una cámara que no funcione, elige \"Introducir código numérico\".';

  @override
  String get linkedDevicesScreen_linkDialog_openApp =>
      'En el dispositivo que quieres vincular, abre Air y toca \"Vincular a una cuenta existente\" en la pantalla de inicio.';

  @override
  String get linkedDevicesScreen_linkDialog_scanQrCode => 'Escanear código QR';

  @override
  String get linkedDevicesScreen_linkDialog_scanQrCode_unavailable =>
      'Escanear código QR (no disponible)';

  @override
  String get linkedDevicesScreen_linkDialog_enterNumericCode =>
      'Introducir código numérico';

  @override
  String get linkedDevicesScreen_linkDialog_warning =>
      'Los dispositivos que vincules tendrán acceso completo a tu cuenta de Air (incluida la posibilidad de añadir o quitar dispositivos, incluso este). Vincula solo dispositivos de confianza.';

  @override
  String get linkedDevicesScreen_linkDialog_numericCodeInstructions =>
      'Introduce el código numérico que aparece en el dispositivo que quieres vincular.';

  @override
  String get linkedDevicesScreen_linkDialog_link => 'Vincular dispositivo';

  @override
  String get linkedDevicesScreen_deviceName_editDialog_title =>
      'Cambiar el nombre del dispositivo';

  @override
  String get linkedDevicesScreen_deviceName_editDialog_cancel => 'Cancelar';

  @override
  String get linkedDevicesScreen_deviceName_editDialog_confirm => 'Cambiar';

  @override
  String get linkedDevicesScreen_unlinkDialog_title =>
      'Desvincular dispositivo';

  @override
  String get linkedDevicesScreen_unlinkDialog_content =>
      'El dispositivo ya no podrá enviar ni recibir mensajes. Todos los datos de tu cuenta se eliminarán de ese dispositivo la próxima vez que se conecte.';

  @override
  String get linkedDevicesScreen_unlinkDialog_cancel => 'Cancelar';

  @override
  String get linkedDevicesScreen_unlinkDialog_confirm => 'Desvincular';

  @override
  String get usernameScreen_title => 'Añadir nombre de usuario';

  @override
  String get usernameScreen_inputHint => 'Escribe un nombre de usuario...';

  @override
  String get usernameScreen_error_emptyUsername =>
      'El nombre de usuario no puede estar vacío';

  @override
  String get usernameScreen_error_alreadyExists =>
      'Ese nombre de usuario ya está en uso';

  @override
  String get usernameScreen_description =>
      'Elige un nombre de usuario con el que otras personas puedan conectar contigo.';

  @override
  String get usernameScreen_syntax =>
      'Usa letras, números o guiones. Mínimo 5 caracteres.';

  @override
  String get usernameScreen_cancel => 'Cancelar';

  @override
  String get usernameScreen_confirm => 'Añadir';

  @override
  String get usernameScreen_error_tooShort =>
      'El nombre de usuario debe tener al menos 5 caracteres';

  @override
  String get usernameScreen_error_tooLong =>
      'El nombre de usuario no puede tener más de 63 caracteres';

  @override
  String get usernameScreen_error_invalidCharacter =>
      'El nombre de usuario solo puede contener letras, números o guiones';

  @override
  String get usernameScreen_error_consecutiveDashes =>
      'El nombre de usuario no puede tener guiones seguidos';

  @override
  String get usernameScreen_error_leadingDigit =>
      'El nombre de usuario no puede empezar por un número';

  @override
  String editDialog_characters_remaining(int characters, int remaining) {
    return '$characters/$remaining caracteres';
  }

  @override
  String get editDisplayNameScreen_title => 'Cambiar el nombre visible';

  @override
  String get editDisplayNameScreen_description =>
      'Elige el nombre que verán los demás.';

  @override
  String get editDisplayNameScreen_cancel => 'Cancelar';

  @override
  String get editDisplayNameScreen_save => 'Guardar';

  @override
  String systemMessage_userAddedUser(String user1, String user2) {
    return '$user1 añadió a $user2';
  }

  @override
  String systemMessage_userRemovedUser(String user1, String user2) {
    return '$user1 quitó a $user2';
  }

  @override
  String systemMessage_userChangedTitle(
    String user,
    String old_name,
    String new_name,
  ) {
    return '$user cambió el nombre del grupo de $old_name a $new_name';
  }

  @override
  String systemMessage_acceptedHandleConnectionRequest(
    String displayName,
    String username,
  ) {
    return 'Has aceptado la solicitud de contacto de $displayName, enviada a tu nombre de usuario $username.';
  }

  @override
  String systemMessage_acceptedDirectConnectionRequest(String displayName) {
    return 'Has aceptado la solicitud de contacto de $displayName, enviada a través de un chat de grupo en común.';
  }

  @override
  String systemMessage_receivedConnectionConfirmation(String displayName) {
    return '$displayName ha aceptado tu solicitud de contacto.';
  }

  @override
  String systemMessage_newHandleConnectionChat(String username) {
    return 'Has enviado una solicitud de contacto al nombre de usuario $username. Puede que no reciba el aviso de inmediato.';
  }

  @override
  String systemMessage_newDirectConnectionChat(String displayName) {
    return 'Has enviado una solicitud de contacto a $displayName. Puede que no reciba el aviso de inmediato.';
  }

  @override
  String systemMessage_receivedHandleConnectionRequest(
    String displayName,
    String username,
  ) {
    return '$displayName te ha enviado una solicitud de contacto a tu nombre de usuario $username.';
  }

  @override
  String systemMessage_receivedDirectConnectionRequest(
    String displayName,
    String groupName,
  ) {
    return '$displayName te ha enviado una solicitud de contacto a través del chat de grupo $groupName.';
  }

  @override
  String systemMessage_userChangedPicture(String user) {
    return '$user cambió la foto del grupo';
  }

  @override
  String systemMessage_userCreatedGroup(String user) {
    return '$user creó el grupo';
  }

  @override
  String get systemMessage_onboarded =>
      'Este cliente se ha incorporado al chat después de la vinculación.';

  @override
  String get timestamp_now => 'Ahora';

  @override
  String timestamp_minutesAgo(int count) {
    return '$count min';
  }

  @override
  String get date_today => 'Hoy';

  @override
  String get date_yesterday => 'Ayer';

  @override
  String get messageBubble_sending => 'Enviando';

  @override
  String get messageBubble_failedToSend => 'No se pudo enviar';

  @override
  String get messageBubble_sent => 'Enviado';

  @override
  String get messageBubble_delivered => 'Entregado';

  @override
  String get messageBubble_read => 'Leído';

  @override
  String get chatList_newContact => 'Nuevo contacto de Air';

  @override
  String get chatList_newGroup => 'Nuevo chat de grupo';

  @override
  String get chatList_emptyMessage =>
      'Añade tu primer contacto de Air para empezar';

  @override
  String get chatList_draft => 'Borrador';

  @override
  String get chatList_you => 'Tú';

  @override
  String get chatList_imageEmoji => '🖼️';

  @override
  String get chatList_fileEmoji => '📎';

  @override
  String get chatList_blocked => 'Bloqueado';

  @override
  String chatList_reaction(String user, String emoji, String message) {
    return '$user reaccionó con $emoji a \"$message\"';
  }

  @override
  String chatList_reactionByYou(String emoji, String message) {
    return 'Reaccionaste con $emoji a \"$message\"';
  }

  @override
  String get chatList_contextMenu_mute => 'Silenciar';

  @override
  String get chatList_contextMenu_unmute => 'Dejar de silenciar';

  @override
  String newChatDialog_error(String chatName) {
    return 'No se pudo crear el chat de grupo $chatName';
  }

  @override
  String newChatDialog_error_incompatibleClient(String chatName) {
    return 'No se pudo crear el chat de grupo $chatName porque uno de los contactos tiene un cliente incompatible.';
  }

  @override
  String get newConnectionDialog_newConnectionTitle => 'Añadir contacto de Air';

  @override
  String get newConnectionDialog_newConnectionDescription =>
      'Introduce el nombre de usuario de la persona a la que quieres escribir.';

  @override
  String get newConnectionDialog_inputLabel =>
      'Nombre de usuario (obligatorio)';

  @override
  String get newConnectionDialog_usernamePlaceholder =>
      'Escribe un nombre de usuario...';

  @override
  String newConnectionDialog_handleExists(String username) {
    return '$username existe. Toca “Enviar” para mandar una solicitud de contacto.';
  }

  @override
  String get newConnectionDialog_cancel => 'Cancelar';

  @override
  String get newConnectionDialog_confirm1 => 'Comprobar';

  @override
  String get newConnectionDialog_confirm2 => 'Enviar';

  @override
  String newConnectionDialog_error(String username) {
    return 'No se pudo enviar la solicitud de contacto a $username. Inténtalo de nuevo.';
  }

  @override
  String get newConnectionDialog_error_emptyUsername =>
      'Escribe el nombre de usuario';

  @override
  String newConnectionDialog_error_usernameNotFound(String username) {
    return 'No se encontró $username. Compruébalo y vuelve a intentarlo.';
  }

  @override
  String get newConnectionDialog_error_duplicateRequest =>
      'Ya tienes una solicitud de contacto pendiente para este nombre de usuario.';

  @override
  String get newConnectionDialog_error_ownUsername =>
      'No puedes enviarte una solicitud de contacto.';

  @override
  String composer_inputHint(String chatTitle) {
    return 'Mensaje para $chatTitle';
  }

  @override
  String get composer_editMessage => 'Editar mensaje';

  @override
  String get composer_error_sendMessage =>
      'No se pudo enviar el mensaje. Inténtalo de nuevo.';

  @override
  String get composer_error_attachment =>
      'No se pudo subir el archivo adjunto. Inténtalo de nuevo.';

  @override
  String composer_error_attachment_too_large(
    String actualSize,
    String maxSize,
  ) {
    return 'El archivo adjunto es demasiado grande. El tamaño máximo es $maxSize y el del archivo es $actualSize.';
  }

  @override
  String get composer_reply_deleted_message_placeholder =>
      'Mensaje original eliminado';

  @override
  String get composer_reply_noaccess_message_user => 'Usuario desconocido';

  @override
  String get composer_reply_noaccess_message_placeholder =>
      'No tienes acceso a este mensaje.';

  @override
  String attachmentSize(double size, String byteUnit) {
    final intl.NumberFormat sizeNumberFormat =
        intl.NumberFormat.decimalPatternDigits(
          locale: localeName,
          decimalDigits: 2,
        );
    final String sizeString = sizeNumberFormat.format(size);

    return '$sizeString $byteUnit';
  }

  @override
  String get attachment_images => 'Imágenes';

  @override
  String get attachment_camera => 'Cámara';

  @override
  String get attachment_otherFiles => 'Otros archivos';

  @override
  String get attachment_notFound => 'El archivo adjunto ya no está disponible.';

  @override
  String get textMessage_edited => 'Editado';

  @override
  String get textMessage_hiddenPlaceholder =>
      'Usuario bloqueado, toca para ver el mensaje';

  @override
  String get textMessage_deleted => 'Mensaje eliminado';

  @override
  String get textMessage_deletedBySelf => 'Has eliminado este mensaje.';

  @override
  String textMessage_deletedByOther(String senderName) {
    return '$senderName ha eliminado este mensaje.';
  }

  @override
  String get linkConfirmation_title => '¿Abrir el enlace?';

  @override
  String get linkConfirmation_description =>
      'Comprueba la URL para asegurarte de que quieres abrirla:';

  @override
  String get linkConfirmation_openLink => 'Abrir';

  @override
  String get linkConfirmation_cancel => 'Cancelar';

  @override
  String get messageContextMenu_reply => 'Responder';

  @override
  String get messageContextMenu_copy => 'Copiar';

  @override
  String get messageContextMenu_edit => 'Editar';

  @override
  String get messageContextMenu_delete => 'Eliminar';

  @override
  String get messageContextMenu_save => 'Guardar';

  @override
  String get messageContextMenu_share => 'Compartir';

  @override
  String get messageContextMenu_saveError =>
      'No se pudo guardar el archivo adjunto';

  @override
  String get messageContextMenu_saveConfirmation => 'Archivo adjunto guardado';

  @override
  String get deleteMessageDialog_title => '¿Eliminar el mensaje?';

  @override
  String get deleteMessageDialog_description =>
      'Elige para quién quieres eliminar este mensaje. Se eliminará de todos tus dispositivos.';

  @override
  String get deleteMessageDialog_forEveryone => 'Eliminar para todos';

  @override
  String get deleteMessageDialog_forMe => 'Eliminar solo para mí';

  @override
  String get deleteMessageForMeDialog_title => '¿Eliminar el mensaje?';

  @override
  String get deleteMessageForMeDialog_description =>
      'Este mensaje se eliminará de todos tus dispositivos.';

  @override
  String get deleteMessageForMeDialog_delete => 'Eliminar';

  @override
  String get reportSpamButton_text => 'Reportar spam';

  @override
  String get reportSpamDialog_title => '¿Reportar spam?';

  @override
  String get reportSpamDialog_content =>
      'Air recibirá un aviso de que esta persona podría estar enviando spam. Air nunca puede ver el contenido de los chats.';

  @override
  String get reportSpamDialog_cancel => 'Cancelar';

  @override
  String get reportSpamDialog_reportSpam => 'Reportar spam';

  @override
  String get reportSpamDialog_success => 'Spam reportado';

  @override
  String get reportSpamDialog_error =>
      'No se pudo reportar el spam. Inténtalo de nuevo.';

  @override
  String get helpScreen_contactUs => 'Contactar con Air';

  @override
  String get helpScreen_versionInfo => 'Información de versión';

  @override
  String get helpScreen_licenses => 'Licencias';

  @override
  String get licensesScreen_title => 'Licencias';

  @override
  String get contactUsScreen_title => 'Contactar con Air';

  @override
  String get contactUsScreen_subject => 'Asunto del mensaje';

  @override
  String get contactUsScreen_body => 'Mensaje';

  @override
  String get contactUsScreen_includeLogs =>
      'Comparte tus registros (así Air puede corregir errores)';

  @override
  String get contactUsScreen_composeEmail => 'Redactar correo';

  @override
  String get contactUsScreen_subject_somethingNotWorking => 'Algo no funciona';

  @override
  String get contactUsScreen_subject_iHaveAQuestion => 'Tengo una pregunta';

  @override
  String get contactUsScreen_subject_requestFeature => 'Solicitar una función';

  @override
  String get contactUsScreen_subject_other => 'Otro';

  @override
  String get contactUsScreen_subject_empty => 'Selecciona un asunto';

  @override
  String get contactUsScreen_body_empty => 'Escribe tu mensaje';

  @override
  String get contactUsScreen_body_tooShort => 'Añade más información';

  @override
  String contactUsScreen_body_logsUrl(String url) {
    return 'Aquí tienes unos registros para ayudarte a depurar mi problema: $url';
  }

  @override
  String get contactUsScreen_errorLaunchingEmail =>
      'No se pudo abrir el cliente de correo';

  @override
  String get contactUsScreen_errorUploadingLogs =>
      'No se pudieron subir los registros';

  @override
  String get groupDetails_title => 'Detalles del grupo';

  @override
  String get groupDetails_leaveChat => 'Salir';

  @override
  String get groupDetails_deleteChat => 'Eliminar';

  @override
  String get groupDetails_addPeople => 'Añadir personas';

  @override
  String groupDetails_memberCount(int count) {
    String _temp0 = intl.Intl.pluralLogic(
      count,
      locale: localeName,
      other: '$count personas',
      one: '$count persona',
    );
    return '$_temp0';
  }

  @override
  String get groupDetails_seeAll => 'Ver todos';

  @override
  String get groupMembersScreen_title => 'Miembros del grupo';

  @override
  String get groupMembersScreen_searchHint => 'Buscar';

  @override
  String get groupCreationScreen_title => 'Añadir miembros';

  @override
  String get groupCreationScreen_next => 'Siguiente';

  @override
  String get groupCreationDetails_title => 'Detalles del grupo';

  @override
  String get groupCreationDetails_groupNameHint =>
      'Nombre del grupo (obligatorio)';

  @override
  String get groupCreationDetails_groupNameHintFocused => 'Nombre del grupo';

  @override
  String get groupCreationDetails_groupNameHelper => 'Usa al menos un carácter';

  @override
  String get groupCreationDetails_create => 'Crear';

  @override
  String get groupCreationDetails_emptySelection => 'Sin miembros';

  @override
  String get addMembersScreen_done => 'Listo';

  @override
  String get addMembersScreen_error_incompatibleClient =>
      'No se pudo añadir a los miembros porque uno de los contactos tiene un cliente incompatible';

  @override
  String get leaveChatDialog_title => 'Salir del grupo';

  @override
  String leaveChatDialog_content(String chatName) {
    return '¿Seguro que quieres salir de $chatName?';
  }

  @override
  String get leaveChatDialog_cancel => 'Cancelar';

  @override
  String get leaveChatDialog_leave => 'Salir';

  @override
  String get deleteChatDialog_title => '¿Eliminar el chat?';

  @override
  String get deleteChatDialog_content =>
      'Este chat se eliminará. No hay forma de deshacerlo.';

  @override
  String get deleteChatDialog_delete => 'Eliminar';

  @override
  String get byteUnit_B => 'B';

  @override
  String get byteUnit_KB => 'KB';

  @override
  String get byteUnit_MB => 'MB';

  @override
  String get byteUnit_GB => 'GB';

  @override
  String get byteUnit_TB => 'TB';

  @override
  String get byteUnit_PB => 'PB';

  @override
  String get byteUnit_EB => 'EB';

  @override
  String get byteUnit_ZB => 'ZB';

  @override
  String get byteUnit_YB => 'YB';

  @override
  String get deleteAccountScreen_title => 'Eliminar mi cuenta';

  @override
  String get deleteAccountScreen_explanatoryText =>
      'Se eliminará tu cuenta de Air y se restablecerá la aplicación. No podrás recuperar tu cuenta.';

  @override
  String get deleteAccountScreen_confirmationInputHint => 'Confirmación';

  @override
  String get deleteAccountScreen_confirmationInputLabel =>
      'Escribe \'delete\' para confirmar.';

  @override
  String get deleteAccountScreen_confirmButtonText => 'Eliminar';

  @override
  String get deleteAccountScreen_deleteAccountError =>
      'Algo ha fallado por nuestra parte. Espera un momento y vuelve a intentarlo.';

  @override
  String get appOutdatedScreen_title => 'Actualización necesaria';

  @override
  String get appOutdatedScreen_message => 'Actualiza para seguir usando Air';

  @override
  String get appOutdatedScreen_description =>
      'Abre TestFlight en iOS o Google Play en Android y actualiza Air.';

  @override
  String get appOutdatedScreen_action => 'Actualizar';

  @override
  String get contactRequestDialog_title => 'Solicitud de contacto';

  @override
  String get contactRequestDialog_avatarHint => 'Toca para ver su foto';

  @override
  String get contactRequestDialog_cancel => 'Más tarde';

  @override
  String get contactRequestDialog_confirm => 'Aceptar';

  @override
  String get contactRequestDialog_error_fatal =>
      'No se pudo aceptar la solicitud de contacto';

  @override
  String get contactRequestDialog_error_incompatibleClient =>
      'No se pudo aceptar la solicitud de contacto. Actualiza Air a la última versión y vuelve a intentarlo.';

  @override
  String get errorBanner_ok => 'OK';

  @override
  String get memberSelectionList_client_not_supported =>
      'Este contacto tiene una versión antigua de la app que necesita actualizarse.';

  @override
  String get homeTab_chats => 'Chats';

  @override
  String get homeTab_profile => 'Tú';

  @override
  String get messageList_newMessages => 'Mensajes nuevos';

  @override
  String get messageList_reactions_react => 'Reaccionar';

  @override
  String get messageList_reactions_remove => 'Quitar';

  @override
  String get messageList_reactions_you => 'Tú';

  @override
  String messageList_reactions_all(int total) {
    return 'Todas · $total';
  }

  @override
  String get emojiPicker_searchHint => 'Buscar emoji';

  @override
  String get emojiPicker_empty => 'No se encontró ningún emoji';

  @override
  String get emojiPicker_skinToneHelp =>
      'Define tu tono de piel predeterminado';
}
