# SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

application:
  listen: 127.0.0.1:8080
  domain: ""
database:
  host: "127.0.0.1"
  port: 5432
  username: "postgres"
  password: "password"
  name: "air_db"
