# SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

application:
  domain: localhost

storage:
  endpoint: http://localhost:9000
  region: eu-west-1
  access_key_id: minioaccesskey
  secret_access_key: miniosecretkey
  force_path_style: true
