# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
apiVersion: apps/v1
kind: Deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: airserver
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    spec:
      containers:
      - env:
        - name: AIR_APPLICATION_DOMAIN
          value: prod.air.ms
        - name: AIR_DATABASE_HOST
          value: db-dev-homadadsybgo.db.upclouddatabases.com
        - name: AIR_DATABASE_PORT
          value: "11569"
        - name: AIR_DATABASE_CACERTPATH
          value: /etc/db-ca-cert/ca.crt
        - name: AIR_DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: prod-postgres-credentials
        - name: AIR_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: prod-postgres-credentials
        - name: AIR_DATABASE_NAME
          value: air_server_db
        - name: AIR_APNS_KEYID
          valueFrom:
            secretKeyRef:
              key: key-id
              name: apns-credentials
        - name: AIR_APNS_TEAMID
          valueFrom:
            secretKeyRef:
              key: team-id
              name: apns-credentials
        - name: AIR_APNS_PRIVATEKEYPATH
          value: /etc/apns-key/apns-key.p8
        - name: AIR_FCM_PATH
          value: /etc/fcm-service-account/fcm-service-account.json
        - name: RUST_LOG
          value: info
        image: ghcr.io/phnx-im/airserver
        imagePullPolicy: Always
        name: airserver
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/db-ca-cert
          name: ca-cert-volume
          readOnly: true
        - mountPath: /etc/apns-key
          name: apns-key-volume
          readOnly: true
        - mountPath: /etc/fcm-service-account
          name: fcm-service-account-volume
          readOnly: true
        - mountPath: server/configuration/production.yaml
          name: configuration
          readOnly: true
          subPath: production.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ca-cert-volume
        secret:
          defaultMode: 420
          secretName: db-ca-cert
      - name: apns-key-volume
        secret:
          defaultMode: 420
          secretName: apns-key
      - name: fcm-service-account-volume
        secret:
          defaultMode: 420
          secretName: fcm-service-account
      - name: configuration
        secret:
          defaultMode: 420
          secretName: air-backend-config

