// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated via app/tool/compile_svg_icons.dart

import 'dart:convert';
import 'package:air/ui/colors/themes.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter/widgets.dart';
import 'package:vector_graphics/vector_graphics_compat.dart';

enum AppIconType {
  arrowLeft,
  arrowRight,
  arrowUp,
  ban,
  camera,
  checkCheckFill,
  checkCheck,
  check,
  circleAlert,
  circleDashed,
  copy,
  download,
  fileDown,
  fileText,
  fileUp,
  globe,
  imageOff,
  imagePlus,
  image,
  logOut,
  messageCircle,
  paperclip,
  pencil,
  plus,
  refreshCcw,
  refreshCw,
  repeat,
  search,
  send,
  settings,
  share,
  shield,
  squareCheck,
  square,
  trash,
  upload,
  user,
  users,
  x,
}

final Map<AppIconType, _InlineBytesLoader> _compiledSvgLoaders = {
  AppIconType.arrowLeft: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAADAAAAAAEBBgAAAAAAAAAAQEEAAJhBAACgQAAAQEEAAEBBAACgQBsAAQACAAAAAAEEAAAAAAAAAJhBAABAQQAAoEAAAEBBMB4AAAAA//8eAQAAAP//',
  ),
  AppIconType.arrowRight: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAACgQAAAQEEAAJhBAABAQRsAAQADAAAAAAEBBgAAAAAAAEBBAACgQAAAmEEAAEBBAABAQQAAmEEwHgAAAAD//x4BAAAA//8=',
  ),
  AppIconType.arrowUp: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAADAAAAAAEBBgAAAAAAAAAAoEAAAEBBAABAQQAAoEAAAJhBAABAQRsAAQACAAAAAAEEAAAAAAAAAEBBAACYQQAAQEEAAKBAMB4AAAAA//8eAQAAAP//',
  ),
  AppIconType.ban: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAXrqdQF66nUBcj5hBaJGYQRsAAQAGAAAAAAICAgIDGgAAAAAAAABAQQAAAEA4J4xBAAAAQAAAsEEfY89AAACwQQAAQEEAALBBOCeMQTgnjEEAALBBAABAQQAAsEEfY89AAACwQQAAAEA4J4xBAAAAQAAAQEEAAABAH2PPQB9jz0AAAABAAABAQQAAAEAwHgAAAAD//x4BAAAA//8=',
  ),
  AppIconType.camera: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAARAAAAAAIBAgECAQIBAgECAQIBAgNAAAAAALbzX0EAAIBAcbZrQdT/f0CThnZBzeaMQKwcfEGamaFAqvGBQWZmvkC2vIRBMxnTQMckikEWAOBAJQaQQQAA4EAAAKBBAADgQCnWqEEAAOBAAACwQV6n/EAAALBBAAAQQQAAsEEAAJBBAACwQSnWmEEp1qhBAACgQQAAoEEAAKBBAACAQAAAoEG8TjlAAACgQQAAAEAp1phBAAAAQAAAkEEAAABAAAAQQQAAAEBep/xAvE45QAAA4EAAAIBAAADgQG3nv0AAAOBAcWbXQFQA4EABAu1AqiDTQCcx+EDJdr5AhesDQTeJoUAYgwlBVt+MQOBQFEFX/39AYhAgQQAAgEAbAAEABgAAAAACAgICAxoAAAAAAAAAQEEAACBB731aQQAAIEEAAHBBEYI1QQAAcEEAAFBBAABwQe99akHvfVpBAACAQQAAQEEAAIBBEYIlQQAAgEEAABBB731qQQAAEEEAAFBBAAAQQRGCNUERgiVBAAAgQQAAQEEAACBBMB4AAAAA//8eAQAAAP//',
  ),
  AppIconType.checkCheckFill: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEcAAAA/wMAAP//GwEAABwAAAAAAgICAgMAAgEBAgIBAgECAwACAQECAgECAQIDagAAAAAAQEEAAJA/fgyQQQAAkD8AALdBB86/QAAAt0EAAEBBAAC3QX4MkEF+DJBBAAC3QQAAQEEAALdBB86/QAAAt0EAAJA/fgyQQQAAkD8AAEBBAACQPwfOv0AHzr9AAACQPwAAQEEAAJA/A/icQfCnIkF3PppBCCwdQQfOlUG+JB1B+Q+TQfaXIkHn+1tB5j9sQfkPVUHZX2VB3pNPQZHtX0EXt0ZBH/RfQf5DQUHSb2VBt9E7Qe7rakGu2DtBHclzQfhTQUHNO3lB8x9SQQP4hEHqlVdBSa6HQX9qYEF9rodBDeBlQQP4hEEH8JxB63M2QXetn0E7ATFBvrCfQQskKEED+JxB8KciQfmPhkH7P+xAbdaDQV5L4UCrz35BeTvhQPhTeUEIIOxA/PsHQQisZkEFwLNA9ds4QQzIqEDcaDNBjgaXQCJsM0EIIIxA1ec4QYI5gUDxYz5BLEiBQNBER0H7P4xA6bdMQfs//EAULoJB1ZUDQVrkhEFLagxBj+SEQQPgEUEULoJB/YeGQfzvCUELRolBznwEQYZJiUEJOPdA+Y+GQfs/7EAwHgAAAAD//w==',
  ),
  AppIconType.checkCheck: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEcHh4f8gMAAP//GwAAABYAAAAAAgIBAgECAgEBAwACAgECAQICAQEDUAAAAAAA4QurQbcXFkGux61BEqAQQR04skESoBBB6/O0QbcXFkG4r7dBXI8bQbivt0E7cCRB6/O0QdXnKUHV53FB6/OQQTtwbEG4r5NBXI9jQbivk0HCF15B6/OQQcIXRkHr84RBJ6BAQR04gkEnoEBBXI97QcIXRkHCF3ZBXI9LQSegcEE7cFRBJ6BwQdXnWUHCF3ZBl/9nQfYXgkHhC6tBtxcWQeELi0FvL6xArseNQSVAoUAdOJJBJUChQOvzlEFvL6xAuK+XQbget0C4r5dBN+DIQOvzlEFsz9NAbM/zQOvzjEE34OhAuK+PQbge10C4r49Bby/MQOvzjEG6vbA/1edJQZMAhT87cERBkwCFP1yPO0G6vbA/whc2QeF63D8noDBBbsARQCegMEHYnidAwhc2QW3/30DsL3xB4QuLQW8vrEAwHgAAAAD//w==',
  ),
  AppIconType.check: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAADAAAAAAEBBgAAAAAAAAAAoEEAAMBAAAAQQQAAiEEAAIBAAABAQTAeAAAAAP//',
  ),
  AppIconType.circleAlert: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAGAAAAAAICAgIDGgAAAAAAQEEAAABAOCeMQQAAAEAAALBBH2PPQAAAsEEAAEBBAACwQTgnjEE4J4xBAACwQQAAQEEAALBBH2PPQAAAsEEAAABAOCeMQQAAAEAAAEBBAAAAQB9jz0AfY89AAAAAQAAAQEEAAABAGwABAAIAAAAAAQQAAAAAAAAAQEEAAABBAABAQQAAQEEbAAIAAgAAAAABBAAAAAAAAABAQQAAgEH2KEBBAACAQTAeAAAAAP//HgEAAAD//x4CAAAA//8=',
  ),
  AppIconType.circleDashed: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAIIAAAAmpkhQeOlC0AurjVBIDX4P9NRSkEgNfg/Z2ZeQeOlC0AbAAEAAgAAAAACCAAAAAAAZmZeQUSLrkHTUUpBrnywQS6uNUGufLBBmpkhQUSLrkEbAAIAAgAAAAACCAAAAAAAO9+MQd0kbkAfXZVBTxaOQHarnEF4a6tAWmSiQdV4zUAbAAMAAgAAAAACCAAAAAAA46ULQGZmXkEgNfg/01FKQSA1+D8urjVB46ULQJqZIUEbAAQAAgAAAAACCAAAAAAAZDuiQTvfjEFsepxBH12VQSIllUF2q5xBy6GMQVpkokEbAAUAAgAAAAACCAAAAAAARIuuQZqZIUGufLBBLq41Qa58sEHTUUpBRIuuQWdmXkEbAAYAAgAAAAACCAAAAAAA3SRuQBKDzEBPFo5Ag4uqQHhrq0AqUo1A1XjNQC/dbEAbAAcAAgAAAAACCAAAAAAAEoPMQGQ7okGDi6pAbHqcQSpSjUAiJZVBL91sQMuhjEEwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//x4EAAAA//8eBQAAAP//HgYAAAD//x4HAAAA//8=',
  ),
  AppIconType.copy: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAKAAAAAAECAQIBAgECAyIAAAAAACBBAAAAQQAAoEEAAABBpdSoQQAAAEEAALBBtlYOQQAAsEEAACBBAACwQQAAoEEAALBBpdSoQaXUqEEAALBBAACgQQAAsEEAACBBAACwQbZWDkEAALBBAAAAQaXUqEEAAABBAACgQQAAAEEAACBBAAAAQbZWDkG2Vg5BAAAAQQAAIEEAAABBGwABAAYAAAAAAgECAQIYAAAAAAAAAIBAAACAQZqZOUAAAIBBAAAAQJqZcUEAAABAAABgQQAAAEAAAIBAAAAAQJqZOUCamTlAAAAAQAAAgEAAAABAAABgQQAAAECamXFBAAAAQAAAgEGamTlAAACAQQAAgEAwHgAAAAD//x4BAAAA//8=',
  ),
  AppIconType.download: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAABAQQAAcEEAAEBBAABAQBsAAQAGAAAAAAECAQIBFAAAAAAAAACoQQAAcEEAAKhBAACYQQAAqEEp1qBBKdagQQAAqEEAAJhBAACoQQAAoEAAAKhBvE55QAAAqEEAAEBAKdagQQAAQEAAAJhBAABAQAAAcEEbAAIAAwAAAAABAQYAAAAAAADgQAAAIEEAAEBBAABwQQAAiEEAACBBMB4AAAAA//8eAQAAAP//HgIAAAD//w==',
  ),
  AppIconType.fileDown: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAIBAgECAQIBAgMoAAAAAAAAAADAQAAAsEFep5xAAACwQQAAgEAp1qhBAACAQAAAoEEAAIBAAACAQAAAgEC8TjlAXqecQAAAAEAAAMBAAAAAQAAAYEEAAABA1zpqQQze/z8fC3RBkjIQQJZDe0EbLy1ABFaaQXNoyUAY+J1BrtrXQCICoEFIgutAAACgQQAAAEEAAKBBAACgQQAAoEEp1qhBKdaYQQAAsEEAAJBBAACwQRsAAQAEAAAAAAECAQwAAAAAAGBBAAAAQAAAYEEAAOBAAABgQVGs8UDXKWdBAAAAQQAAcEEAAABBAACgQQAAAEEbAAIAAgAAAAABBAAAAAAAAABAQQAAkEEAAEBBAABAQRsAAwADAAAAAAEBBgAAAAAAABBBAABwQQAAQEEAAJBBAABwQQAAcEEwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//w==',
  ),
  AppIconType.fileText: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAIBAgECAQIBAgMoAAAAAAAAAADAQAAAsEFep5xAAACwQQAAgEAp1qhBAACAQAAAoEEAAIBAAACAQAAAgEC8TjlAXqecQAAAAEAAAMBAAAAAQAAAYEEAAABA1zpqQQze/z8fC3RBkjIQQJZDe0EbLy1ABFaaQXNoyUAY+J1BrtrXQCICoEFIgutAAACgQQAAAEEAAKBBAACgQQAAoEEp1qhBKdaYQQAAsEEAAJBBAACwQRsAAQAEAAAAAAECAQwAAAAAAGBBAAAAQAAAYEEAAOBAAABgQVGs8UDXKWdBAAAAQQAAcEEAAABBAACgQQAAAEEbAAIAAgAAAAABBAAAAAAAAAAgQQAAEEEAAABBAAAQQRsAAwACAAAAAAEEAAAAAAAAAIBBAABQQQAAAEEAAFBBGwAEAAIAAAAAAQQAAAAAAAAAgEEAAIhBAAAAQQAAiEEwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//x4EAAAA//8=',
  ),
  AppIconType.fileUp: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAIBAgECAQIBAgMoAAAAAAAAAADAQAAAsEFep5xAAACwQQAAgEAp1qhBAACAQAAAoEEAAIBAAACAQAAAgEC8TjlAXqecQAAAAEAAAMBAAAAAQAAAYEEAAABA1zpqQQze/z8fC3RBkjIQQJZDe0EbLy1ABFaaQXNoyUAY+J1BrtrXQCICoEFIgutAAACgQQAAAEEAAKBBAACgQQAAoEEp1qhBKdaYQQAAsEEAAJBBAACwQRsAAQAEAAAAAAECAQwAAAAAAGBBAAAAQAAAYEEAAOBAAABgQVGs8UDXKWdBAAAAQQAAcEEAAABBAACgQQAAAEEbAAIAAgAAAAABBAAAAAAAAABAQQAAQEEAAEBBAACQQRsAAwADAAAAAAEBBgAAAAAAAHBBAABwQQAAQEEAAEBBAAAQQQAAcEEwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//w==',
  ),
  AppIconType.globe: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAGAAAAAAICAgIDGgAAAAAAQEEAAABAOCeMQQAAAEAAALBBH2PPQAAAsEEAAEBBAACwQTgnjEE4J4xBAACwQQAAQEEAALBBH2PPQAAAsEEAAABAOCeMQQAAAEAAAEBBAAAAQB9jz0AfY89AAAAAQAAAQEEAAABAGwABAAMAAAAAAgIOAAAAAAAAQEEAAABAVVXVQDMz80BVVdVAMzODQQAAQEEAALBBq6qKQTMzg0GrqopBMzPzQAAAQEEAAABAGwACAAIAAAAAAQQAAAAAAAAAAEAAAEBBAACwQQAAQEEwHgAAAAD//x4BAAAA//8eAgAAAP//',
  ),
  AppIconType.imageOff: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAAAAQAAAAEAAALBBAACwQRsAAQADAAAAAAICDgAAAABcjyZBXI8mQaAOGkGVETNB0McFQTASM0GqjPJAtZAmQbSJ2UA6DxpB6YrZQGrIBUFcj/JAXI/yQBsAAgACAAAAAAEEAAAAAAAAAFhBAABYQQAAwEAAAKhBGwADAAIAAAAAAQQAAAAAAAAAkEEAAEBBAACoQQAAcEEbAAQABgAAAAACAQIBAhgAAAAAAI/CZUCPwmVAralNQEGdfUCOEkBA4guPQAAAQEAAAKBAAABAQAAAmEEAAEBAKdagQbxOeUAAAKhBAACgQAAAqEEAAJhBAACoQWZmnEEAAKhBf2qgQXE9pkGuR6NBrkejQRsABQAEAAAAAAECAQwAAAAAAKhBAABwQQAAqEEAAKBAAACoQbxOeUAp1qBBAABAQAAAmEEAAEBAAAAQQQAAQEAwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//x4EAAAA//8eBQAAAP//',
  ),
  AppIconType.imagePlus: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAACAQQAAoEAAALBBAACgQBsAAQACAAAAAAEEAAAAAAAAAJhBAAAAQAAAmEEAAABBGwACAAgAAAAAAQIBAgECARwAAAAAAKhBAAA4QQAAqEEAAJhBAACoQSnWoEEp1qBBAACoQQAAmEEAAKhBAACgQAAAqEG8TnlAAACoQQAAQEAp1qBBAABAQAAAmEEAAEBAAACgQAAAQEC8TnlAvE55QAAAQEAAAKBAAABAQAAASEEAAEBAGwADAAQAAAAAAQIBDAAAAAAAqEEAAHBB30+PQb6fPkFiEIlBvCEyQTvffUG8ITJBQmBxQb6fPkEAAMBAAACoQRsABAAGAAAAAAICAgIDGgAAAAAAAAAQQQAA4EBKqSFBAADgQAAAMEFtrfxAAAAwQQAAEEEAADBBSqkhQUqpIUEAADBBAAAQQQAAMEFtrfxAAAAwQQAA4EBKqSFBAADgQAAAEEEAAOBAba38QG2t/EAAAOBAAAAQQQAA4EAwHgAAAAD//x4BAAAA//8eAgAAAP//HgMAAAD//x4EAAAA//8=',
  ),
  AppIconType.image: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAKAAAAAAECAQIBAgECAyIAAAAAAKBAAABAQAAAmEEAAEBApdSgQQAAQEAAAKhB2Vp5QAAAqEEAAKBAAACoQQAAmEEAAKhBpdSgQaXUoEEAAKhBAACYQQAAqEEAAKBAAACoQdlaeUAAAKhBAABAQKXUoEEAAEBAAACYQQAAQEAAAKBAAABAQNlaeUDZWnlAAABAQAAAoEAAAEBAGwABAAYAAAAAAgICAgMaAAAAAAAAABBBAADgQEqpIUEAAOBAAAAwQW2t/EAAADBBAAAQQQAAMEFKqSFBSqkhQQAAMEEAABBBAAAwQW2t/EAAADBBAADgQEqpIUEAAOBAAAAQQQAA4EBtrfxAba38QAAA4EAAABBBAADgQBsAAgAEAAAAAAECAQwAAAAAAKhBAABwQd9Pj0G+nz5BYhCJQbwhMkE7331BvCEyQUJgcUG+nz5BAADAQAAAqEEwHgAAAAD//x4BAAAA//8eAgAAAP//',
  ),
  AppIconType.logOut: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAADAAAAAAEBBgAAAAAAAAAAgEEAAIhBAACoQQAAQEEAAIBBAADgQBsAAQACAAAAAAEEAAAAAAAAAKhBAABAQQAAEEEAAEBBGwACAAYAAAAAAQIBAgEUAAAAAAAAABBBAACoQQAAoEAAAKhBvE55QAAAqEEAAEBAKdagQQAAQEAAAJhBAABAQAAAoEAAAEBAvE55QLxOeUAAAEBAAACgQAAAQEAAABBBAABAQDAeAAAAAP//HgEAAAD//x4CAAAA//8=',
  ),
  AppIconType.messageCircle: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAIBAgIBAgICAgI2AAAAAAAA7nw/QGq8gkEF5khADbSFQV7+SkBk9IhBBoFFQG8SjEEQWAFAWmSmQefB+T8XG6lB+vYDQE3qq0EeExRAddGtQUEvJECduK9BSQY7QFlysEGwclBAaryvQaRw1UCDwKdB+DThQCMrp0GWZO1AbGynQaab+EDufKhBFNdCQUf1uEGIbItBUqetQV6poUH6tI1BNOa3QUOFW0Fw6rNBoOMEQXs5mEG2W5xADRF5Qa7Auz8nWCJB3XyEP4f/xUDtQHdAf50OQLYh1kBwKWE/71c/Qe58P0BrvIJBMB4AAAAA//8=',
  ),
  AppIconType.paperclip: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAMAAAAAAECAgECAgECAgIBNAAAAAAAAACAQQAAwECDwPJAQmBpQd7A2UAV4HVB3sDZQAIShUGDwPJA7FGLQRTgBUHVkZFBBSQaQdWRkUHXoyZB7FGLQcuhlkGWQw1BDSGjQSOK6EANIaNBDn6XQMuhlkEMAktAiSKKQfsPzj8Hv2tB+w/OP4PAUkEMAktAQmCZQGiRO0E9bVBAm8BTQRmKKUBCQ3dBweBMQDlMjEFoN3BA0vacQessrEAg+6lBTdfuQPVlrkHYwBhBytCyQX5DPEFl9K1BsXJUQfypoUGJQa1BEoM6QTAeAAAAAP//',
  ),
  AppIconType.pencil: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAICAQIBAgIBAgMsAAAAAAAAWmSpQef72UBUMrJBX8K2QGQyskG+T3tAfmSpQQ3cNECZlqBBttDcP/lPkkEOw9w/BoGJQc3MNEBU43VAWmSBQUgHZ0B3PoNBDgpcQDaGhUFU41VAMQiIQRBYAUAX2apBvvL7P/BBrEHvEAFA28itQRxlCUDz0q5BSbkRQAvdr0Hn8R1AXD+wQUw3KUDy0q9BbeffQJZDpUHo7OlAhICkQakL80ABI6NByXb6QLpJoUEbAAEAAgAAAAABBAAAAAAAAABwQQAAoEAAAJhBAAAQQTAeAAAAAP//HgEAAAD//w==',
  ),
  AppIconType.plus: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAACgQAAAQEEAAJhBAABAQRsAAQACAAAAAAEEAAAAAAAAAEBBAACgQAAAQEEAAJhBMB4AAAAA//8eAQAAAP//',
  ),
  AppIconType.refreshCcw: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAEAAAAAAICARAAAAAAAAAAqEEAAEBBAACoQSbx4EC2w4dBAABAQAAAQEEAAEBARb4XQRSbQED/NOJANnB/QOxRqEAVrrdAAABAQAAAAEEbAAEAAwAAAAABAQYAAAAAAABAQAAAQEAAAEBAAAAAQQAAAEEAAABBGwACAAQAAAAAAgIBEAAAAAAAQEAAAEBBAABAQLbDh0Em8eBAAACoQQAAQEEAAKhBvEFoQZ7sp0HAcodB+RGgQYXrlUF7FJJBAACoQQAAgEEbAAMAAwAAAAABAQYAAAAAAACAQQAAgEEAAKhBAACAQQAAqEEAAKhBMB4AAAAA//8eAQAAAP//HgIAAAD//x4DAAAA//8=',
  ),
  AppIconType.refreshCw: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAEAAAAAAICARAAAAAAAAAAQEAAAEBBAABAQCbx4EAm8eBAAABAQAAAQEEAAEBAvEFoQRSbQEDAcodBNnB/QIXrlUEVrrdAAACoQQAAAEEbAAEAAwAAAAABAQYAAAAAAACoQQAAQEAAAKhBAAAAQQAAgEEAAABBGwACAAQAAAAAAgIBEAAAAAAAqEEAAEBBAACoQbbDh0G2w4dBAACoQQAAQEEAAKhBRb4XQZ7sp0H/NOJA+RGgQexRqEB7FJJBAABAQAAAgEEbAAMAAwAAAAABAQYAAAAAAAAAQQAAgEEAAEBAAACAQQAAQEAAAKhBMB4AAAAA//8eAQAAAP//HgIAAAD//x4DAAAA//8=',
  ),
  AppIconType.repeat: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAADAAAAAAEBBgAAAAAAAAAAiEEAAABAAACoQQAAwEAAAIhBAAAgQRsAAQAEAAAAAAECAQwAAAAAAEBAAAAwQQAAQEAAACBBAABAQLxO+UC8TplAAADAQAAA4EAAAMBAAACoQQAAwEAbAAIAAwAAAAABAQYAAAAAAADgQAAAsEEAAEBAAACQQQAA4EAAAGBBGwADAAQAAAAAAQIBDAAAAAAAqEEAAFBBAACoQQAAYEEAAKhBUayBQVGsmUEAAJBBAACIQQAAkEEAAEBAAACQQTAeAAAAAP//HgEAAAD//x4CAAAA//8eAwAAAP//',
  ),
  AppIconType.search: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAACoQQAAqEGuR4VBrkeFQRsAAQAGAAAAAAICAgIDGgAAAAAAAAAwQQAAQEAnpXZBAABAQAAAmEGytdJAAACYQQAAMEEAAJhBJ6V2QSeldkEAAJhBAAAwQQAAmEGytdJAAACYQQAAQEAnpXZBAABAQAAAMEEAAEBAsrXSQLK10kAAAEBAAAAwQQAAQEAwHgAAAAD//x4BAAAA//8=',
  ),
  AppIconType.send: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAMAAAAAAICAQICAQICAQIDMgAAAAAAdZNoQe58rUEl0mlBDQqvQRXdbEE5CrBBmTRwQUT/r0EcjHNBT/SvQcx7dkGJ4K5BaJF3QcdLrUG0yK9BNV4qQIJOsEGdyh5AGvKvQVrXEUCX265BRCMJQBXFrUEvbwBArCasQeAX+z85tKpBXroBQMuhFUCYbghBu/sIQDSECUGIXQBA5HMMQeEFAEBnyw9BdFz/P+siE0GcrwdA2y0WQZMYFECLbBdBbecjQdNNSkFTAixBjoxNQbdvMkH89lNBLbI1QWIQXEEbAAEAAgAAAAABBAAAAAAA/tSuQXNoCUC+ny5BQmBRQTAeAAAAAP//HgEAAAD//w==',
  ),
  AppIconType.settings: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAZAAAAAAICAgICAgICAgICAgICAgICAgICAgICApIAAAAAarwaQR1ahEASkBxBfNQ7QPCzLEGDHQFADAJAQYMdAUAoUFNBgx0BQAZ0Y0F81DtArkdlQRxahED4WmZBjKucQGJKbUG6abJACN13QRmdvkDXN4FBd9DKQNmoh0HU8MtAJzGNQcqhwUBE9pVBkrSxQG1SoEEO/75A4COlQfda4EBS9alBcNsAQXipp0FpIBZB/tSfQRBYIUFu1ppBUFooQUfdl0EkyjNBR92XQfP9P0FH3ZdBwzFMQW7WmkGXoVdB/tSfQdejXkF4qadBfttpQVL1qUF3IH9B4COlQTbnh0FtUqBBMD6QQUT2lUHPkJNBJzGNQYGVj0HZqIdBvgGNQdc3gUHWSY1BCN13Qa1WkEFiSm1BhWOTQfhaZkEQ05hBrkdlQWznnkEGdGNBZIOoQShQU0FD2q9BDAJAQUPar0HwsyxBQ9qvQRKQHEFkg6hBarwaQWznnkGgqRlBftKYQZ25EkFjYpNB0SUIQXNVkEEKJPtAgkiNQWRd4UDfAI1BZDvLQIGVj0HuJqhAz5CTQZhsfUAwPpBBAeFWQDbnh0FqVTBAdyB/QUC0QkB+22lBCKyAQNejXkFFppRAl6FXQeOKoEDDMUxB44qgQPP9P0HjiqBAJMozQUWmlEBQWihBCKyAQBBYIUGiy0JAHx8WQS55MEAG3wBBmPlWQCVo4EACen1APhK/QNUgqEBTw7FAMzPLQMqhwUBqVOFA1PDLQHIY+0B30MpA3x4IQRmdvkCEsRJBummyQO+gGUGMq5xAObQaQRxahEAbAAEABgAAAAACAgICAxoAAAAAAAAAQEEAABBB731aQQAAEEEAAHBBEYIlQQAAcEEAAEBBAABwQe99WkHvfVpBAABwQQAAQEEAAHBBEYIlQQAAcEEAABBB731aQQAAEEEAAEBBAAAQQRGCJUERgiVBAAAQQQAAQEEAABBBMB4AAAAA//8eAQAAAP//',
  ),
  AppIconType.share: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAABAQQAAAEAAAEBBAABwQRsAAQADAAAAAAEBBgAAAAAAAIBBAADAQAAAQEEAAABAAAAAQQAAwEAbAAIABgAAAAABAgECARQAAAAAAAAAgEAAAEBBAACAQAAAoEEAAIBAKdaoQV6nnEAAALBBAADAQAAAsEEAAJBBAACwQSnWmEEAALBBAACgQSnWqEEAAKBBAACgQQAAoEEAAEBBMB4AAAAA//8eAQAAAP//HgIAAAD//w==',
  ),
  AppIconType.shield: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAALAAAAAAICAgECAgICAgM0AAAAAAAAAACgQQAAUEEAAKBBAACQQQAAhEEAAKRBpHBFQZqZr0Fh9EFBxzCwQSkrPkGMKbBBUrg6QR+Fr0EAAPBAAACkQQAAgEAAAJBBAACAQAAAUEEAAIBAAADAQAAAgECvU65Ar1OOQAAAoEAAAKBAAACgQAAA4EAAAKBAAAAYQTMzc0AK1zNBhesRQMDXOkED+vM/PyhFQQP68z/1KExBhesRQPYoaEEK13NAAACIQQAAoEAAAJhBAACgQBRrnEEAAKBAAACgQa9TrkAAAKBBAADAQDAeAAAAAP//',
  ),
  AppIconType.squareCheck: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAKAAAAAAECAQIBAgECAyIAAAAAAKBAAABAQAAAmEEAAEBApdSgQQAAQEAAAKhB2Vp5QAAAqEEAAKBAAACoQQAAmEEAAKhBpdSgQaXUoEEAAKhBAACYQQAAqEEAAKBAAACoQdlaeUAAAKhBAABAQKXUoEEAAEBAAACYQQAAQEAAAKBAAABAQNlaeUDZWnlAAABAQAAAoEAAAEBAGwABAAMAAAAAAQEGAAAAAAAAEEEAAEBBAAAwQQAAYEEAAHBBAAAgQTAeAAAAAP//HgEAAAD//w==',
  ),
  AppIconType.square: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAKAAAAAAECAQIBAgECAyIAAAAAAKBAAABAQAAAmEEAAEBApdSgQQAAQEAAAKhB2Vp5QAAAqEEAAKBAAACoQQAAmEEAAKhBpdSgQaXUoEEAAKhBAACYQQAAqEEAAKBAAACoQdlaeUAAAKhBAABAQKXUoEEAAEBAAACYQQAAQEAAAKBAAABAQNlaeUDZWnlAAABAQAAAoEAAAEBAMB4AAAAA//8=',
  ),
  AppIconType.trash: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAGAAAAAAECAQIBFAAAAAAAmEEAAMBAAACYQQAAoEEAAJhBKdaoQSnWkEEAALBBAACIQQAAsEEAAOBAAACwQV6nvEAAALBBAACgQCnWqEEAAKBAAACgQQAAoEAAAMBAGwABAAIAAAAAAQQAAAAAAAAAQEAAAMBAAACoQQAAwEAbAAIABgAAAAABAgECARQAAAAAAAAAAEEAAMBAAAAAQQAAgEAAAABBvE45QK9TDkEAAABAAAAgQQAAAEAAAGBBAAAAQFGscUEAAABAAACAQbxOOUAAAIBBAACAQAAAgEEAAMBAMB4AAAAA//8eAQAAAP//HgIAAAD//w==',
  ),
  AppIconType.upload: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAABAQQAAQEAAAEBBAABwQRsAAQADAAAAAAEBBgAAAAAAAIhBAAAAQQAAQEEAAEBAAADgQAAAAEEbAAIABgAAAAABAgECARQAAAAAAAAAqEEAAHBBAACoQQAAmEEAAKhBKdagQSnWoEEAAKhBAACYQQAAqEEAAKBAAACoQbxOeUAAAKhBAABAQCnWoEEAAEBAAACYQQAAQEAAAHBBMB4AAAAA//8eAQAAAP//HgIAAAD//w==',
  ),
  AppIconType.user: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAAGAAAAAAECAQIBFAAAAAAAmEEAAKhBAACYQQAAmEEAAJhBr1OGQVGsiUEAAHBBAABwQQAAcEEAABBBAABwQbxO2UAAAHBBAACgQK9ThkEAAKBAAACYQQAAoEAAAKhBGwABAAYAAAAAAgICAgMaAAAAAAAAAEBBAABAQJNSY0EAAEBAAACAQdlamUAAAIBBAADgQAAAgEGTUhNBk1JjQQAAMEEAAEBBAAAwQW2tHEEAADBBAAAAQZNSE0EAAABBAADgQAAAAEHZWplAba0cQQAAQEAAAEBBAABAQDAeAAAAAP//HgEAAAD//w==',
  ),
  AppIconType.users: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEcHh4f8gMAAP//GwAAADwAAAAAAQICAQECAgECAgECAgECAgECAgMAAQECAgICAgIBAgIDAAICAgIDAAICAgICAgICAgICAgMAAgICAgMOAQAAAAByQQAAqEEAAHJBAACYQQAAckGeXpFBarxsQUECi0EpXGNB7FGGQdGRWkH07IFBCtdOQUOtfkEcfEJB+Q9+QQAAQEEAAH5BAADAQAAAfkF4eqVAAAB+Qe4IjEDLoYFBBJByQOxRhkEsDk1AQQKLQQAAOECeXpFBAAA4QAAAmEEAADhAAACoQQAAOECY3atBke0eQAAAr0EAAABAAACvQd0kwj8AAK9BAACQP5jdq0EAAJA/AACoQQAAkD8AAJhBAACQPySojUEKutE/aryDQe5fI0Dc13hB1uJdQEw3akFRoJZAAABiQQAAwEAAAGJBAABAQQAAYkG4r1RBAABiQSuHaEFMN2pBJCh3QdzXeEFa5IJBaryDQQAAh0EkqI1BAACHQQAAmEEAAIdBAACoQQAAh0GY3atBmN2DQQAAr0EAAIBBAACvQdBEeEEAAK9BAAByQZjdq0EAAHJBAACoQQAAqUEAAKhBAACpQQwCmEEW6qhBB/CVQRKDqEE6I5FB9bmmQaaKjEHywaNBEbaIQS9doEFnVYRB4JybQW40gUHmP5ZB16N/QaOBkkELtX1Bg0CQQWIQdkHpN5FB3pNuQYMvkkFZF2dBowGWQTGZYkEawJlB/YdkQecdokFR2mhBwoapQT2bckHs0a5B/yGAQRUdtEEr9oZBKP62QR1aj0EAALdB9P2XQQAAt0EAAKhBAAC3QZjdq0GY3bNBAACvQQAAsEEAAK9BaCKsQQAAr0EAAKlBmN2rQQAAqUEAAKhBAABCQQAA4EAAAEJBgsWoQEmdK0EAAHhAAAAQQQAAeECCxehAAAB4QAAAvECCxahAAAC8QAAA4EAAALxAP50LQYLF6EAAACJBAAAQQQAAIkFJnStBAAAiQQAAQkE/nQtBAABCQQAA4EAD+JBBAADgQAP4kEHT2clAYiGPQbVUtEAOvotB/8+iQFFaiEHgSpFAa5qDQTS/hEAcfHxBA2B+QGkAdUF8m3ZAe4NwQekOWEDrc3JB8x86QCxldEGgMhxAMQh8QXE9CkDywYFBAAASQLgeikGOWCNAjoaRQbZnSkAU0JZB/YeAQJoZnEHG3JtAA/ieQQ1xvUAD+J5BAADgQAP4nkF6RwFBmhmcQZ0REkEU0JZBArwfQY6GkUH+ZS1BuB6KQccpN0HywYFBNIA7QTEIfEGkcD1BLGV0QU3zOEHrc3JBA3gxQXuDcEFQ/ClBaQB1QUtZIkEcfHxBCmggQWuag0FmoB1BUVqIQZBaF0EOvotBAZgOQWIhj0Gm1QVBA/iQQS0m9kAD+JBBAADgQAAAXkEAAOBAAABeQQgUG0ESFDtBAAA+QQAAEEEAAD5B8dfJQAAAPkEAAIRACBQbQQAAhEAAAOBAAACEQPHXiUDx18lAAAAIQAAAEEEAAAhAEhQ7QQAACEAAAF5B8deJQAAAXkEAAOBAMB4AAAAA//8=',
  ),
  AppIconType.x: const _InlineBytesLoader(
    'Yi2IAAEpAADAQQAAwEEdAAAA/wEBAwAAgEAAAOA/AAD//xsAAAACAAAAAAEEAAAAAACQQQAAwEAAAMBAAACQQRsAAQACAAAAAAEEAAAAAAAAAMBAAADAQAAAkEEAAJBBMB4AAAAA//8eAQAAAP//',
  ),
};

BytesLoader compiledSvgLoader(AppIconType icon) => _compiledSvgLoaders[icon]!;

class AppIcon extends StatelessWidget {
  const AppIcon({
    super.key,
    required this.type,
    this.size,
    this.color,
    this.fit = BoxFit.contain,
    this.alignment = Alignment.center,
  });

  const AppIcon.arrowLeft({super.key, this.size, this.color})
    : type = AppIconType.arrowLeft,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.arrowRight({super.key, this.size, this.color})
    : type = AppIconType.arrowRight,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.arrowUp({super.key, this.size, this.color})
    : type = AppIconType.arrowUp,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.ban({super.key, this.size, this.color})
    : type = AppIconType.ban,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.camera({super.key, this.size, this.color})
    : type = AppIconType.camera,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.checkCheckFill({super.key, this.size, this.color})
    : type = AppIconType.checkCheckFill,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.checkCheck({super.key, this.size, this.color})
    : type = AppIconType.checkCheck,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.check({super.key, this.size, this.color})
    : type = AppIconType.check,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.circleAlert({super.key, this.size, this.color})
    : type = AppIconType.circleAlert,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.circleDashed({super.key, this.size, this.color})
    : type = AppIconType.circleDashed,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.copy({super.key, this.size, this.color})
    : type = AppIconType.copy,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.download({super.key, this.size, this.color})
    : type = AppIconType.download,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.fileDown({super.key, this.size, this.color})
    : type = AppIconType.fileDown,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.fileText({super.key, this.size, this.color})
    : type = AppIconType.fileText,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.fileUp({super.key, this.size, this.color})
    : type = AppIconType.fileUp,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.globe({super.key, this.size, this.color})
    : type = AppIconType.globe,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.imageOff({super.key, this.size, this.color})
    : type = AppIconType.imageOff,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.imagePlus({super.key, this.size, this.color})
    : type = AppIconType.imagePlus,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.image({super.key, this.size, this.color})
    : type = AppIconType.image,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.logOut({super.key, this.size, this.color})
    : type = AppIconType.logOut,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.messageCircle({super.key, this.size, this.color})
    : type = AppIconType.messageCircle,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.paperclip({super.key, this.size, this.color})
    : type = AppIconType.paperclip,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.pencil({super.key, this.size, this.color})
    : type = AppIconType.pencil,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.plus({super.key, this.size, this.color})
    : type = AppIconType.plus,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.refreshCcw({super.key, this.size, this.color})
    : type = AppIconType.refreshCcw,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.refreshCw({super.key, this.size, this.color})
    : type = AppIconType.refreshCw,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.repeat({super.key, this.size, this.color})
    : type = AppIconType.repeat,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.search({super.key, this.size, this.color})
    : type = AppIconType.search,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.send({super.key, this.size, this.color})
    : type = AppIconType.send,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.settings({super.key, this.size, this.color})
    : type = AppIconType.settings,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.share({super.key, this.size, this.color})
    : type = AppIconType.share,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.shield({super.key, this.size, this.color})
    : type = AppIconType.shield,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.squareCheck({super.key, this.size, this.color})
    : type = AppIconType.squareCheck,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.square({super.key, this.size, this.color})
    : type = AppIconType.square,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.trash({super.key, this.size, this.color})
    : type = AppIconType.trash,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.upload({super.key, this.size, this.color})
    : type = AppIconType.upload,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.user({super.key, this.size, this.color})
    : type = AppIconType.user,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.users({super.key, this.size, this.color})
    : type = AppIconType.users,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  const AppIcon.x({super.key, this.size, this.color})
    : type = AppIconType.x,
      fit = BoxFit.contain,
      alignment = Alignment.center;

  final AppIconType type;
  final double? size;
  final Color? color;
  final BoxFit fit;
  final Alignment alignment;

  @override
  Widget build(BuildContext context) {
    final color = this.color ?? CustomColorScheme.of(context).text.primary;
    return createCompatVectorGraphic(
      loader: compiledSvgLoader(type),
      width: size,
      height: size,
      fit: fit,
      alignment: alignment,
      colorFilter: ColorFilter.mode(color, BlendMode.srcIn),
    );
  }
}

class _InlineBytesLoader extends BytesLoader {
  const _InlineBytesLoader(this.base64Data);
  final String base64Data;
  @override
  Future<ByteData> loadBytes(BuildContext? context) {
    final bytes = base64Decode(base64Data);
    return SynchronousFuture(ByteData.sublistView(bytes));
  }

  @override
  Object cacheKey(BuildContext? context) => this;
}
