// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'markdown.dart';
import 'message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'types.dart';
import 'user_cubit.dart';

// These functions are ignored because they are not marked as `pub`: `affected`, `contains`, `initial_load`, `is_empty`, `load_chats`, `of`, `record`, `reload`, `remove`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ChatKeys`, `ChatsPublisherInner`, `LocalState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ChatsPublisher>>
abstract class ChatsPublisher implements RustOpaqueInterface {
  Future<void> close();

  Future<AddUsernameContactError?> createContactChat({
    required UiUsername username,
    required UsernameHash hash,
  });

  Future<ChatId> createGroupChat({
    required String groupName,
    Uint8List? picture,
    required bool isApq,
  });

  Future<void> mute({required ChatId chatId, UiChatMuted? mutedUntil});

  factory ChatsPublisher({required UserCubitBase userCubit}) => RustLib
      .instance
      .api
      .crateApiChatPublisherChatsPublisherNew(userCubit: userCubit);

  /// Long running task
  ///
  /// One delta carrying every chat and the full order, then one delta per database change.
  /// Returns when cancelled.
  Stream<ChatsDelta> stream();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UsernameHash>>
abstract class UsernameHash implements RustOpaqueInterface {}

/// A delta [`ChatsPublisher`] emits in its stream.
class ChatsDelta {
  final List<UiChatDetails> upserted;
  final Set<ChatId> removed;

  /// Only when ordering of chats changed.
  final List<ChatId>? order;

  const ChatsDelta({required this.upserted, required this.removed, this.order});

  @override
  int get hashCode => upserted.hashCode ^ removed.hashCode ^ order.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatsDelta &&
          runtimeType == other.runtimeType &&
          upserted == other.upserted &&
          removed == other.removed &&
          order == other.order;
}
