// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `highlight_code_block`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `hash`, `hash`, `hash`, `hash`

class HighlightColor {
  final int r;
  final int g;
  final int b;
  final int a;

  const HighlightColor({
    required this.r,
    required this.g,
    required this.b,
    required this.a,
  });

  @override
  int get hashCode => r.hashCode ^ g.hashCode ^ b.hashCode ^ a.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightColor &&
          runtimeType == other.runtimeType &&
          r == other.r &&
          g == other.g &&
          b == other.b &&
          a == other.a;
}

class HighlightFontStyle {
  final int bits;

  const HighlightFontStyle({required this.bits});

  @override
  int get hashCode => bits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightFontStyle &&
          runtimeType == other.runtimeType &&
          bits == other.bits;
}

class HighlightRange {
  final int start;
  final int end;
  final HighlightStyle style;

  const HighlightRange({
    required this.start,
    required this.end,
    required this.style,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightRange &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          style == other.style;
}

class HighlightStyle {
  final HighlightColor? fg;
  final HighlightColor? bg;
  final HighlightFontStyle? style;

  const HighlightStyle({this.fg, this.bg, this.style});

  @override
  int get hashCode => fg.hashCode ^ bg.hashCode ^ style.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HighlightStyle &&
          runtimeType == other.runtimeType &&
          fg == other.fg &&
          bg == other.bg &&
          style == other.style;
}
