// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user_cubit.dart';
part 'invitation_codes_cubit.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `load_and_emit_state`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<InvitationCodesCubitBase>>
abstract class InvitationCodesCubitBase implements RustOpaqueInterface {
  Future<void> close();

  bool get isClosed;

  Future<void> markInvitationCodeAsCopied({required String code});

  factory InvitationCodesCubitBase({required UserCubitBase userCubit}) =>
      RustLib.instance.api
          .crateApiInvitationCodesCubitInvitationCodesCubitBaseNew(
            userCubit: userCubit,
          );

  Future<RequestInvitationCodeError?> requestInvitationCode();

  InvitationCodesState get state;

  Stream<InvitationCodesState> stream();
}

/// Mirror of the [`InvitationCode`] type
@freezed
sealed class InvitationCode with _$InvitationCode {
  const factory InvitationCode({required String code, required bool copied}) =
      _InvitationCode;
}

@freezed
sealed class InvitationCodesState with _$InvitationCodesState {
  const InvitationCodesState._();
  const factory InvitationCodesState({required List<InvitationCode> codes}) =
      _InvitationCodesState;
  static Future<InvitationCodesState> default_() => RustLib.instance.api
      .crateApiInvitationCodesCubitInvitationCodesStateDefault();
}

enum RequestInvitationCodeError { userQuotaExceeded, globalQuotaExceeded }
