// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'user_cubit.dart';
part 'linked_devices_cubit.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `devices_listener`, `load_and_emit`, `try_load`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LinkedDevicesCubitBase>>
abstract class LinkedDevicesCubitBase implements RustOpaqueInterface {
  Future<void> close();

  bool get isClosed;

  factory LinkedDevicesCubitBase({required UserCubitBase userCubit}) =>
      RustLib.instance.api.crateApiLinkedDevicesCubitLinkedDevicesCubitBaseNew(
        userCubit: userCubit,
      );

  Future<void> renameDevice({
    required UuidValue clientId,
    required String name,
  });

  LinkedDevicesState get state;

  Stream<LinkedDevicesState> stream();

  Future<void> unlinkDevice({required UuidValue clientId});
}

enum LinkedDevicePlatform { unknown, android, ios, macos, windows, linux }

@freezed
sealed class LinkedDevicesState with _$LinkedDevicesState {
  const LinkedDevicesState._();
  const factory LinkedDevicesState({required List<UiLinkedDevice> devices}) =
      _LinkedDevicesState;
  static Future<LinkedDevicesState> default_() => RustLib.instance.api
      .crateApiLinkedDevicesCubitLinkedDevicesStateDefault();
}

/// One row in the Linked Devices screen.
///
/// An empty `name` means the device has no metadata entry yet. The Dart side
/// substitutes a localized fallback, since localization lives in Flutter.
@freezed
sealed class UiLinkedDevice with _$UiLinkedDevice {
  const factory UiLinkedDevice({
    required UuidValue clientId,
    required String name,
    required LinkedDevicePlatform platform,
    DateTime? linkedAt,
    required bool isThisDevice,
  }) = _UiLinkedDevice;
}
