// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'markdown.dart';
import 'message_content.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'types.dart';
import 'user_cubit.dart';
part 'message_list_cubit.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `apply_messages`, `clear_first_unread_index`, `compute_flight_positions`, `handle_jump_to_bottom`, `handle_jump_to_message`, `handle_load_newer`, `handle_load_older`, `initial_load`, `load_bottom`, `load_is_connection_chat`, `new`, `notify_message_neighbors`, `process_store_notification`, `recompute_flight_positions_range`, `reload_current_window`, `run_loop`, `spawn`, `try_process_store_notification`, `update_message_in_place`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `Command`, `LoadDirection`, `MessageListContext`, `MessageListStateInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageListCubitBase>>
abstract class MessageListCubitBase implements RustOpaqueInterface {
  Future<void> close();

  bool get isClosed;

  /// Jump to the most recent messages.
  Future<void> jumpToBottom();

  /// Jump to a specific message (loads a window around it if not in view).
  Future<void> jumpToMessage({required MessageId messageId});

  /// Request loading of newer messages (append to window).
  Future<void> loadNewer();

  /// Request loading of older messages (prepend to window).
  Future<void> loadOlder();

  factory MessageListCubitBase({
    required UserCubitBase userCubit,
    required ChatId chatId,
  }) => RustLib.instance.api.crateApiMessageListCubitMessageListCubitBaseNew(
    userCubit: userCubit,
    chatId: chatId,
  );

  MessageListState get state;

  Stream<MessageListState> stream();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageListState>>
abstract class MessageListState implements RustOpaqueInterface {
  static Future<MessageListState> default_() =>
      RustLib.instance.api.crateApiMessageListCubitMessageListStateDefault();

  bool isNewMessage(MessageId messageId);

  /// The number of loaded messages in the list
  ///
  /// Note that this is not the number of all messages in the chat.
  int get loadedMessagesCount;

  /// Returns the message at the given index.
  UiChatMessage? messageAt(int index);

  /// Returns the lookup table mapping a message id to the index in the list.
  int? messageIdIndex(MessageId messageId);

  MessageListMeta get meta;
}

/// Attributes of the message list state.
@freezed
sealed class MessageListMeta with _$MessageListMeta {
  const MessageListMeta._();
  const factory MessageListMeta({
    bool? isConnectionChat,
    required bool hasOlder,
    required bool hasNewer,
    required bool isAtBottom,
    int? scrollToIndex,
    int? firstUnreadIndex,
  }) = _MessageListMeta;
  static Future<MessageListMeta> default_() =>
      RustLib.instance.api.crateApiMessageListCubitMessageListMetaDefault();
}
