// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user_cubit.dart';
part 'multi_device.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `linking_code_from_url`, `multi_device_linking_url`, `take_receiver`

/// Runs a multi-device provisioning session on a fresh device.
///
/// Connects to the relay at `domain`, emits the linking [`MultiDeviceProvisionEvent::Code`] as soon
/// as the relay assigns it, and keeps the session alive until the existing device links or the
/// session fails.
Stream<MultiDeviceProvisionEvent> multiDeviceProvisionClient({
  required String domain,
}) => RustLib.instance.api.crateApiMultiDeviceMultiDeviceProvisionClient(
  domain: domain,
);

/// Drives the acceptor (existing-device) side of multi-device linking.
///
/// `session_id` is the linking code that the existing device scanned from (or typed in from) the
/// fresh device. Connects to the relay, emits [`MultiDeviceLinkEvent::AwaitingConfirmation`] once
/// connected, then waits for the user to approve via [`MultiDeviceLinkConfirmation::confirm`] before
/// admitting the new device into a fresh MLS group and completing the handshake.
Stream<MultiDeviceLinkEvent> multiDeviceLinkClient({
  required UserCubitBase userCubit,
  required String sessionId,
  required MultiDeviceLinkConfirmation confirmation,
}) => RustLib.instance.api.crateApiMultiDeviceMultiDeviceLinkClient(
  userCubit: userCubit,
  sessionId: sessionId,
  confirmation: confirmation,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MultiDeviceLinkConfirmation>>
abstract class MultiDeviceLinkConfirmation implements RustOpaqueInterface {
  /// Approves the link, unblocking the linking task. A no-op if already confirmed.
  void confirm();

  factory MultiDeviceLinkConfirmation() =>
      RustLib.instance.api.crateApiMultiDeviceMultiDeviceLinkConfirmationNew();
}

@freezed
sealed class MultiDeviceLinkEvent with _$MultiDeviceLinkEvent {
  const MultiDeviceLinkEvent._();

  /// Connected to the relay; waiting for the user to approve on this device via
  /// [`MultiDeviceLinkConfirmation::confirm`].
  const factory MultiDeviceLinkEvent.awaitingConfirmation() =
      MultiDeviceLinkEvent_AwaitingConfirmation;

  /// Linking completed successfully.
  const factory MultiDeviceLinkEvent.linked(String field0) =
      MultiDeviceLinkEvent_Linked;

  /// Linking failed (e.g. the connection dropped or the session expired).
  const factory MultiDeviceLinkEvent.failed(String field0) =
      MultiDeviceLinkEvent_Failed;
}

@freezed
sealed class MultiDeviceProvisionEvent with _$MultiDeviceProvisionEvent {
  const MultiDeviceProvisionEvent._();

  /// The relay assigned a linking code. Display it so the user can enter it on their existing
  /// device.
  const factory MultiDeviceProvisionEvent.code({
    String? qrcodeSvg,
    required String code,
  }) = MultiDeviceProvisionEvent_Code;

  /// The existing device has established the session and the linking process is underway.
  const factory MultiDeviceProvisionEvent.linking() =
      MultiDeviceProvisionEvent_Linking;

  /// The existing device connected and linking completed successfully.
  const factory MultiDeviceProvisionEvent.linked(String field0) =
      MultiDeviceProvisionEvent_Linked;

  /// The session ended without linking (e.g. it timed out or the connection dropped).
  const factory MultiDeviceProvisionEvent.failed(String field0) =
      MultiDeviceProvisionEvent_Failed;
}
