// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'notifications.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'types.dart';
part 'notification_context.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `subscribe`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NotificationContextBase>>
abstract class NotificationContextBase implements RustOpaqueInterface {
  /// Clears the notifications a chat has already posted, for when it opens.
  Future<void> chatOpened({required ChatId chatId});

  factory NotificationContextBase({
    required DartNotificationService notificationService,
  }) => RustLib.instance.api
      .crateApiNotificationContextNotificationContextBaseNew(
        notificationService: notificationService,
      );

  /// Records the policy the UI moved to.
  void setPolicy({required NotificationPolicy policy});
}

@freezed
sealed class NotificationPolicy with _$NotificationPolicy {
  const NotificationPolicy._();

  /// Do not show any notifications
  const factory NotificationPolicy.suppressAll() =
      NotificationPolicy_SuppressAll;

  /// Show all notifications.
  const factory NotificationPolicy.allowAll() = NotificationPolicy_AllowAll;

  /// Show all notifications, except for those from the given chat.
  const factory NotificationPolicy.suppressChat({required ChatId chatId}) =
      NotificationPolicy_SuppressChat;

  static Future<NotificationPolicy> default_() => RustLib.instance.api
      .crateApiNotificationContextNotificationPolicyDefault();
}
