// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:uuid/uuid.dart';
import 'user.dart';
part 'registration.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `from_anyhow`

/// Asks a server whether signing up with it needs a challenge right now.
Future<RegistrationInfo> getRegistrationInfo({required String domain}) =>
    RustLib.instance.api.crateApiRegistrationGetRegistrationInfo(
      domain: domain,
    );

/// Asks the server to send a challenge to this device's push endpoint.
Future<NewAdmissionSession> createAdmissionSession({
  required String domain,
  required PlatformPushToken pushToken,
}) => RustLib.instance.api.crateApiRegistrationCreateAdmissionSession(
  domain: domain,
  pushToken: pushToken,
);

class AdmissionSession {
  final UuidValue sessionId;
  final String challenge;

  const AdmissionSession({required this.sessionId, required this.challenge});

  @override
  int get hashCode => sessionId.hashCode ^ challenge.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdmissionSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          challenge == other.challenge;
}

enum ChallengeKind { invitationCode, admissionSession }

@freezed
sealed class CreateUserError with _$CreateUserError implements FrbException {
  const CreateUserError._();

  /// The server wants one of these kinds of challenge answered first.
  const factory CreateUserError.challengeRequired({
    required List<ChallengeKind> accepted,
  }) = CreateUserError_ChallengeRequired;

  /// The server turned down the challenge response.
  const factory CreateUserError.challengeRejected() =
      CreateUserError_ChallengeRejected;

  /// Anything else, carrying the message for the log and the banner.
  const factory CreateUserError.other({required String message}) =
      CreateUserError_Other;
}

class NewAdmissionSession {
  final UuidValue sessionId;
  final Duration lifetime;

  const NewAdmissionSession({required this.sessionId, required this.lifetime});

  @override
  int get hashCode => sessionId.hashCode ^ lifetime.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NewAdmissionSession &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          lifetime == other.lifetime;
}

@freezed
sealed class RegistrationChallenge with _$RegistrationChallenge {
  const RegistrationChallenge._();

  const factory RegistrationChallenge.invitationCode(String field0) =
      RegistrationChallenge_InvitationCode;
  const factory RegistrationChallenge.admissionSession(
    AdmissionSession field0,
  ) = RegistrationChallenge_AdmissionSession;
}

@freezed
sealed class RegistrationInfo with _$RegistrationInfo {
  const factory RegistrationInfo({
    required bool challengeRequired,
    required List<ChallengeKind> acceptedChallenges,
  }) = _RegistrationInfo;
}
