// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0-beta.6.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'user.dart';
part 'user_settings_cubit.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `f64_decode`, `f64_encode`, `reload_read_receipts`, `settings_listener`, `subscribe`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DefaultEmojiSkinToneSetting`, `InterfaceScaleSetting`, `LocaleSetting`, `SendOnEnterSetting`, `SidebarWidthSetting`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `decode`, `decode`, `decode`, `decode`, `decode`, `encode`, `encode`, `encode`, `encode`, `encode`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `default`

/// Loads the persisted user settings. Missing rows keep the defaults.
Future<UserSettings> loadUserSettings({required User user}) =>
    RustLib.instance.api.crateApiUserSettingsCubitLoadUserSettings(user: user);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UserSettingsCubitBase>>
abstract class UserSettingsCubitBase implements RustOpaqueInterface {
  Future<void> close();

  bool get isClosed;

  /// Creates a cubit for `user` starting from the `initial` settings.
  ///
  /// Callers load `initial` with [`load_user_settings`]. Synced settings are
  /// re-read in the background, see [`settings_listener`].
  factory UserSettingsCubitBase({
    required User user,
    required UserSettings initial,
  }) => RustLib.instance.api.crateApiUserSettingsCubitUserSettingsCubitBaseNew(
    user: user,
    initial: initial,
  );

  Future<void> setDefaultEmojiSkinTone({required int value});

  Future<void> setDeveloperMode({required bool value});

  Future<void> setExperimentalFeatures({required bool value});

  Future<void> setInterfaceScale({required double value});

  Future<void> setLocale({required String value});

  Future<void> setReadReceipts({required bool value});

  Future<void> setSendOnEnter({required bool value});

  Future<void> setSidebarWidth({required double value});

  UserSettings get state;

  Stream<UserSettings> stream();
}

@freezed
sealed class UserSettings with _$UserSettings {
  const factory UserSettings({
    String? locale,
    double? interfaceScale,
    @Default(240.0) double sidebarWidth,
    @Default(false) bool sendOnEnter,
    @Default(true) bool readReceipts,
    @Default(false) bool developerMode,
    @Default(false) bool experimentalFeatures,
    @Default(0) int defaultEmojiSkinTone,
  }) = _UserSettings;
}
