// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unreachable_switch_default, prefer_const_constructors, camel_case_types
import 'package:convert/convert.dart';

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// Delete all databases of this client.
Future<void> deleteDatabases({required String dbPath}) =>
    RustLib.instance.api.crateApiUtilsDeleteDatabases(dbPath: dbPath);

/// Tears down a device that another device unlinked: stops the background work
/// that writes to the database, then deletes it.
Future<void> deleteClientDatabase({
  required User user,
  required String dbPath,
  required UuidValue clientRecordId,
}) => RustLib.instance.api.crateApiUtilsDeleteClientDatabase(
  user: user,
  dbPath: dbPath,
  clientRecordId: clientRecordId,
);

/// Returns whether the file at the given path is a recognized image format.
/// Uses the same detection as `load_attachment_image()`.
Future<bool> isImageFile({required String path}) =>
    RustLib.instance.api.crateApiUtilsIsImageFile(path: path);

/// Reads file paths from the system clipboard. Only supported on desktop
/// platforms (Linux, Windows, macOS).
///
/// Returns `None` if the clipboard does not contain file paths, or when called
/// on unsupported platforms.
Future<List<String>?> readClipboardFilePaths() =>
    RustLib.instance.api.crateApiUtilsReadClipboardFilePaths();

/// Reads an image from the system clipboard and returns it as PNG bytes. Only
/// supported on desktop platforms (Linux, Windows, macOS).
///
/// Returns `None` if the clipboard does not contain image data, or when called
/// on unsupported platforms.
Future<Uint8List?> readClipboardImage() =>
    RustLib.instance.api.crateApiUtilsReadClipboardImage();
