[package]
name = "notifications"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
jni = "0.21.1"
tokio = { version = "1.44.1", features = ["rt", "sync"] }
tracing = "0.1.41"

[build-dependencies]
swift-rs = { version = "1.0.7", features = ["build"] }
