# SPDX-FileCopyrightText: 2024 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish Android app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths:
      - "coreclient/**"
      - "apiclient/**"
      - "applogic/**"
      - "common/**"
      - "app/**"
      - "Cargo.toml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SQLX_OFFLINE: true

jobs:
  android-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all commit metadata (build number is derived from number of commits)
          fetch-depth: 0
          # Don't download historical file contents (blobs)
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          fastlane: true
          jdk: true
          cargo-binstall-tools: cargo-ndk

      - name: Build and upload to Play Store
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_PLAYSTORE_KEY_JSON: ${{ secrets.ANDROID_PLAYSTORE_KEY_JSON }}
          CARGOKIT_CARGO_PROFILE: ci-release
        working-directory: app
        run: bundle exec fastlane android beta_android upload_to_play_store:true --verbose
