# SPDX-FileCopyrightText: 2024 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Android app

on:
  workflow_call:
    inputs:
      upload:
        description: "Upload the app to the Play Store"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SQLX_OFFLINE: true
  RUSTFLAGS: "-D warnings"

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          # Fetch all commit metadata (client build metadata is derived from git history)
          fetch-depth: 0
          # Don't download historical file contents (blobs)
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          fastlane: true
          jdk: true
          sccache: true
          cargo-binstall-tools: cargo-ndk

      - name: Build Android app
        env:
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_PLAYSTORE_KEY_JSON: ${{ secrets.ANDROID_PLAYSTORE_KEY_JSON }}
        working-directory: app
        run: bundle exec fastlane android beta_android ${{ inputs.upload && 'upload_to_play_store:true' || '' }} --verbose

      - name: Upload Android app APK
        if: ${{ !inputs.upload }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: air-android
          path: app/build/app/outputs/flutter-apk/app-staging-release.apk
          if-no-files-found: error
