# SPDX-FileCopyrightText: 2024 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Android app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: cargo-bins/cargo-binstall@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - run: curl -fsSL https://fvm.app/install.sh | bash

      - name: Install required Java version
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@1.90.0
        with:
          targets: aarch64-linux-android

      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: app/build/airapplogic/build

      - run: cargo binstall cargo-ndk --no-confirm
      - name: Set up Android CI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd app/fastlane && bundle install

      - name: Build Android app
        run: |
          cd app/fastlane && bundle exec fastlane android beta_android --verbose

      - name: Calculate short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload Android app APK
        uses: actions/upload-artifact@v4
        with:
          name: air-${{ steps.vars.outputs.sha_short }}
          path: app/build/app/outputs/flutter-apk/app-release.apk
