# SPDX-FileCopyrightText: 2026 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches: ["main", "release/**"]
  merge_group:

jobs:
  android:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  ios:
    uses: ./.github/workflows/ios.yml
    secrets: inherit

  macos:
    uses: ./.github/workflows/macos.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  windows:
    uses: ./.github/workflows/windows.yml
    secrets: inherit
