# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  RUSTFLAGS: -D warnings
  SQLX_OFFLINE: true

jobs:
  frb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Fetch only last commit, we do not need build_number for CI tests
          fetch-depth: 1
          # Don't download historical file contents (blobs)
          filter: blob:none

      ## CHECK FRB
      - uses: extractions/setup-just@v2
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall flutter_rust_bridge_codegen@2.11.1 --no-confirm
      - run: just install-fvm
      - run: echo /home/runner/fvm/bin >> $GITHUB_PATH
      - run: (cd app && fvm install)
      - run: just check-frb

  flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          lfs: true

      # CHECK FLUTTER
      - uses: extractions/setup-just@v2
      - run: just install-fvm
      - run: echo /home/runner/fvm/bin >> $GITHUB_PATH
      - run: (cd app && fvm install)
      - run: just check-flutter

      # TEST FLUTTER
      - run: just test-flutter
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: golden-failures
          path: app/test/**/failures/*

  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      # CHECK RUST
      - uses: extractions/setup-just@v2
      - uses: dtolnay/rust-toolchain@1.92.0
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny@0.19.0,sqlx-cli@0.8.6,cargo-machete@0.9.1
      - run: pip3 install --user reuse podman-compose
      - uses: Swatinem/rust-cache@v2
      - run: just check-rust

      # TEST RUST
      - run: just test-rust
