# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  SQLX_OFFLINE: true

jobs:
  check:
    name: ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - check: app-resources
          - check: cargo-deny
            cargo-binstall-tools: cargo-deny@0.19.0
          - check: cargo-machete
            cargo-binstall-tools: cargo-machete@0.9.1
          - check: clippy
          - check: dart
          - check: frb
            cargo-binstall-tools: cargo-expand flutter_rust_bridge_codegen@2.12.0
          - check: reuse
            pypi-packages: reuse~=6.2
          - check: rustfmt
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - id: setup-buildenv
        name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          git-lfs: false
          cargo-binstall-tools: ${{ matrix.cargo-binstall-tools }}
          pypi-packages: ${{ matrix.pypi-packages }}

      - run: just check-${{ matrix.check }}

  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv

      - name: Flutter tests
        run: just test-flutter

      - if: failure()
        name: Upload failed tests screenshots
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: app/test/**/failures/*

  rust-build-tests:
    name: Build Rust tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          # pypi-packages: podman-compose~=1.5
          cargo-binstall-tools: cargo-nextest
          flutter: false

      - name: Build cargo test binaries
        run: |
          cargo nextest archive --test integration --archive-file cargo-tests.tar.zst

      - uses: actions/upload-artifact@v7
        with:
          name: test-binaries
          path: cargo-tests.tar.zst

  rust-tests:
    name: Run Rust ${{ matrix.job-name }}
    needs: rust-build-tests
    
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - job-name: integration tests
            nextest-args: --test integration
          - job-name: integration tests (with APQ groups)
            nextest-args: --test integration
            nextest-env: TEST_WITH_APQ_GROUPS=true
          - job-name: unit tests
            nextest-args: --exclude integration

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - uses: actions/download-artifact@v8
        with:
          name: test-binaries

      - name: Setup cargo binstall
        uses: cargo-bins/cargo-binstall@v1.19.0

      - name: Install cargo-nextest
        run: cargo binstall --no-confirm cargo-nextest

      - name: Build cargo test binaries
        run: |
          cargo nextest run --archive-file cargo-tests.tar.zst

