# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_RETRY: 10
  RUSTUP_MAX_RETRIES: 10
  SQLX_OFFLINE: true

jobs:
  check:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Check app resources
            just: check-app-resources
          - name: Check licenses and advisories
            just: check-cargo-deny
            cargo-binstall-tools: cargo-deny@0.19.0
          - name: Find unused crates
            just: check-cargo-machete
            cargo-binstall-tools: cargo-machete@0.9.1
          - name: Rust clippy
            just: check-clippy
          - name: Dart lints
            just: check-dart
          - name: Check FRB
            just: check-frb
            cargo-binstall-tools: cargo-expand flutter_rust_bridge_codegen@2.12.0
          - name: License headers
            just: check-reuse
            pypi-packages: reuse~=6.2
          - name: Rust formatting
            just: check-rustfmt
    
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - id: setup-buildenv
        name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          git-lfs: false
          cargo-binstall-tools: ${{ matrix.cargo-binstall-tools }}
          pypi-packages: ${{ matrix.pypi-packages }}

      - run: just ${{ matrix.just }}

  flutter:
    name: Flutter tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv

      - name: Flutter tests
        run: just test-flutter

      - if: failure()
        name: Upload failed tests screenshots
        uses: actions/upload-artifact@v4
        with:
          name: golden-failures
          path: app/test/**/failures/*

  rust-build-tests:
    name: Build Rust tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          cargo-binstall-tools: cargo-nextest
          flutter: false

      - name: Build cargo test binaries
        run: |
          cargo nextest archive --cargo-profile ci --archive-file cargo-tests.tar.zst

      - uses: actions/upload-artifact@v7
        with:
          name: test-binaries
          path: cargo-tests.tar.zst

  rust-tests:
    name: ${{ matrix.name }}
    needs: rust-build-tests
    
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        include:
          - name: Run Rust unit tests
            profile: default
          - name: Run Rust integration tests
            profile: integration
          - name: Run Rust integration tests (with APQ groups)
            profile: integration-with-apq

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          filter: blob:none

      - name: Download test binaries
        uses: actions/download-artifact@v8
        with:
          name: test-binaries

      - name: Setup build envionment
        uses: ./.github/actions/setup-buildenv
        with:
          cargo-binstall-tools: cargo-nextest
          pypi-packages: podman-compose~=1.5
          flutter: false
          sccache: false

      - name: Run tests
        run: cargo nextest run --archive-file cargo-tests.tar.zst --profile ${{ matrix.profile }}
