# SPDX-FileCopyrightText: 2026 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: CI (Container image)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
    paths: &file-to-hash
      - '.github/workflows/ci_container_image.yml'
      - 'ci/Dockerfile'
      - 'app/.fvmrc'
      - 'rust-toolchain.toml'

jobs:
  build_push_container_image:
    runs-on: ubuntu-latest
    name: Build and push container image
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47

      - name: Hash only changed files
        id: hash
        run: cat "sha256sum=$(${{ steps.changed-files.outputs.all_changed_files }} | sha256sum | cut -d '' -f1)" >> "$GITHUB_OUTPUT"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: ci/Dockerfile
          push: true
          tags: ghcr.io/phnx-im/air/linux-ci-${{ steps.hash.outputs.sha256sum }}