# SPDX-FileCopyrightText: 2026 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Lints

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions: {}

jobs:
  typos:
    name: Check for typos
    runs-on: ubuntu-latest
    steps:
      - name: typos-action
        uses: crate-ci/typos@631208b7aac2daa8b707f55e7331f9112b0e062d # v1.44.0