# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Linux app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SQLX_OFFLINE: true

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch all commit metadata (build number is derived from number of commits)
          fetch-depth: 0
          # Don't download historical file contents (blobs)
          filter: blob:none

      - run: git lfs install && git lfs pull

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@1.94.0

      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall sccache just --no-confirm

      - name: Install build dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: 3.41.4
          cache: true
          cache-sdk: true

      - name: Build desktop app
        uses: ./.github/actions/sccache
        with:
          command: cd app && flutter build linux -v --build-number=$(git rev-list --count HEAD)

      - name: Upload Linux app
        uses: actions/upload-artifact@v4
        with:
          name: linux-app-x64
          path: app/build/linux/x64/release/bundle
