# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Publish macOS app

on:
  push:
    branches:
      - main
    paths:
      - "coreclient/**"
      - "apiclient/**"
      - "applogic/**"
      - "common/**"
      - "app/**"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SQLX_OFFLINE: true

jobs:
  mac-publish:
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch all commit metadata (build number is derived from number of commits)
          fetch-depth: 0
          # Don't download historical file contents (blobs)
          filter: blob:none
          
      - id: setup-buildenv
        name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          fastlane: true

      - name: Build and upload to TestFlight
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_P8_BASE64: ${{ secrets.APP_STORE_KEY_P8_BASE64 }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        working-directory: app
        run: bundle exec fastlane mac beta_macos upload_to_test_flight:true --verbose
