# SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Self-hosted build & tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: [self-hosted, linux, ARM64]
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: phnx_db
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3
      - name: Set up CI
        run: cd prototype && make setup-ci
      - name: Integrate bridge
        run: cd prototype && make frb-integrate
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo nextest run
