# SPDX-FileCopyrightText: 2023 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Test Kubernetes Access

on:
  pull_request:
    branches:
      - main

jobs:
  test-k8s-access:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.18.0'

    - name: Configure kubeconfig
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        mkdir -p $HOME/.kube
        echo "${KUBECONFIG}" > $HOME/.kube/config

    - name: Test Kubernetes access
      run: |
        kubectl get deployments -n default
