# SPDX-FileCopyrightText: 2025 Phoenix R&D GmbH <hello@phnx.im>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Windows app

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    paths:
      - "coreclient/**"
      - "apiclient/**"
      - "applogic/**"
      - "common/**"
      - "app/**"
      - "Cargo.toml"
      - "Cargo.lock"
  merge_group:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  SQLX_OFFLINE: true
  RUSTFLAGS: "-D warnings"

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          # Fetch all commit metadata (build number is derived from number of commits)
          fetch-depth: 0
          # Don't download historical file contents (blobs)
          filter: blob:none

      - id: setup-buildenv
        name: Setup build environment
        uses: ./.github/actions/setup-buildenv
        with:
          sccache: true

      - name: Build Windows app
        working-directory: app
        run: flutter build windows -v --build-number=${{ steps.setup-buildenv.outputs.build-number }}

      # Show sccache stats manually (because it fails in the post setup-buildenv step)
      - name: Show sccache stats
        if: always()
        shell: bash
        run: sccache --show-stats

      - name: Upload Windows app
        uses: actions/upload-artifact@v6
        with:
          name: windows-app-x64
          path: app/build/windows/x64/runner/Release
